<a href="https://colab.research.google.com/github/Octa-p/data_viz_2022/blob/main/Final_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
import os
path = '/content/drive/My Drive/DataViz22_data'

In [4]:
alldb = pd.read_csv(os.path.join(path, 'alldb.csv'))

In [5]:
data_file_path = os.path.join(path,'hospital_list.xlsx')  
hospital = pd.read_excel(data_file_path)

In [6]:
alldb

,Unnamed: 0,user,RowKey,care,date,ov,phone,site,time,urine,pid,PartitionKey,title,age
0,0,test,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,data is not completed,data is not completed
1,1,04857,136FD222-FD9F-4E54-AE1F-7282A276B085,NaN,2022-02-24,NaN,"iPhone10,4",05310,10:50:32,NaN,NaN,NaN,data is not completed,data is not completed
2,2,NaN,1E6D3D62-4C8A-4F8E-90D1-0DC5BC2752DF.png,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,data is not completed,data is not completed
3,3,3450101576642,2D331FB0-CBA2-4586-A5B0-CB3CF44DD9FE,NaN,2022-02-23,0,"iPhone13,4",05087,09:59:47,ปกติ (เหลืองใส),NaN,NaN,data is not completed,data is not completed
4,4,3450101576642,45197AF7-7CB4-470C-9ABB-37C092BD6B21,NaN,2022-02-23,NaN,"iPhone13,4",05087,09:44:06,ปกติ (เหลืองใส),NaN,NaN,data is not completed,data is not completed
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40030,40030,NaN,6B5FA20F-190E-4021-8547-C12308024C6C,NaN,NaN,NaN,"iPhone13,4",01234,NaN,NaN,5,เกษศิรินทร์ ไชยลาภ,data is not completed,data is not completed
40031,40031,NaN,F48C51C0-A345-40D6-93F4-46213267E1B1,NaN,NaN,2,"iPhone10,5",01234,NaN,ปกติ (เหลืองใส),5,เถลิงเกียรติ เสริฐเลิศ,data is not completed,data is not completed
40032,40032,NaN,A986BDAA-6D7C-4017-8E62-A3C104E946B9,NaN,NaN,1,"iPhone13,4",01234,NaN,ปกติ (เหลืองใส),1,เสรี,data is not completed,data is not completed
40033,40033,NaN,bbuogxulur.png,NaN,NaN,NaN,Samsung SM-A115F,01234,NaN,NaN,1,เสรี,data is not completed,data is not completed
40034,40034,NaN,zttpqogiso.png,NaN,NaN,1,Samsung SM-A115F,01234,NaN,ปกติ (เหลืองใส),1,เสรี,data is not completed,data is not completed

# เลือกข้อมูล

In [7]:
alldb_01 = alldb[['user','RowKey','date','phone','site','time','urine','ov','PartitionKey']]
alldb_01

,user,RowKey,date,phone,site,time,urine,ov,PartitionKey
0,test,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,04857,136FD222-FD9F-4E54-AE1F-7282A276B085,2022-02-24,"iPhone10,4",05310,10:50:32,NaN,NaN,NaN
2,NaN,1E6D3D62-4C8A-4F8E-90D1-0DC5BC2752DF.png,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3450101576642,2D331FB0-CBA2-4586-A5B0-CB3CF44DD9FE,2022-02-23,"iPhone13,4",05087,09:59:47,ปกติ (เหลืองใส),0,NaN
4,3450101576642,45197AF7-7CB4-470C-9ABB-37C092BD6B21,2022-02-23,"iPhone13,4",05087,09:44:06,ปกติ (เหลืองใส),NaN,NaN
...,...,...,...,...,...,...,...,...,...
40030,NaN,6B5FA20F-190E-4021-8547-C12308024C6C,NaN,"iPhone13,4",01234,NaN,NaN,NaN,เกษศิรินทร์ ไชยลาภ
40031,NaN,F48C51C0-A345-40D6-93F4-46213267E1B1,NaN,"iPhone10,5",01234,NaN,ปกติ (เหลืองใส),2,เถลิงเกียรติ เสริฐเลิศ
40032,NaN,A986BDAA-6D7C-4017-8E62-A3C104E946B9,NaN,"iPhone13,4",01234,NaN,ปกติ (เหลืองใส),1,เสรี
40033,NaN,bbuogxulur.png,NaN,Samsung SM-A115F,01234,NaN,NaN,NaN,เสรี
40034,NaN,zttpqogiso.png,NaN,Samsung SM-A115F,01234,NaN,ปกติ (เหลืองใส),1,เสรี

# Dropna ข้อมูล

In [8]:
alldb_dp =alldb_01.dropna()
alldb_dp

,user,RowKey,date,phone,site,time,urine,ov,PartitionKey
185,85879,shmpdrmtgc.png,2022-03-24,OPPO CPH2293,05194,13:08:39,มีตะกอน,0,0000
186,45-161,D2CABB8C-533B-450A-AFA6-B693749CC1C6,2022-02-23,"iPhone11,8",04312,09:45:28,ปกติ (เหลืองใส),0,0-1528
187,45-161,57A5F06C-C840-49EA-9514-A30D3C897CC8,2022-02-23,"iPhone11,8",04312,10:06:45,ปกติ (เหลืองใส),0,0-1544
188,27529,ADC54E82-4225-4DE6-89A6-A7E556C15FB1,2022-02-25,"iPhone13,1",04999,14:22:22,ปกติ (เหลืองใส),0,0000
190,06223,kfpwuaqldj.png,2022-03-23,Xiaomi 21081111RG,13777,16:31:45,ปกติ (เหลืองใส),0,00000
...,...,...,...,...,...,...,...,...,...
40013,ttest,crqcufokmn.png,2022-02-21,Samsung SM-G998B,test,14:23:45,ขุ่น,2,x001
40014,ttest,gzxgflnowr.png,2022-02-21,Samsung SM-G998B,test,14:23:43,ขุ่น,2,x001
40016,xxx,jytlopevha.png,2022-02-17,Samsung SM-N950F,xxx,00:01:06,ปกติ (เหลืองใส),3,xxx
40022,yyy,ivccsksowb.png,2022-02-17,Samsung SM-N950F,yyy,08:41:05,มีเม็ดเลือดแดง,2,yyy
40023,zzz,psudrnccsh.png,2022-02-17,Samsung SM-N950F,zzz,08:41:04,มีตะกอน,2,zzz

In [9]:
print (alldb_dp.dtypes)

user            object
RowKey          object
date            object
phone           object
site            object
time            object
urine           object
ov              object
PartitionKey    object
dtype: object

## ต้องการให้ user, site, ov และ PartitionKey เป็นตัวเลขเท่านั้น

In [10]:
import numpy as np

In [11]:
alldb_dp['user'] = pd.to_numeric(alldb_dp['user'], errors='coerce') #errors=’coerce’, you’ll transform the non-numeric values into NaN.
alldb_dp['site'] = pd.to_numeric(alldb_dp['site'], errors='coerce')
alldb_dp['ov'] = pd.to_numeric(alldb_dp['ov'], errors='coerce')
alldb_dp['PartitionKey'] = pd.to_numeric(alldb_dp['PartitionKey'], errors='coerce')

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.

In [12]:
alldb_dp = alldb_dp.replace(np.nan, 5, regex=True)
alldb_dp['user'] = alldb_dp['user'].astype(int)
alldb_dp['site'] = alldb_dp['site'].astype(int)
alldb_dp['ov'] = alldb_dp['ov'].astype(int)
alldb_dp['PartitionKey'] = alldb_dp['PartitionKey'].astype(int)

In [13]:
print (alldb_dp.dtypes)

user             int64
RowKey          object
date            object
phone           object
site             int64
time            object
urine           object
ov               int64
PartitionKey     int64
dtype: object

In [14]:
alldb_dp

,user,RowKey,date,phone,site,time,urine,ov,PartitionKey
185,85879,shmpdrmtgc.png,2022-03-24,OPPO CPH2293,5194,13:08:39,มีตะกอน,0,0
186,5,D2CABB8C-533B-450A-AFA6-B693749CC1C6,2022-02-23,"iPhone11,8",4312,09:45:28,ปกติ (เหลืองใส),0,5
187,5,57A5F06C-C840-49EA-9514-A30D3C897CC8,2022-02-23,"iPhone11,8",4312,10:06:45,ปกติ (เหลืองใส),0,5
188,27529,ADC54E82-4225-4DE6-89A6-A7E556C15FB1,2022-02-25,"iPhone13,1",4999,14:22:22,ปกติ (เหลืองใส),0,0
190,6223,kfpwuaqldj.png,2022-03-23,Xiaomi 21081111RG,13777,16:31:45,ปกติ (เหลืองใส),0,0
...,...,...,...,...,...,...,...,...,...
40013,5,crqcufokmn.png,2022-02-21,Samsung SM-G998B,5,14:23:45,ขุ่น,2,5
40014,5,gzxgflnowr.png,2022-02-21,Samsung SM-G998B,5,14:23:43,ขุ่น,2,5
40016,5,jytlopevha.png,2022-02-17,Samsung SM-N950F,5,00:01:06,ปกติ (เหลืองใส),3,5
40022,5,ivccsksowb.png,2022-02-17,Samsung SM-N950F,5,08:41:05,มีเม็ดเลือดแดง,2,5
40023,5,psudrnccsh.png,2022-02-17,Samsung SM-N950F,5,08:41:04,มีตะกอน,2,5

## ต้องการให้ RowKey, phone และ urine เป็น String

In [15]:
alldb_dp.astype({'RowKey':'string', 'phone':'string','urine':'string'}).dtypes

user             int64
RowKey          string
date            object
phone           string
site             int64
time            object
urine           string
ov               int64
PartitionKey     int64
dtype: object

In [16]:
set(alldb_dp['date'])

{'2022-02-15',
 '2022-02-16',
 '2022-02-17',
 '2022-02-18',
 '2022-02-19',
 '2022-02-20',
 '2022-02-21',
 '2022-02-22',
 '2022-02-23',
 '2022-02-24',
 '2022-02-25',
 '2022-02-26',
 '2022-02-27',
 '2022-02-28',
 '2022-03-01',
 '2022-03-02',
 '2022-03-03',
 '2022-03-04',
 '2022-03-05',
 '2022-03-06',
 '2022-03-07',
 '2022-03-08',
 '2022-03-09',
 '2022-03-10',
 '2022-03-11',
 '2022-03-12',
 '2022-03-13',
 '2022-03-14',
 '2022-03-15',
 '2022-03-16',
 '2022-03-17',
 '2022-03-18',
 '2022-03-19',
 '2022-03-20',
 '2022-03-21',
 '2022-03-22',
 '2022-03-23',
 '2022-03-24',
 '2022-03-25',
 '2022-03-26',
 '2022-03-27',
 '2022-03-28',
 '2022-03-29',
 '2022-03-30',
 '2022-03-31',
 '2022-04-01',
 '2022-04-02',
 '2022-04-03',
 '2022-04-04',
 '2022-04-05'}

### date เป็น YYYY-MM-DD แล้ว

In [17]:
set(alldb_dp['time'])

{'11:58:57',
 '13:20:53',
 '10:50:39',
 '10:20:56',
 '19:20:28',
 '17:36:20',
 '15:15:54',
 '15:31:55',
 '14:50:25',
 '11:32:08',
 '18:34:07',
 '12:47:06',
 '15:44:35',
 '12:43:36',
 '10:11:25',
 '17:51:30',
 '14:17:38',
 '14:54:32',
 '21:49:57',
 '13:57:02',
 '16:21:36',
 '10:06:06',
 '13:29:21',
 '10:33:08',
 '10:29:46',
 '10:04:36',
 '11:47:43',
 '14:45:16',
 '17:23:23',
 '10:40:42',
 '15:52:43',
 '15:11:24',
 '15:12:35',
 '15:36:20',
 '10:44:20',
 '11:53:41',
 '22:18:15',
 '18:12:33',
 '15:40:35',
 '17:16:20',
 '09:34:10',
 '15:20:02',
 '14:13:25',
 '15:24:12',
 '14:06:12',
 '10:34:41',
 '11:06:32',
 '10:08:28',
 '14:40:19',
 '10:49:01',
 '12:43:46',
 '15:27:02',
 '11:00:08',
 '15:51:37',
 '09:50:12',
 '17:46:37',
 '14:11:59',
 '09:35:30',
 '14:25:34',
 '18:45:27',
 '00:57:14',
 '10:02:16',
 '18:17:25',
 '16:30:06',
 '10:43:27',
 '10:55:45',
 '09:58:04',
 '13:11:15',
 '15:39:35',
 '18:12:24',
 '17:52:22',
 '11:46:58',
 '11:51:51',
 '17:14:29',
 '14:31:01',
 '10:29:32',
 '09:57:19',
 '13:27:47',
 '15:25:27',
 '14:23:07',
 '10:53:45',
 '14:59:38',
 '11:19:34',
 '10:30:25',
 '12:16:06',
 '11:04:48',
 '12:34:14',
 '12:12:19',
 '18:45:05',
 '13:17:05',
 '10:47:42',
 '14:18:13',
 '17:01:54',
 '11:24:08',
 '10:52:30',
 '09:10:13',
 '14:29:02',
 '10:46:50',
 '14:30:54',
 '12:17:26',
 '13:06:31',
 '14:55:18',
 '16:00:57',
 '14:28:07',
 '13:49:04',
 '10:09:58',
 '11:42:10',
 '10:10:47',
 '15:17:11',
 '19:21:47',
 '12:51:11',
 '14:07:53',
 '16:52:33',
 '11:31:33',
 '14:44:30',
 '14:13:20',
 '10:40:56',
 '18:23:50',
 '12:34:57',
 '09:33:41',
 '08:30:40',
 '17:20:02',
 '09:59:46',
 '18:58:47',
 '14:46:39',
 '10:06:57',
 '12:04:59',
 '09:47:51',
 '10:30:42',
 '15:11:53',
 '16:52:00',
 '17:32:35',
 '10:05:35',
 '10:18:02',
 '13:53:24',
 '11:52:05',
 '14:08:14',
 '18:18:50',
 '13:02:52',
 '09:17:04',
 '14:12:37',
 '16:42:12',
 '10:59:11',
 '13:12:27',
 '12:36:37',
 '14:42:00',
 '15:15:52',
 '09:38:29',
 '16:02:42',
 '14:42:18',
 '12:34:47',
 '11:16:11',
 '13:43:48',
 '13:38:03',
 '13:47:16',
 '16:22:30',
 '15:39:00',
 '10:14:56',
 '10:44:38',
 '08:15:00',
 '14:12:21',
 '13:52:44',
 '14:21:59',
 '16:36:46',
 '11:55:55',
 '15:07:56',
 '17:21:18',
 '11:01:50',
 '12:00:52',
 '10:18:42',
 '15:01:17',
 '12:00:42',
 '17:48:39',
 '12:01:49',
 '13:56:43',
 '11:53:50',
 '10:11:01',
 '21:11:56',
 '13:02:38',
 '16:13:37',
 '14:57:56',
 '22:00:01',
 '13:40:49',
 '11:45:26',
 '10:30:06',
 '15:00:52',
 '11:45:39',
 '15:03:53',
 '19:34:50',
 '12:21:48',
 '09:59:52',
 '13:26:07',
 '10:32:06',
 '13:18:30',
 '14:16:05',
 '15:46:07',
 '18:05:42',
 '10:50:27',
 '12:12:12',
 '10:19:41',
 '12:15:29',
 '10:46:09',
 '12:00:49',
 '12:19:47',
 '13:51:06',
 '10:00:02',
 '12:00:44',
 '11:17:16',
 '14:32:41',
 '11:50:17',
 '14:21:17',
 '09:50:24',
 '14:48:47',
 '12:23:14',
 '11:22:14',
 '09:33:48',
 '16:39:06',
 '14:33:08',
 '19:54:14',
 '17:50:45',
 '13:41:24',
 '14:49:21',
 '12:30:01',
 '11:36:40',
 '16:21:51',
 '11:22:59',
 '21:21:50',
 '17:25:12',
 '10:38:48',
 '15:19:06',
 '17:04:19',
 '11:42:00',
 '11:16:26',
 '15:42:00',
 '10:15:12',
 '16:24:24',
 '10:54:03',
 '12:24:28',
 '09:41:11',
 '16:49:42',
 '11:04:14',
 '11:33:16',
 '15:06:27',
 '10:35:02',
 '14:04:29',
 '09:44:48',
 '17:22:17',
 '09:56:40',
 '12:31:19',
 '10:33:42',
 '13:55:31',
 '19:53:09',
 '09:30:16',
 '09:51:30',
 '08:36:29',
 '12:38:35',
 '10:13:30',
 '17:59:09',
 '16:31:46',
 '15:02:13',
 '14:18:17',
 '13:05:24',
 '15:52:47',
 '15:31:34',
 '10:36:58',
 '13:52:00',
 '11:14:39',
 '11:54:39',
 '13:57:11',
 '14:34:05',
 '11:41:42',
 '14:34:26',
 '10:49:30',
 '12:22:20',
 '15:33:40',
 '11:47:20',
 '18:01:13',
 '18:08:38',
 '15:05:56',
 '14:23:16',
 '16:27:56',
 '10:45:02',
 '13:33:06',
 '11:13:46',
 '14:01:34',
 '10:23:06',
 '10:42:58',
 '14:51:00',
 '11:36:46',
 '13:59:07',
 '13:01:01',
 '16:32:00',
 '15:29:33',
 '16:26:29',
 '09:44:27',
 '11:26:51',
 '12:25:11',
 '13:15:06',
 '13:33:14',
 '18:15:37',
 '16:28:39',
 '13:00:19',
 '10:44:29',
 '15:43:12',
 '15:53:56',
 '11:55:13',
 '13:04:50',
 '12:51:27',
 '15:00:08',
 '11:37:37',
 '12:59:21',
 '10:52:32',
 '17:55:18',
 '14:57:18',
 '12:08:28',
 '11:49:34',
 '14:13:32',
 '11:37:41',
 '15:45:47',
 '15:02:57',
 '16:07:59',
 '09:38:51',
 '11:36:53',
 '14:53:06',
 '13:54:54',
 '19:14:54',
 '10:10:12',
 '13:32:56',
 '10:42:31',
 '14:48:57',
 '14:15:03',
 '09:26:54',
 '09:58:06',
 '17:10:48',
 '14:14:24',
 '10:47:18',
 '15:11:38',
 '12:06:28',
 '12:47:44',
 '15:20:43',
 '11:10:09',
 '11:20:24',
 '16:49:54',
 '14:39:42',
 '10:14:36',
 '13:54:43',
 '12:02:56',
 '21:27:26',
 '13:31:19',
 '09:18:58',
 '13:36:46',
 '11:37:30',
 '13:43:08',
 '15:04:20',
 '09:45:30',
 '12:15:34',
 '15:34:48',
 '21:24:56',
 '15:47:50',
 '14:09:35',
 '14:15:19',
 '10:54:19',
 '09:53:50',
 '15:19:14',
 '19:25:35',
 '19:18:09',
 '13:51:19',
 '14:55:27',
 '14:19:10',
 '16:50:01',
 '10:14:04',
 '16:38:18',
 '13:54:24',
 '11:41:19',
 '12:52:21',
 '14:19:27',
 '15:24:29',
 '16:07:17',
 '16:37:07',
 '10:37:59',
 '16:33:02',
 '12:15:05',
 '14:27:18',
 '14:26:57',
 '17:08:57',
 '12:24:34',
 '12:18:13',
 '10:56:31',
 '12:53:54',
 '10:47:16',
 '09:55:36',
 '08:46:58',
 '17:49:28',
 '12:27:35',
 '11:49:02',
 '16:58:51',
 '09:04:33',
 '16:34:18',
 '13:13:16',
 '10:19:55',
 '11:22:19',
 '13:39:41',
 '11:00:19',
 '10:33:24',
 '13:48:04',
 '11:28:50',
 '15:39:12',
 '11:44:02',
 '15:38:09',
 '11:29:05',
 '10:40:15',
 '14:59:45',
 '10:51:37',
 '09:28:46',
 '11:42:51',
 '13:52:54',
 '15:42:59',
 '15:25:55',
 '16:49:57',
 '13:29:22',
 '14:33:26',
 '09:02:31',
 '14:15:21',
 '14:24:15',
 '19:58:44',
 '14:03:15',
 '15:48:15',
 '10:46:04',
 '12:11:30',
 '15:43:39',
 '10:33:40',
 '16:56:24',
 '12:49:22',
 '16:56:46',
 '10:56:18',
 '20:21:34',
 '13:57:12',
 '10:49:13',
 '14:31:10',
 '16:54:03',
 '11:01:29',
 '16:09:37',
 '10:44:53',
 '16:05:56',
 '09:43:38',
 '12:00:07',
 '19:45:25',
 '12:45:07',
 '14:00:53',
 '10:50:02',
 '16:47:32',
 '13:28:38',
 '09:37:40',
 '08:44:00',
 '12:57:00',
 '11:00:43',
 '10:23:02',
 '12:40:54',
 '13:27:29',
 '16:05:07',
 '10:38:44',
 '13:21:35',
 '09:50:35',
 '18:27:47',
 '10:26:55',
 '14:30:28',
 '14:37:01',
 '15:10:27',
 '18:30:37',
 '11:00:56',
 '12:03:52',
 '12:33:31',
 '15:26:59',
 '18:09:29',
 '10:32:48',
 '15:28:07',
 '12:25:54',
 '15:51:07',
 '09:48:58',
 '12:59:46',
 '10:48:24',
 '11:49:31',
 '10:36:57',
 '12:01:30',
 '11:44:25',
 '13:21:06',
 '09:26:41',
 '11:23:56',
 '16:22:58',
 '16:08:30',
 '15:03:40',
 '10:37:48',
 '12:46:15',
 '12:19:51',
 '10:07:54',
 '15:53:42',
 '15:26:24',
 '09:43:08',
 '18:54:27',
 '23:01:48',
 '16:23:56',
 '17:09:05',
 '09:40:17',
 '17:05:33',
 '16:07:10',
 '16:23:05',
 '10:30:35',
 '13:27:21',
 '11:54:18',
 '09:26:17',
 '16:43:13',
 '12:14:07',
 '20:00:09',
 '10:02:13',
 '13:25:20',
 '14:10:07',
 '13:33:57',
 '18:11:57',
 '11:50:35',
 '15:19:42',
 '13:54:06',
 '11:13:43',
 '09:34:42',
 '15:10:41',
 '11:21:04',
 '09:48:51',
 '11:41:55',
 '15:45:32',
 '10:34:11',
 '12:24:03',
 '20:46:43',
 '11:03:03',
 '15:01:43',
 '09:55:50',
 '11:18:22',
 '16:58:53',
 '16:02:58',
 '22:55:10',
 '16:18:05',
 '10:08:59',
 '11:47:51',
 '16:28:29',
 '15:16:14',
 '14:52:04',
 '10:13:13',
 '16:55:50',
 '11:59:09',
 '15:27:07',
 '09:53:15',
 '16:07:30',
 '12:32:14',
 '11:16:43',
 '11:15:39',
 '08:56:42',
 '14:46:34',
 '14:51:37',
 '13:53:09',
 '12:29:47',
 '15:00:24',
 '18:48:26',
 '10:05:40',
 '12:28:01',
 '10:43:01',
 '12:00:12',
 '14:36:14',
 '09:19:07',
 '14:56:21',
 '12:38:01',
 '09:35:47',
 '14:25:16',
 '16:08:24',
 '10:21:27',
 '14:01:25',
 '11:30:05',
 '08:46:56',
 '14:03:08',
 '10:42:18',
 '15:31:18',
 '10:07:24',
 '14:50:09',
 '10:36:04',
 '10:33:45',
 '10:47:48',
 '16:09:17',
 '12:15:37',
 '12:04:17',
 '16:25:42',
 '11:45:02',
 '14:29:34',
 '09:44:13',
 '09:10:18',
 '13:56:32',
 '10:20:18',
 '13:24:53',
 '11:37:04',
 '11:26:05',
 '11:34:35',
 '09:23:20',
 '10:32:02',
 '15:47:43',
 '11:31:54',
 '09:08:58',
 '18:48:52',
 '18:26:12',
 '12:12:05',
 '16:25:55',
 '09:53:09',
 '11:32:34',
 '12:37:17',
 '15:22:09',
 '14:12:27',
 '11:54:22',
 '14:22:33',
 '08:54:40',
 '14:54:34',
 '10:11:49',
 '10:55:51',
 '17:35:38',
 '14:28:20',
 '08:34:26',
 '09:46:29',
 '14:23:40',
 '14:24:17',
 '16:04:39',
 '11:10:00',
 '14:46:47',
 '15:56:16',
 '11:59:57',
 '11:17:51',
 '14:43:37',
 '14:05:27',
 '14:05:55',
 '18:54:03',
 '15:59:10',
 '08:22:08',
 '19:25:30',
 '12:15:04',
 '12:23:02',
 '22:47:19',
 '10:45:51',
 '11:05:01',
 '11:07:27',
 '17:23:44',
 '16:11:28',
 '14:15:39',
 '11:42:30',
 '14:48:37',
 '19:22:23',
 '11:35:31',
 '09:54:43',
 '10:09:35',
 '18:16:49',
 '12:45:06',
 '15:49:37',
 '10:12:21',
 '13:25:49',
 '09:56:59',
 '17:24:06',
 '17:24:10',
 '16:10:42',
 '20:22:38',
 '22:07:00',
 '15:52:23',
 '15:51:40',
 '13:57:03',
 '14:16:08',
 '10:21:37',
 '19:27:51',
 '09:07:05',
 '15:30:02',
 '14:44:02',
 '18:56:45',
 '10:44:56',
 '15:49:50',
 '15:09:29',
 '15:23:26',
 '14:10:34',
 '10:13:00',
 '17:12:40',
 '14:41:48',
 '15:25:51',
 '08:46:21',
 '11:02:05',
 '14:57:11',
 '09:58:53',
 '18:03:21',
 '09:05:56',
 '17:37:37',
 '09:08:27',
 '11:25:51',
 '16:09:58',
 '10:41:30',
 '11:31:36',
 '10:07:03',
 '09:57:34',
 '17:16:35',
 '16:21:33',
 '13:55:57',
 '12:13:36',
 '10:12:58',
 '11:25:29',
 '09:08:16',
 '11:04:50',
 '15:39:41',
 '11:44:12',
 '14:18:41',
 '11:25:14',
 '10:22:13',
 '12:09:02',
 '12:32:24',
 '10:59:54',
 '12:44:14',
 '12:21:59',
 '10:00:05',
 '16:19:43',
 '14:48:55',
 '12:59:05',
 '11:00:37',
 '14:34:43',
 '10:02:38',
 '09:44:41',
 '11:45:33',
 '09:53:36',
 '14:53:04',
 '09:16:54',
 '16:08:15',
 '14:32:56',
 '11:05:27',
 '15:11:58',
 '12:05:30',
 '15:18:02',
 '17:04:58',
 '14:32:25',
 '09:40:27',
 '13:21:54',
 '08:22:23',
 '13:42:12',
 '23:47:45',
 '11:36:25',
 '09:48:23',
 '13:56:02',
 '13:35:06',
 '13:29:42',
 '12:47:30',
 '14:11:12',
 '10:21:55',
 '13:28:08',
 '10:46:57',
 '10:40:48',
 '09:59:43',
 '15:24:22',
 '15:32:52',
 '19:55:57',
 '13:53:59',
 '11:33:01',
 '12:03:22',
 '23:26:05',
 '20:00:11',
 '10:58:22',
 '09:00:46',
 '16:30:50',
 '20:40:06',
 '10:59:09',
 '14:44:11',
 '09:30:57',
 '17:07:53',
 '18:24:22',
 '12:29:08',
 '10:37:31',
 '10:54:22',
 '14:07:30',
 '12:14:15',
 '11:18:52',
 '16:45:20',
 '09:24:20',
 '11:55:04',
 '13:08:18',
 '17:57:55',
 '11:44:35',
 '09:48:25',
 '21:23:56',
 '12:29:14',
 '14:58:47',
 '20:29:10',
 '17:14:13',
 '10:43:05',
 '10:27:58',
 '15:03:31',
 '14:57:03',
 '14:14:02',
 '11:34:22',
 '15:37:24',
 '10:13:49',
 '13:01:40',
 '20:31:17',
 '12:52:19',
 '11:47:16',
 '15:52:57',
 '22:52:38',
 '11:06:40',
 '12:02:27',
 '15:23:05',
 '13:00:05',
 '15:05:39',
 '10:03:50',
 '13:03:22',
 '14:05:47',
 '15:29:27',
 '14:14:28',
 '10:38:39',
 '11:47:39',
 '14:57:51',
 '10:19:24',
 '11:31:55',
 '16:20:58',
 '12:30:37',
 '16:03:51',
 '11:14:56',
 '18:40:18',
 '11:54:34',
 '12:32:49',
 '16:05:08',
 '15:11:18',
 '09:26:09',
 '10:48:43',
 '16:47:53',
 '08:14:08',
 '14:09:00',
 '12:11:57',
 '12:10:36',
 '10:36:52',
 '08:59:01',
 '17:37:22',
 '13:48:58',
 '14:33:28',
 '12:59:01',
 '16:21:40',
 '14:15:22',
 '09:01:56',
 '21:56:12',
 '18:12:49',
 '10:37:41',
 '12:05:17',
 '14:29:15',
 '11:21:44',
 '15:42:52',
 '15:38:08',
 '11:21:25',
 '10:55:57',
 '11:19:51',
 '16:24:09',
 '12:43:11',
 '15:14:22',
 '15:47:52',
 '10:19:53',
 '11:37:27',
 '20:33:51',
 '10:13:38',
 '10:37:45',
 '11:19:25',
 '16:51:39',
 '14:40:44',
 '14:42:02',
 '15:40:08',
 '11:02:13',
 '09:14:02',
 '14:20:39',
 '09:59:26',
 '16:15:57',
 '09:05:17',
 '13:16:13',
 '12:16:04',
 '19:35:16',
 '15:38:32',
 '08:14:30',
 '09:17:08',
 '10:46:01',
 '11:39:42',
 '14:19:59',
 '14:21:10',
 '12:34:26',
 '14:19:09',
 '17:42:33',
 '15:14:13',
 '09:23:55',
 '10:20:05',
 '10:36:42',
 '16:15:59',
 '15:36:31',
 '15:52:30',
 '19:45:36',
 '13:05:33',
 '17:10:16',
 '10:36:16',
 '11:53:53',
 '10:23:52',
 '16:03:08',
 '13:00:44',
 '10:22:33',
 '11:08:12',
 '14:59:14',
 '17:54:53',
 '09:54:19',
 '10:25:50',
 '16:02:59',
 '13:29:43',
 '10:59:03',
 '15:12:25',
 '16:02:18',
 '12:20:49',
 '16:50:47',
 '15:41:32',
 '14:02:51',
 '14:26:15',
 '13:26:49',
 '09:36:34',
 '14:35:40',
 '17:45:37',
 '09:44:38',
 '10:26:12',
 '14:06:07',
 '16:32:08',
 '14:30:15',
 '22:45:27',
 '14:23:45',
 '09:45:09',
 '10:30:50',
 '12:30:44',
 '13:35:04',
 '10:58:49',
 '13:47:57',
 '17:04:08',
 '10:41:06',
 '11:10:20',
 '11:36:13',
 '10:29:59',
 '13:49:59',
 '09:58:56',
 '16:16:59',
 '16:34:44',
 '10:46:13',
 '11:44:39',
 '15:49:21',
 '11:59:26',
 '10:25:42',
 '14:25:30',
 '12:00:31',
 '17:36:50',
 '11:51:59',
 '10:02:14',
 '15:48:18',
 '11:04:43',
 '10:40:35',
 '17:45:25',
 '10:35:05',
 '21:42:17',
 '14:07:56',
 '09:35:13',
 '10:01:49',
 '10:36:00',
 '21:56:52',
 '15:29:46',
 '09:12:21',
 '15:21:13',
 '10:08:38',
 '16:59:38',
 '10:19:54',
 '11:48:24',
 '16:38:15',
 '10:35:42',
 '12:12:54',
 '14:41:16',
 '08:25:23',
 '14:48:27',
 '10:31:04',
 '14:03:30',
 '13:49:00',
 '10:23:41',
 '07:07:35',
 '16:42:05',
 '12:57:16',
 '12:18:57',
 '00:47:25',
 '10:40:05',
 '10:07:43',
 '19:40:12',
 '08:13:38',
 '14:15:17',
 '15:42:48',
 '09:32:12',
 '15:58:34',
 '09:30:19',
 '15:18:32',
 '12:04:53',
 '14:39:41',
 '14:32:26',
 '13:19:47',
 '14:16:00',
 '10:04:06',
 '13:59:58',
 ...}

### time เป็น hh-mm-ss แล้ว

## ทำให้ user เป็นตัวเลข 5 หลัก

In [18]:
TF=list()
for each_row in alldb_dp.iterrows():
    if (9999 < each_row[1]['user'] < 100000):  #each_row คือ ตัวเลข
        TF.append(True)
    else:
        TF.append(False)

alldb_dp1= alldb_dp[TF]

In [19]:
alldb_dp1.head()

,user,RowKey,date,phone,site,time,urine,ov,PartitionKey
185,85879,shmpdrmtgc.png,2022-03-24,OPPO CPH2293,5194,13:08:39,มีตะกอน,0,0
188,27529,ADC54E82-4225-4DE6-89A6-A7E556C15FB1,2022-02-25,"iPhone13,1",4999,14:22:22,ปกติ (เหลืองใส),0,0
191,12015,00859DB9-1BD9-4825-B246-3DC25EFD1924,2022-03-30,"iPhone12,3",6307,14:46:08,ปกติ (เหลืองใส),4,1
192,91811,1376ACA2-AFA5-4457-967A-D2FCF908E6A5,2022-03-30,"iPhone14,3",5328,15:27:45,ปกติ (เหลืองใส),4,1
193,95821,1914EE67-CD8F-47EE-A968-2772911AA5DF,2022-03-30,"iPhone13,4",6302,10:16:46,ปกติ (เหลืองใส),3,1

In [20]:
TF2=list()
for each_row in alldb_dp1.iterrows():
    if (9999 < each_row[1]['site'] < 100000):  
        TF2.append(True)
    else:
        TF2.append(False)

alldb_dp2= alldb_dp1[TF2]

In [21]:
alldb_dp2

,user,RowKey,date,phone,site,time,urine,ov,PartitionKey
203,18041,3FBB8FE8-F3EE-4307-8E01-406D7A1B2488,2022-03-28,"iPhone14,3",11158,10:12:10,ปกติ (เหลืองใส),2,1
208,27096,4D1F5F3E-E557-4F64-BEB7-D4FBCADFA43F,2022-03-30,"iPhone14,5",11160,14:56:46,ปกติ (เหลืองใส),0,1
221,76486,73F5F082-6877-4C1F-971D-0485621C1D94,2022-03-18,"iPhone12,1",13949,15:09:50,ปกติ (เหลืองใส),2,1
224,51235,76E4E69A-2C96-4B9D-BF7E-B97D64D3277D,2022-03-21,"iPhone13,3",13987,11:21:56,ปกติ (เหลืองใส),0,1
228,61813,7EED02D6-47C8-4AEE-9B88-5DFBD7836508,2022-03-03,"iPhone12,3",13777,15:59:20,มีเม็ดเลือดแดง,2,1
...,...,...,...,...,...,...,...,...,...
39812,99999,F45E78D3-7D89-47A3-8207-C705377E0E0A,2022-03-11,"iPhone14,2",99999,11:36:34,ขุ่น,1,99999
39813,99999,lnlohgqckf.png,2022-03-10,Samsung SM-G998B,99999,18:10:29,มีตะกอน,0,99999
39814,99999,vkdocpmjiv.png,2022-03-10,Samsung SM-G998B,99999,12:14:41,"ขุ่น, มีเม็ดเลือดแดง",1,99999
39815,99999,vrvyfnvayq.png,2022-03-10,Samsung SM-G998B,99999,13:58:01,ปกติ (เหลืองใส),1,99999
39816,99999,zuhbtvyrce.png,2022-03-10,Samsung SM-G998B,99999,13:57:58,ปกติ (เหลืองใส),1,99999

In [22]:
TF3=list()
for each_row in alldb_dp2.iterrows():
    if (9999 < each_row[1]['PartitionKey'] < 100000):  
        TF3.append(True)
    else:
        TF3.append(False)

alldb_dp3= alldb_dp2[TF3]

In [23]:
alldb_dp3

,user,RowKey,date,phone,site,time,urine,ov,PartitionKey
39370,26462,6C55B69E-8E4C-46B0-B0D7-4754A529EE3C,2022-03-21,"iPhone13,4",11069,10:08:34,ปกติ (เหลืองใส),4,10961
39371,26462,eehzjpxnjw.png,2022-03-22,OPPO CPH1819,11069,10:06:17,ขุ่น,1,10962
39372,26462,cjukggkdgy.png,2022-03-22,OPPO CPH1819,11069,09:33:02,ใส่เป็นน้ำเปล่า,0,10963
39373,26462,wpnaiylzxi.png,2022-03-22,Vivo V2050,11069,09:31:42,ปกติ (เหลืองใส),0,10964
39374,26462,pnqumypemv.png,2022-03-22,Vivo V2050,11069,09:49:16,ปกติ (เหลืองใส),3,10965
...,...,...,...,...,...,...,...,...,...
39812,99999,F45E78D3-7D89-47A3-8207-C705377E0E0A,2022-03-11,"iPhone14,2",99999,11:36:34,ขุ่น,1,99999
39813,99999,lnlohgqckf.png,2022-03-10,Samsung SM-G998B,99999,18:10:29,มีตะกอน,0,99999
39814,99999,vkdocpmjiv.png,2022-03-10,Samsung SM-G998B,99999,12:14:41,"ขุ่น, มีเม็ดเลือดแดง",1,99999
39815,99999,vrvyfnvayq.png,2022-03-10,Samsung SM-G998B,99999,13:58:01,ปกติ (เหลืองใส),1,99999
39816,99999,zuhbtvyrce.png,2022-03-10,Samsung SM-G998B,99999,13:57:58,ปกติ (เหลืองใส),1,99999

In [24]:
alldb_dp3

,user,RowKey,date,phone,site,time,urine,ov,PartitionKey
39370,26462,6C55B69E-8E4C-46B0-B0D7-4754A529EE3C,2022-03-21,"iPhone13,4",11069,10:08:34,ปกติ (เหลืองใส),4,10961
39371,26462,eehzjpxnjw.png,2022-03-22,OPPO CPH1819,11069,10:06:17,ขุ่น,1,10962
39372,26462,cjukggkdgy.png,2022-03-22,OPPO CPH1819,11069,09:33:02,ใส่เป็นน้ำเปล่า,0,10963
39373,26462,wpnaiylzxi.png,2022-03-22,Vivo V2050,11069,09:31:42,ปกติ (เหลืองใส),0,10964
39374,26462,pnqumypemv.png,2022-03-22,Vivo V2050,11069,09:49:16,ปกติ (เหลืองใส),3,10965
...,...,...,...,...,...,...,...,...,...
39812,99999,F45E78D3-7D89-47A3-8207-C705377E0E0A,2022-03-11,"iPhone14,2",99999,11:36:34,ขุ่น,1,99999
39813,99999,lnlohgqckf.png,2022-03-10,Samsung SM-G998B,99999,18:10:29,มีตะกอน,0,99999
39814,99999,vkdocpmjiv.png,2022-03-10,Samsung SM-G998B,99999,12:14:41,"ขุ่น, มีเม็ดเลือดแดง",1,99999
39815,99999,vrvyfnvayq.png,2022-03-10,Samsung SM-G998B,99999,13:58:01,ปกติ (เหลืองใส),1,99999
39816,99999,zuhbtvyrce.png,2022-03-10,Samsung SM-G998B,99999,13:57:58,ปกติ (เหลืองใส),1,99999

In [26]:
hospital

,hcode,name,zone_code,zone_name,provincecode,province,amphurcode,amphur,tamboncode,tambon,code4,name5,code9,name10,short_thai,short_english
0,00001,สำนักงานสาธารณสุขจังหวัดสมุทรปราการ,6,สาขาพื้นที่(ระยอง),11.0,สมุทรปราการ,1.0,เมืองสมุทรปราการ,1.0,ปากน้ำ,1.0,สำนักงานสาธารณสุขจังหวัด,NaN,NaN,สป,SPK
1,00002,สำนักงานสาธารณสุขจังหวัดนนทบุรี,4,สาขาพื้นที่(สระบุรี),12.0,นนทบุรี,1.0,เมืองนนทบุรี,4.0,บางกระสอ,1.0,สำนักงานสาธารณสุขจังหวัด,NaN,NaN,นบ,NBI
2,00003,สำนักงานสาธารณสุขจังหวัดปทุมธานี,4,สาขาพื้นที่(สระบุรี),13.0,ปทุมธานี,1.0,เมืองปทุมธานี,1.0,บางปรอก,1.0,สำนักงานสาธารณสุขจังหวัด,NaN,NaN,ปท,PTE
3,00004,สำนักงานสาธารณสุขจังหวัดพระนครศรีอยุธยา,4,สาขาพื้นที่(สระบุรี),14.0,พระนครศรีอยุธยา,1.0,พระนครศรีอยุธยา,3.0,หอรัตนไชย,1.0,สำนักงานสาธารณสุขจังหวัด,NaN,NaN,อย,AYA
4,00005,สำนักงานสาธารณสุขจังหวัดอ่างทอง,4,สาขาพื้นที่(สระบุรี),15.0,อ่างทอง,1.0,เมืองอ่างทอง,8.0,บ้านอิฐ,1.0,สำนักงานสาธารณสุขจังหวัด,NaN,NaN,อท,ATG
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17098,99990,ศูนย์สุขภาพชุมชนโรงพยาบาลอุตรดิตถ์(สาขา 2 วัดท...,2,สาขาพื้นที่(พิษณุโลก),53.0,อุตรดิตถ์,1.0,เมืองอุตรดิตถ์,1.0,ท่าอิฐ,8.0,ศูนย์สุขภาพชุมชน ของ รพ.,10.0,1 ปฐมภูมิ,อต,UTT
17099,99991,ศูนย์สุขภาพชุมชนโรงพยาบาลกุยบุรี,5,สาขาพื้นที่(ราชบุรี),77.0,ประจวบคีรีขันธ์,2.0,กุยบุรี,1.0,กุยบุรี,8.0,ศูนย์สุขภาพชุมชน ของ รพ.,10.0,1 ปฐมภูมิ,ปข,PKN
17100,99993,ศูนย์สุขภาพชุมชนตำบลวัดเพลง,5,สาขาพื้นที่(ราชบุรี),70.0,ราชบุรี,9.0,วัดเพลง,3.0,วัดเพลง,8.0,ศูนย์สุขภาพชุมชน ของ รพ.,10.0,1 ปฐมภูมิ,รบ,RBR
17101,99996,คลินิกทันตกรรม สสจ.ศรีสะเกษ,10,สาขาพื้นที่(อุบลราชธานี),33.0,ศรีสะเกษ,1.0,เมืองศรีสะเกษ,11.0,โพนข่า,8.0,ศูนย์สุขภาพชุมชน ของ รพ.,10.0,1 ปฐมภูมิ,ศก,SSK
17102,99998,ศูนย์สุขภาพชุมชนตำบลบางแพ,5,สาขาพื้นที่(ราชบุรี),70.0,ราชบุรี,6.0,บางแพ,2.0,วังเย็น,8.0,ศูนย์สุขภาพชุมชน ของ รพ.,10.0,1 ปฐมภูมิ,รบ,RBR

In [27]:
hospital.isnull().any()

hcode            False
name              True
zone_code        False
zone_name         True
provincecode      True
province         False
amphurcode        True
amphur            True
tamboncode        True
tambon            True
code4             True
name5             True
code9             True
name10            True
short_thai        True
short_english     True
dtype: bool

In [33]:
hospital_dp = hospital.dropna()
hospital_dp

,hcode,name,zone_code,zone_name,provincecode,province,amphurcode,amphur,tamboncode,tambon,code4,name5,code9,name10,short_thai,short_english
931,00933,โรงพยาบาลส่งเสริมสุขภาพตำบลสำโรงเหนือ,6,สาขาพื้นที่(ระยอง),11.0,สมุทรปราการ,1.0,เมืองสมุทรปราการ,2.0,สำโรงเหนือ,18.0,โรงพยาบาลส่งเสริมสุขภาพตำบล,10.0,1 ปฐมภูมิ,สป,SPK
932,00934,โรงพยาบาลส่งเสริมสุขภาพตำบลบางเมือง,6,สาขาพื้นที่(ระยอง),11.0,สมุทรปราการ,1.0,เมืองสมุทรปราการ,3.0,บางเมือง,18.0,โรงพยาบาลส่งเสริมสุขภาพตำบล,10.0,1 ปฐมภูมิ,สป,SPK
933,00935,โรงพยาบาลส่งเสริมสุขภาพตำบลเฉลิมพระเกียรติ บ้า...,6,สาขาพื้นที่(ระยอง),11.0,สมุทรปราการ,1.0,เมืองสมุทรปราการ,3.0,บางเมือง,18.0,โรงพยาบาลส่งเสริมสุขภาพตำบล,10.0,1 ปฐมภูมิ,สป,SPK
934,00936,โรงพยาบาลส่งเสริมสุขภาพตำบลบางปูใหม่,6,สาขาพื้นที่(ระยอง),11.0,สมุทรปราการ,1.0,เมืองสมุทรปราการ,8.0,บางปูใหม่,18.0,โรงพยาบาลส่งเสริมสุขภาพตำบล,10.0,1 ปฐมภูมิ,สป,SPK
935,00937,โรงพยาบาลส่งเสริมสุขภาพตำบลแพรกษา,6,สาขาพื้นที่(ระยอง),11.0,สมุทรปราการ,1.0,เมืองสมุทรปราการ,10.0,แพรกษา,18.0,โรงพยาบาลส่งเสริมสุขภาพตำบล,10.0,1 ปฐมภูมิ,สป,SPK
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17098,99990,ศูนย์สุขภาพชุมชนโรงพยาบาลอุตรดิตถ์(สาขา 2 วัดท...,2,สาขาพื้นที่(พิษณุโลก),53.0,อุตรดิตถ์,1.0,เมืองอุตรดิตถ์,1.0,ท่าอิฐ,8.0,ศูนย์สุขภาพชุมชน ของ รพ.,10.0,1 ปฐมภูมิ,อต,UTT
17099,99991,ศูนย์สุขภาพชุมชนโรงพยาบาลกุยบุรี,5,สาขาพื้นที่(ราชบุรี),77.0,ประจวบคีรีขันธ์,2.0,กุยบุรี,1.0,กุยบุรี,8.0,ศูนย์สุขภาพชุมชน ของ รพ.,10.0,1 ปฐมภูมิ,ปข,PKN
17100,99993,ศูนย์สุขภาพชุมชนตำบลวัดเพลง,5,สาขาพื้นที่(ราชบุรี),70.0,ราชบุรี,9.0,วัดเพลง,3.0,วัดเพลง,8.0,ศูนย์สุขภาพชุมชน ของ รพ.,10.0,1 ปฐมภูมิ,รบ,RBR
17101,99996,คลินิกทันตกรรม สสจ.ศรีสะเกษ,10,สาขาพื้นที่(อุบลราชธานี),33.0,ศรีสะเกษ,1.0,เมืองศรีสะเกษ,11.0,โพนข่า,8.0,ศูนย์สุขภาพชุมชน ของ รพ.,10.0,1 ปฐมภูมิ,ศก,SSK
17102,99998,ศูนย์สุขภาพชุมชนตำบลบางแพ,5,สาขาพื้นที่(ราชบุรี),70.0,ราชบุรี,6.0,บางแพ,2.0,วังเย็น,8.0,ศูนย์สุขภาพชุมชน ของ รพ.,10.0,1 ปฐมภูมิ,รบ,RBR

In [34]:
hospital_dp['hcode'] = hospital_dp['hcode'].astype(int)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [36]:
hospital_dp

,hcode,name,zone_code,zone_name,provincecode,province,amphurcode,amphur,tamboncode,tambon,code4,name5,code9,name10,short_thai,short_english
931,933,โรงพยาบาลส่งเสริมสุขภาพตำบลสำโรงเหนือ,6,สาขาพื้นที่(ระยอง),11.0,สมุทรปราการ,1.0,เมืองสมุทรปราการ,2.0,สำโรงเหนือ,18.0,โรงพยาบาลส่งเสริมสุขภาพตำบล,10.0,1 ปฐมภูมิ,สป,SPK
932,934,โรงพยาบาลส่งเสริมสุขภาพตำบลบางเมือง,6,สาขาพื้นที่(ระยอง),11.0,สมุทรปราการ,1.0,เมืองสมุทรปราการ,3.0,บางเมือง,18.0,โรงพยาบาลส่งเสริมสุขภาพตำบล,10.0,1 ปฐมภูมิ,สป,SPK
933,935,โรงพยาบาลส่งเสริมสุขภาพตำบลเฉลิมพระเกียรติ บ้า...,6,สาขาพื้นที่(ระยอง),11.0,สมุทรปราการ,1.0,เมืองสมุทรปราการ,3.0,บางเมือง,18.0,โรงพยาบาลส่งเสริมสุขภาพตำบล,10.0,1 ปฐมภูมิ,สป,SPK
934,936,โรงพยาบาลส่งเสริมสุขภาพตำบลบางปูใหม่,6,สาขาพื้นที่(ระยอง),11.0,สมุทรปราการ,1.0,เมืองสมุทรปราการ,8.0,บางปูใหม่,18.0,โรงพยาบาลส่งเสริมสุขภาพตำบล,10.0,1 ปฐมภูมิ,สป,SPK
935,937,โรงพยาบาลส่งเสริมสุขภาพตำบลแพรกษา,6,สาขาพื้นที่(ระยอง),11.0,สมุทรปราการ,1.0,เมืองสมุทรปราการ,10.0,แพรกษา,18.0,โรงพยาบาลส่งเสริมสุขภาพตำบล,10.0,1 ปฐมภูมิ,สป,SPK
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17098,99990,ศูนย์สุขภาพชุมชนโรงพยาบาลอุตรดิตถ์(สาขา 2 วัดท...,2,สาขาพื้นที่(พิษณุโลก),53.0,อุตรดิตถ์,1.0,เมืองอุตรดิตถ์,1.0,ท่าอิฐ,8.0,ศูนย์สุขภาพชุมชน ของ รพ.,10.0,1 ปฐมภูมิ,อต,UTT
17099,99991,ศูนย์สุขภาพชุมชนโรงพยาบาลกุยบุรี,5,สาขาพื้นที่(ราชบุรี),77.0,ประจวบคีรีขันธ์,2.0,กุยบุรี,1.0,กุยบุรี,8.0,ศูนย์สุขภาพชุมชน ของ รพ.,10.0,1 ปฐมภูมิ,ปข,PKN
17100,99993,ศูนย์สุขภาพชุมชนตำบลวัดเพลง,5,สาขาพื้นที่(ราชบุรี),70.0,ราชบุรี,9.0,วัดเพลง,3.0,วัดเพลง,8.0,ศูนย์สุขภาพชุมชน ของ รพ.,10.0,1 ปฐมภูมิ,รบ,RBR
17101,99996,คลินิกทันตกรรม สสจ.ศรีสะเกษ,10,สาขาพื้นที่(อุบลราชธานี),33.0,ศรีสะเกษ,1.0,เมืองศรีสะเกษ,11.0,โพนข่า,8.0,ศูนย์สุขภาพชุมชน ของ รพ.,10.0,1 ปฐมภูมิ,ศก,SSK
17102,99998,ศูนย์สุขภาพชุมชนตำบลบางแพ,5,สาขาพื้นที่(ราชบุรี),70.0,ราชบุรี,6.0,บางแพ,2.0,วังเย็น,8.0,ศูนย์สุขภาพชุมชน ของ รพ.,10.0,1 ปฐมภูมิ,รบ,RBR

# ลองเชื่อมก่อนแล้วค่อยหา 5 หลัก

In [39]:
alldp_hos = alldb_dp.merge(hospital_dp,how='left',left_on='site',right_on = 'hcode') 
alldp_hos

,user,RowKey,date,phone,site,time,urine,ov,PartitionKey,hcode,...,amphurcode,amphur,tamboncode,tambon,code4,name5,code9,name10,short_thai,short_english
0,85879,shmpdrmtgc.png,2022-03-24,OPPO CPH2293,5194,13:08:39,มีตะกอน,0,0,5194.0,...,9.0,หนองพอก,4.0,กกโพธิ์,18.0,โรงพยาบาลส่งเสริมสุขภาพตำบล,10.0,1 ปฐมภูมิ,รอ,RET
1,5,D2CABB8C-533B-450A-AFA6-B693749CC1C6,2022-02-23,"iPhone11,8",4312,09:45:28,ปกติ (เหลืองใส),0,5,4312.0,...,6.0,สีชมพู,1.0,สีชมพู,18.0,โรงพยาบาลส่งเสริมสุขภาพตำบล,10.0,1 ปฐมภูมิ,ขก,KKN
2,5,57A5F06C-C840-49EA-9514-A30D3C897CC8,2022-02-23,"iPhone11,8",4312,10:06:45,ปกติ (เหลืองใส),0,5,4312.0,...,6.0,สีชมพู,1.0,สีชมพู,18.0,โรงพยาบาลส่งเสริมสุขภาพตำบล,10.0,1 ปฐมภูมิ,ขก,KKN
3,27529,ADC54E82-4225-4DE6-89A6-A7E556C15FB1,2022-02-25,"iPhone13,1",4999,14:22:22,ปกติ (เหลืองใส),0,0,4999.0,...,6.0,บรบือ,19.0,หนองโก,18.0,โรงพยาบาลส่งเสริมสุขภาพตำบล,10.0,1 ปฐมภูมิ,มค,MKM
4,6223,kfpwuaqldj.png,2022-03-23,Xiaomi 21081111RG,13777,16:31:45,ปกติ (เหลืองใส),0,0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38658,5,crqcufokmn.png,2022-02-21,Samsung SM-G998B,5,14:23:45,ขุ่น,2,5,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38659,5,gzxgflnowr.png,2022-02-21,Samsung SM-G998B,5,14:23:43,ขุ่น,2,5,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38660,5,jytlopevha.png,2022-02-17,Samsung SM-N950F,5,00:01:06,ปกติ (เหลืองใส),3,5,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38661,5,ivccsksowb.png,2022-02-17,Samsung SM-N950F,5,08:41:05,มีเม็ดเลือดแดง,2,5,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38662,5,psudrnccsh.png,2022-02-17,Samsung SM-N950F,5,08:41:04,มีตะกอน,2,5,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [40]:
alldp_hosdp = alldp_hos.dropna()

In [41]:
alldp_hosdp

,user,RowKey,date,phone,site,time,urine,ov,PartitionKey,hcode,...,amphurcode,amphur,tamboncode,tambon,code4,name5,code9,name10,short_thai,short_english
0,85879,shmpdrmtgc.png,2022-03-24,OPPO CPH2293,5194,13:08:39,มีตะกอน,0,0,5194.0,...,9.0,หนองพอก,4.0,กกโพธิ์,18.0,โรงพยาบาลส่งเสริมสุขภาพตำบล,10.0,1 ปฐมภูมิ,รอ,RET
1,5,D2CABB8C-533B-450A-AFA6-B693749CC1C6,2022-02-23,"iPhone11,8",4312,09:45:28,ปกติ (เหลืองใส),0,5,4312.0,...,6.0,สีชมพู,1.0,สีชมพู,18.0,โรงพยาบาลส่งเสริมสุขภาพตำบล,10.0,1 ปฐมภูมิ,ขก,KKN
2,5,57A5F06C-C840-49EA-9514-A30D3C897CC8,2022-02-23,"iPhone11,8",4312,10:06:45,ปกติ (เหลืองใส),0,5,4312.0,...,6.0,สีชมพู,1.0,สีชมพู,18.0,โรงพยาบาลส่งเสริมสุขภาพตำบล,10.0,1 ปฐมภูมิ,ขก,KKN
3,27529,ADC54E82-4225-4DE6-89A6-A7E556C15FB1,2022-02-25,"iPhone13,1",4999,14:22:22,ปกติ (เหลืองใส),0,0,4999.0,...,6.0,บรบือ,19.0,หนองโก,18.0,โรงพยาบาลส่งเสริมสุขภาพตำบล,10.0,1 ปฐมภูมิ,มค,MKM
5,12015,00859DB9-1BD9-4825-B246-3DC25EFD1924,2022-03-30,"iPhone12,3",6307,14:46:08,ปกติ (เหลืองใส),4,1,6307.0,...,7.0,พิชัย,2.0,บ้านดารา,18.0,โรงพยาบาลส่งเสริมสุขภาพตำบล,10.0,1 ปฐมภูมิ,อต,UTT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38567,5,4A66E929-ABE2-4CFD-B16C-F57A34A790D2,2022-02-18,"iPhone9,4",5271,10:11:21,ปกติ (เหลืองใส),3,985,5271.0,...,16.0,ศรีสมเด็จ,6.0,โพธิ์สัย,18.0,โรงพยาบาลส่งเสริมสุขภาพตำบล,10.0,1 ปฐมภูมิ,รอ,RET
38568,5,F5AAEAFD-01C4-4DD5-A0B0-3D3AD784F956,2022-02-18,"iPhone9,4",5271,10:23:48,ปกติ (เหลืองใส),2,987,5271.0,...,16.0,ศรีสมเด็จ,6.0,โพธิ์สัย,18.0,โรงพยาบาลส่งเสริมสุขภาพตำบล,10.0,1 ปฐมภูมิ,รอ,RET
38569,68768,D8A3A9EA-929E-4CEB-BFDF-C9BE093EA663,2022-03-24,"iPhone11,8",11088,10:25:32,ปกติ (เหลืองใส),1,99444,11088.0,...,14.0,ห้วยผึ้ง,3.0,นิคมห้วยผึ้ง,7.0,โรงพยาบาลชุมชน,21.0,2.1 ทุติยภูมิระดับต้น,กส,KSN
38570,99771,E04D3D60-B916-40A1-AE77-91CCD89DD084,2022-03-31,"iPhone10,5",5396,11:03:40,ปกติ (เหลืองใส),0,99771,5396.0,...,10.0,คำม่วง,9.0,เนินยาง,18.0,โรงพยาบาลส่งเสริมสุขภาพตำบล,10.0,1 ปฐมภูมิ,กส,KSN
38571,5,8DEB2E46-2F4A-42F8-BE82-F74ECDDCE9EE,2022-02-18,"iPhone9,4",5271,10:23:07,ปกติ (เหลืองใส),3,999,5271.0,...,16.0,ศรีสมเด็จ,6.0,โพธิ์สัย,18.0,โรงพยาบาลส่งเสริมสุขภาพตำบล,10.0,1 ปฐมภูมิ,รอ,RET

In [42]:
CF=list()
for each_row in alldp_hosdp.iterrows():
    if (9999 < each_row[1]['user'] < 100000):  #each_row คือ ตัวเลข
        CF.append(True)
    else:
        CF.append(False)

alldp_hosdp1= alldp_hosdp[CF]

In [43]:
alldp_hosdp1

,user,RowKey,date,phone,site,time,urine,ov,PartitionKey,hcode,...,amphurcode,amphur,tamboncode,tambon,code4,name5,code9,name10,short_thai,short_english
0,85879,shmpdrmtgc.png,2022-03-24,OPPO CPH2293,5194,13:08:39,มีตะกอน,0,0,5194.0,...,9.0,หนองพอก,4.0,กกโพธิ์,18.0,โรงพยาบาลส่งเสริมสุขภาพตำบล,10.0,1 ปฐมภูมิ,รอ,RET
3,27529,ADC54E82-4225-4DE6-89A6-A7E556C15FB1,2022-02-25,"iPhone13,1",4999,14:22:22,ปกติ (เหลืองใส),0,0,4999.0,...,6.0,บรบือ,19.0,หนองโก,18.0,โรงพยาบาลส่งเสริมสุขภาพตำบล,10.0,1 ปฐมภูมิ,มค,MKM
5,12015,00859DB9-1BD9-4825-B246-3DC25EFD1924,2022-03-30,"iPhone12,3",6307,14:46:08,ปกติ (เหลืองใส),4,1,6307.0,...,7.0,พิชัย,2.0,บ้านดารา,18.0,โรงพยาบาลส่งเสริมสุขภาพตำบล,10.0,1 ปฐมภูมิ,อต,UTT
6,91811,1376ACA2-AFA5-4457-967A-D2FCF908E6A5,2022-03-30,"iPhone14,3",5328,15:27:45,ปกติ (เหลืองใส),4,1,5328.0,...,18.0,ฆ้องชัย,3.0,โคกสะอาด,18.0,โรงพยาบาลส่งเสริมสุขภาพตำบล,10.0,1 ปฐมภูมิ,กส,KSN
7,95821,1914EE67-CD8F-47EE-A968-2772911AA5DF,2022-03-30,"iPhone13,4",6302,10:16:46,ปกติ (เหลืองใส),3,1,6302.0,...,5.0,ฟากท่า,4.0,สองห้อง,18.0,โรงพยาบาลส่งเสริมสุขภาพตำบล,10.0,1 ปฐมภูมิ,อต,UTT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38558,68768,899A7591-50C9-40BC-9746-A831A08DE980,2022-03-24,"iPhone11,8",11088,10:29:37,ปกติ (เหลืองใส),0,90470,11088.0,...,14.0,ห้วยผึ้ง,3.0,นิคมห้วยผึ้ง,7.0,โรงพยาบาลชุมชน,21.0,2.1 ทุติยภูมิระดับต้น,กส,KSN
38560,68768,BF39F27C-1B43-4C97-A034-D7A579BED2B6,2022-03-24,"iPhone11,8",11088,10:24:40,ปกติ (เหลืองใส),1,91123,11088.0,...,14.0,ห้วยผึ้ง,3.0,นิคมห้วยผึ้ง,7.0,โรงพยาบาลชุมชน,21.0,2.1 ทุติยภูมิระดับต้น,กส,KSN
38562,76331,pvpiawlexb.png,2022-02-23,Samsung SM-G965U,5258,15:32:53,ปกติ (เหลืองใส),1,92,5258.0,...,14.0,อาจสามารถ,9.0,ขี้เหล็ก,18.0,โรงพยาบาลส่งเสริมสุขภาพตำบล,10.0,1 ปฐมภูมิ,รอ,RET
38569,68768,D8A3A9EA-929E-4CEB-BFDF-C9BE093EA663,2022-03-24,"iPhone11,8",11088,10:25:32,ปกติ (เหลืองใส),1,99444,11088.0,...,14.0,ห้วยผึ้ง,3.0,นิคมห้วยผึ้ง,7.0,โรงพยาบาลชุมชน,21.0,2.1 ทุติยภูมิระดับต้น,กส,KSN
38570,99771,E04D3D60-B916-40A1-AE77-91CCD89DD084,2022-03-31,"iPhone10,5",5396,11:03:40,ปกติ (เหลืองใส),0,99771,5396.0,...,10.0,คำม่วง,9.0,เนินยาง,18.0,โรงพยาบาลส่งเสริมสุขภาพตำบล,10.0,1 ปฐมภูมิ,กส,KSN

In [46]:
CF2=list()
for each_row in alldp_hosdp1.iterrows():
    if (9999 < each_row[1]['site'] < 100000):  #each_row คือ ตัวเลข
        CF2.append(True)
    else:
        CF2.append(False)

alldp_hosdp2 =  alldp_hosdp1[CF2]

In [47]:
alldp_hosdp2

,user,RowKey,date,phone,site,time,urine,ov,PartitionKey,hcode,...,amphurcode,amphur,tamboncode,tambon,code4,name5,code9,name10,short_thai,short_english
17,18041,3FBB8FE8-F3EE-4307-8E01-406D7A1B2488,2022-03-28,"iPhone14,3",11158,10:12:10,ปกติ (เหลืองใส),2,1,11158.0,...,2.0,ตรอน,2.0,บ้านแก่ง,7.0,โรงพยาบาลชุมชน,22.0,2.2 ทุติยภูมิระดับกลาง,อต,UTT
22,27096,4D1F5F3E-E557-4F64-BEB7-D4FBCADFA43F,2022-03-30,"iPhone14,5",11160,14:56:46,ปกติ (เหลืองใส),0,1,11160.0,...,4.0,น้ำปาด,1.0,แสนตอ,7.0,โรงพยาบาลชุมชน,22.0,2.2 ทุติยภูมิระดับกลาง,อต,UTT
35,76486,73F5F082-6877-4C1F-971D-0485621C1D94,2022-03-18,"iPhone12,1",13949,15:09:50,ปกติ (เหลืองใส),2,1,13949.0,...,6.0,พนมไพร,7.0,โคกสว่าง,18.0,โรงพยาบาลส่งเสริมสุขภาพตำบล,10.0,1 ปฐมภูมิ,รอ,RET
38,51235,76E4E69A-2C96-4B9D-BF7E-B97D64D3277D,2022-03-21,"iPhone13,3",13987,11:21:56,ปกติ (เหลืองใส),0,1,13987.0,...,3.0,แม่แจ่ม,8.0,กองแขก,18.0,โรงพยาบาลส่งเสริมสุขภาพตำบล,10.0,1 ปฐมภูมิ,ชม,CMI
55,54614,A4023987-89F9-40AD-B8CB-4EBBE29838E3,2022-04-01,"iPhone13,3",14284,16:28:39,ปกติ (เหลืองใส),0,1,14284.0,...,8.0,ห้วยเม็ก,6.0,พิมูล,18.0,โรงพยาบาลส่งเสริมสุขภาพตำบล,10.0,1 ปฐมภูมิ,กส,KSN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38551,68768,40A5A14E-33E1-4246-95A7-9757D184BC39,2022-03-24,"iPhone11,8",11088,10:31:17,ปกติ (เหลืองใส),1,88432,11088.0,...,14.0,ห้วยผึ้ง,3.0,นิคมห้วยผึ้ง,7.0,โรงพยาบาลชุมชน,21.0,2.1 ทุติยภูมิระดับต้น,กส,KSN
38554,68768,B7F36631-D2C4-4EB5-852D-790BFAFDFD71,2022-03-24,"iPhone11,8",11088,10:30:22,ปกติ (เหลืองใส),2,89170,11088.0,...,14.0,ห้วยผึ้ง,3.0,นิคมห้วยผึ้ง,7.0,โรงพยาบาลชุมชน,21.0,2.1 ทุติยภูมิระดับต้น,กส,KSN
38558,68768,899A7591-50C9-40BC-9746-A831A08DE980,2022-03-24,"iPhone11,8",11088,10:29:37,ปกติ (เหลืองใส),0,90470,11088.0,...,14.0,ห้วยผึ้ง,3.0,นิคมห้วยผึ้ง,7.0,โรงพยาบาลชุมชน,21.0,2.1 ทุติยภูมิระดับต้น,กส,KSN
38560,68768,BF39F27C-1B43-4C97-A034-D7A579BED2B6,2022-03-24,"iPhone11,8",11088,10:24:40,ปกติ (เหลืองใส),1,91123,11088.0,...,14.0,ห้วยผึ้ง,3.0,นิคมห้วยผึ้ง,7.0,โรงพยาบาลชุมชน,21.0,2.1 ทุติยภูมิระดับต้น,กส,KSN
38569,68768,D8A3A9EA-929E-4CEB-BFDF-C9BE093EA663,2022-03-24,"iPhone11,8",11088,10:25:32,ปกติ (เหลืองใส),1,99444,11088.0,...,14.0,ห้วยผึ้ง,3.0,นิคมห้วยผึ้ง,7.0,โรงพยาบาลชุมชน,21.0,2.1 ทุติยภูมิระดับต้น,กส,KSN

In [49]:
CF3=list()
for each_row in alldp_hosdp2.iterrows():
    if (9999 < each_row[1]['PartitionKey'] < 100000):  #each_row คือ ตัวเลข
        CF3.append(True)
    else:
        CF3.append(False)

alldp_hosdp3 =  alldp_hosdp2[CF3]

In [50]:
alldp_hosdp3

,user,RowKey,date,phone,site,time,urine,ov,PartitionKey,hcode,...,amphurcode,amphur,tamboncode,tambon,code4,name5,code9,name10,short_thai,short_english
38180,26462,6C55B69E-8E4C-46B0-B0D7-4754A529EE3C,2022-03-21,"iPhone13,4",11069,10:08:34,ปกติ (เหลืองใส),4,10961,11069.0,...,10.0,เสลภูมิ,17.0,ขวัญเมือง,7.0,โรงพยาบาลชุมชน,22.0,2.2 ทุติยภูมิระดับกลาง,รอ,RET
38181,26462,eehzjpxnjw.png,2022-03-22,OPPO CPH1819,11069,10:06:17,ขุ่น,1,10962,11069.0,...,10.0,เสลภูมิ,17.0,ขวัญเมือง,7.0,โรงพยาบาลชุมชน,22.0,2.2 ทุติยภูมิระดับกลาง,รอ,RET
38182,26462,cjukggkdgy.png,2022-03-22,OPPO CPH1819,11069,09:33:02,ใส่เป็นน้ำเปล่า,0,10963,11069.0,...,10.0,เสลภูมิ,17.0,ขวัญเมือง,7.0,โรงพยาบาลชุมชน,22.0,2.2 ทุติยภูมิระดับกลาง,รอ,RET
38183,26462,wpnaiylzxi.png,2022-03-22,Vivo V2050,11069,09:31:42,ปกติ (เหลืองใส),0,10964,11069.0,...,10.0,เสลภูมิ,17.0,ขวัญเมือง,7.0,โรงพยาบาลชุมชน,22.0,2.2 ทุติยภูมิระดับกลาง,รอ,RET
38184,26462,pnqumypemv.png,2022-03-22,Vivo V2050,11069,09:49:16,ปกติ (เหลืองใส),3,10965,11069.0,...,10.0,เสลภูมิ,17.0,ขวัญเมือง,7.0,โรงพยาบาลชุมชน,22.0,2.2 ทุติยภูมิระดับกลาง,รอ,RET
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38551,68768,40A5A14E-33E1-4246-95A7-9757D184BC39,2022-03-24,"iPhone11,8",11088,10:31:17,ปกติ (เหลืองใส),1,88432,11088.0,...,14.0,ห้วยผึ้ง,3.0,นิคมห้วยผึ้ง,7.0,โรงพยาบาลชุมชน,21.0,2.1 ทุติยภูมิระดับต้น,กส,KSN
38554,68768,B7F36631-D2C4-4EB5-852D-790BFAFDFD71,2022-03-24,"iPhone11,8",11088,10:30:22,ปกติ (เหลืองใส),2,89170,11088.0,...,14.0,ห้วยผึ้ง,3.0,นิคมห้วยผึ้ง,7.0,โรงพยาบาลชุมชน,21.0,2.1 ทุติยภูมิระดับต้น,กส,KSN
38558,68768,899A7591-50C9-40BC-9746-A831A08DE980,2022-03-24,"iPhone11,8",11088,10:29:37,ปกติ (เหลืองใส),0,90470,11088.0,...,14.0,ห้วยผึ้ง,3.0,นิคมห้วยผึ้ง,7.0,โรงพยาบาลชุมชน,21.0,2.1 ทุติยภูมิระดับต้น,กส,KSN
38560,68768,BF39F27C-1B43-4C97-A034-D7A579BED2B6,2022-03-24,"iPhone11,8",11088,10:24:40,ปกติ (เหลืองใส),1,91123,11088.0,...,14.0,ห้วยผึ้ง,3.0,นิคมห้วยผึ้ง,7.0,โรงพยาบาลชุมชน,21.0,2.1 ทุติยภูมิระดับต้น,กส,KSN
38569,68768,D8A3A9EA-929E-4CEB-BFDF-C9BE093EA663,2022-03-24,"iPhone11,8",11088,10:25:32,ปกติ (เหลืองใส),1,99444,11088.0,...,14.0,ห้วยผึ้ง,3.0,นิคมห้วยผึ้ง,7.0,โรงพยาบาลชุมชน,21.0,2.1 ทุติยภูมิระดับต้น,กส,KSN