<a href="https://colab.research.google.com/github/Octa-p/data_viz_2022/blob/main/Final_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [86]:
import pandas as pd

In [87]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [88]:
import os

In [89]:
path = '/content/drive/My Drive/DataViz22_data'
data_cases = pd.read_csv(os.path.join(path, 'confirmed-cases.csv'))
data_cases1 = pd.read_csv(os.path.join(path, 'confirmed-cases-since-120864.csv'))
data_cases2 = pd.read_csv(os.path.join(path, 'confirmed-cases-since-271064.csv'))
data_cases3 = pd.read_csv(os.path.join(path, 'confirmed-cases-since-280265.csv'))

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2882: DtypeWarning: Columns (4) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

# ข้อมูลจำนวนผู้เชื้อช่วงที่ 1

In [90]:
data_cases

,No.,announce_date,Notified date,sex,age,Unit,nationality,province_of_isolation,risk,province_of_onset,district_of_onset
0,1,12/1/2020,NaN,หญิง,61.0,ปี,China,กรุงเทพมหานคร,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,NaN
1,2,17/1/2020,NaN,หญิง,74.0,ปี,China,กรุงเทพมหานคร,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,NaN
2,3,22/1/2020,NaN,หญิง,73.0,ปี,Thailand,นครปฐม,คนต่างชาติเดินทางมาจากต่างประเทศ,นครปฐม,เมือง
3,4,22/1/2020,NaN,ชาย,68.0,ปี,China,กรุงเทพมหานคร,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,NaN
4,5,24/1/2020,NaN,หญิง,66.0,ปี,China,นนทบุรี,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,NaN
...,...,...,...,...,...,...,...,...,...,...,...
839766,839767,12/8/2021,11/8/2021,ชาย,52.0,ปี,NaN,กาญจนบุรี,ทัณฑสถาน/เรือนจำ,กาญจนบุรี,NaN
839767,839768,12/8/2021,11/8/2021,ชาย,34.0,ปี,Thailand,กาญจนบุรี,ทัณฑสถาน/เรือนจำ,กาญจนบุรี,NaN
839768,839769,12/8/2021,11/8/2021,ชาย,31.0,ปี,Thailand,กาญจนบุรี,ทัณฑสถาน/เรือนจำ,กาญจนบุรี,NaN
839769,839770,12/8/2021,11/8/2021,ชาย,83.0,ปี,Thailand,กาญจนบุรี,ทัณฑสถาน/เรือนจำ,กาญจนบุรี,NaN
839770,839771,12/8/2021,11/8/2021,ชาย,47.0,ปี,Thailand,กาญจนบุรี,ทัณฑสถาน/เรือนจำ,กาญจนบุรี,NaN

# ข้อมูลจำนวนผู้เชื้อช่วงที่ 2

In [91]:
data_cases1

,No.,announce_date,Notified date,sex,age,Unit,nationality,province_of_isolation,risk,province_of_onset,district_of_onset
0,816990,12/8/2021,11/8/2021,ชาย,7.0,ปี,Thailand,เชียงราย,อื่นๆ,NaN,NaN
1,816991,12/8/2021,11/8/2021,ชาย,1.0,ปี,Thailand,เชียงราย,อื่นๆ,NaN,NaN
2,816992,12/8/2021,11/8/2021,ชาย,35.0,ปี,Thailand,เชียงราย,อื่นๆ,NaN,NaN
3,816993,12/8/2021,11/8/2021,หญิง,33.0,ปี,Thailand,เชียงราย,อื่นๆ,NaN,NaN
4,816994,12/8/2021,11/8/2021,หญิง,14.0,ปี,Thailand,เชียงราย,สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
1042163,1859153,25/10/2021,24/10/2021,ชาย,45.0,ปี,NaN,กรุงเทพมหานคร,ทัณฑสถาน/เรือนจำ,NaN,NaN
1042164,1859154,25/10/2021,24/10/2021,ชาย,31.0,ปี,NaN,กรุงเทพมหานคร,ทัณฑสถาน/เรือนจำ,NaN,NaN
1042165,1859155,25/10/2021,24/10/2021,ชาย,31.0,ปี,NaN,กรุงเทพมหานคร,ทัณฑสถาน/เรือนจำ,NaN,NaN
1042166,1859156,25/10/2021,24/10/2021,ชาย,24.0,ปี,NaN,กรุงเทพมหานคร,ทัณฑสถาน/เรือนจำ,NaN,NaN
1042167,1859157,25/10/2021,24/10/2021,ชาย,25.0,ปี,NaN,เชียงใหม่,ทัณฑสถาน/เรือนจำ,NaN,NaN

# ข้อมูลจำนวนผู้เชื้อช่วงที่ 3

In [92]:
data_cases2

,No.,announce_date,Notified date,sex,age,Unit,nationality,province_of_isolation,risk,province_of_onset,district_of_onset,Unnamed: 11
0,1859158,26/10/2021,25/10/2021,ชาย,20.0,ปี,Thailand,ลำปาง,อื่นๆ,ลำปาง,เมืองลำปาง,NaN
1,1859159,26/10/2021,25/10/2021,หญิง,42.0,ปี,Thailand,ลำปาง,อื่นๆ,ลำปาง,เมืองลำปาง,NaN
2,1859160,26/10/2021,25/10/2021,หญิง,33.0,ปี,Thailand,ลำปาง,ไปสถานที่ชุมชน เช่น ตลาดนัด สถานที่ท่องเที่ยว,ลำปาง,ห้างฉัตร,NaN
3,1859161,26/10/2021,25/10/2021,หญิง,52.0,ปี,Thailand,ลำปาง,ไปสถานที่ชุมชน เช่น ตลาดนัด สถานที่ท่องเที่ยว,ลำปาง,ห้างฉัตร,NaN
4,1859162,26/10/2021,25/10/2021,หญิง,84.0,ปี,Thailand,ลำปาง,สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้,ลำปาง,เมืองลำปาง,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
1010454,2869612,27/2/2022,26/2/2022,ชาย,NaN,NaN,NaN,กรุงเทพมหานคร,ทัณฑสถาน/เรือนจำ,NaN,NaN,NaN
1010455,2869613,27/2/2022,26/2/2022,ชาย,NaN,NaN,NaN,กรุงเทพมหานคร,ทัณฑสถาน/เรือนจำ,NaN,NaN,NaN
1010456,2869614,27/2/2022,26/2/2022,ชาย,NaN,NaN,NaN,ปัตตานี,ทัณฑสถาน/เรือนจำ,NaN,NaN,NaN
1010457,2869615,27/2/2022,26/2/2022,ชาย,NaN,NaN,NaN,ปัตตานี,ทัณฑสถาน/เรือนจำ,NaN,NaN,NaN
1010458,2869616,27/2/2022,26/2/2022,ชาย,NaN,NaN,NaN,ปัตตานี,ทัณฑสถาน/เรือนจำ,NaN,NaN,NaN

# ข้อมูลจำนวนผู้เชื้อช่วงที่ 4

In [93]:
data_cases3

,No.,announce_date,Notified date,sex,age,Unit,nationality,province_of_isolation,risk,province_of_onset,district_of_onset
0,2869617,28/2/2022,27/2/2022,ชาย,41.0,ปี,Thailand,พะเยา,สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้,พะเยา,เมืองพะเยา
1,2869618,28/2/2022,27/2/2022,หญิง,45.0,ปี,Thailand,พะเยา,สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้,พะเยา,เมืองพะเยา
2,2869619,28/2/2022,27/2/2022,หญิง,40.0,ปี,Thailand,พะเยา,สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้,พะเยา,เมืองพะเยา
3,2869620,28/2/2022,27/2/2022,ชาย,44.0,ปี,Thailand,พะเยา,สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้,พะเยา,เมืองพะเยา
4,2869621,28/2/2022,27/2/2022,ชาย,11.0,ปี,Thailand,พะเยา,สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้,พะเยา,เมืองพะเยา
...,...,...,...,...,...,...,...,...,...,...,...
357076,3226693,15/3/2022,14/3/2022,ชาย,NaN,NaN,NaN,ปราจีนบุรี,ทัณฑสถาน/เรือนจำ,NaN,NaN
357077,3226694,15/3/2022,14/3/2022,ชาย,NaN,NaN,NaN,ปราจีนบุรี,ทัณฑสถาน/เรือนจำ,NaN,NaN
357078,3226695,15/3/2022,14/3/2022,ชาย,NaN,NaN,NaN,นครราชสีมา,ทัณฑสถาน/เรือนจำ,NaN,NaN
357079,3226696,15/3/2022,14/3/2022,ชาย,NaN,NaN,NaN,นครราชสีมา,ทัณฑสถาน/เรือนจำ,NaN,NaN
357080,3226697,15/3/2022,14/3/2022,หญิง,NaN,NaN,NaN,ขอนแก่น,ทัณฑสถาน/เรือนจำ,NaN,NaN

# เตรียมข้อมูล

## ข้อมูลจำนวนผู้เชื้อช่วงที่ 1

In [94]:
data_cases.isnull().any()

No.                      False
announce_date            False
Notified date             True
sex                       True
age                       True
Unit                      True
nationality               True
province_of_isolation     True
risk                      True
province_of_onset         True
district_of_onset         True
dtype: bool

จากการตรวจสอบพบว่า มี column ที่มีค่า missing คือ

*   Notified date 
*   sex
*   age
*   Unit
*   nationality
*   province_of_isolation
*   risk
*   province_of_onset
*   district_of_onset

In [95]:
casedrop = pd.read_csv(os.path.join(path, 'confirmed-cases.csv'))

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2882: DtypeWarning: Columns (4) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

### dropna

In [96]:
casedrop_clean = casedrop.dropna() 
casedrop_clean

,No.,announce_date,Notified date,sex,age,Unit,nationality,province_of_isolation,risk,province_of_onset,district_of_onset
47,48,6/3/2020,4/3/2020,ชาย,43.0,ปี,United Kingdom,กรุงเทพมหานคร,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,คลองตัน
124,125,6/3/2021,5/3/2021,หญิง,55.0,ปี,Thailand,ปทุมธานี,Cluster ตลาดพรพัฒน์,ปทุมธานี,ธัญบุรี
161,162,17/3/2020,21/3/2020,ชาย,14.0,ปี,Thailand,สุราษฎร์ธานี,สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้,สุราษฎร์ธานี,เมือง
181,182,18/3/2020,15/3/2020,ชาย,33.0,ปี,Thailand,ขอนแก่น,สนามมวย,ขอนแก่น,เมือง
186,187,18/3/2020,16/3/2020,ชาย,36.0,ปี,Thailand,ร้อยเอ็ด,สนามมวย,ร้อยเอ็ด,เชียงขวัญ
...,...,...,...,...,...,...,...,...,...,...,...
839391,839392,12/8/2021,11/8/2021,หญิง,83.0,ปี,Thailand,กรุงเทพมหานคร,ไปสถานที่ชุมชน เช่น ตลาดนัด สถานที่ท่องเที่ยว,กรุงเทพมหานคร,วัฒนา
839392,839393,12/8/2021,11/8/2021,ชาย,66.0,ปี,Thailand,กรุงเทพมหานคร,สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้,กรุงเทพมหานคร,บางขุนเทียน
839393,839394,12/8/2021,11/8/2021,หญิง,43.0,ปี,Thailand,กรุงเทพมหานคร,ไปสถานที่ชุมชน เช่น ตลาดนัด สถานที่ท่องเที่ยว,กรุงเทพมหานคร,ประเวศ
839394,839395,12/8/2021,11/8/2021,หญิง,74.0,ปี,Thailand,กรุงเทพมหานคร,ไปสถานที่ชุมชน เช่น ตลาดนัด สถานที่ท่องเที่ยว,กรุงเทพมหานคร,ธนบุรี
839395,839396,12/8/2021,11/8/2021,ชาย,29.0,ปี,Thailand,กรุงเทพมหานคร,อาชีพเสี่ยง เช่น ทำงานในสถานที่แออัด หรือทำงาน...,กรุงเทพมหานคร,ประเวศ

In [97]:
casedrop_clean.isnull().any()

No.                      False
announce_date            False
Notified date            False
sex                      False
age                      False
Unit                     False
nationality              False
province_of_isolation    False
risk                     False
province_of_onset        False
district_of_onset        False
dtype: bool

In [98]:
casedrop_clean.shape #ขนาดของตาราง dropna

(599988, 11)

In [99]:
removes = data_cases.shape[0] - casedrop_clean.shape[0]
print(f'size before drop = {data_cases.shape[0]}')
print(f'size after drop = {casedrop_clean.shape[0]}')
print(f'% from drop = {(removes/data_cases.shape[0])*100}')
 #มีข้อมูลที่หายไป 28% ซึ่งไม่สามารถยอมรับได้

size before drop = 839771
size after drop = 599988
% from drop = 28.553379433202625

### แทน missing ด้วยค่าที่เหมาะสม (fillna())

In [100]:
case = data_cases.fillna(value={'Notified date':'ไม่มีข้อมูล','sex':'ไม่มีข้อมูล','Unit':'ปี','nationality':'ไม่มีข้อมูล','province_of_isolation':'ไม่มีข้อมูล','risk':'ไม่มีข้อมูล','province_of_onset':'ไม่มีข้อมูล','district_of_onset':'ไม่มีข้อมูล'}) #แทนด้วยคำว่า ไม่มีข้อมูล ได้เนื่องจากในตารางมีค่าว่าง และในคอลัมป์ไม่มีค่าเป็นตัวเลขจึงใช้ค่า string ในการแทนที่ได้

In [101]:
case

,No.,announce_date,Notified date,sex,age,Unit,nationality,province_of_isolation,risk,province_of_onset,district_of_onset
0,1,12/1/2020,ไม่มีข้อมูล,หญิง,61.0,ปี,China,กรุงเทพมหานคร,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,ไม่มีข้อมูล
1,2,17/1/2020,ไม่มีข้อมูล,หญิง,74.0,ปี,China,กรุงเทพมหานคร,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,ไม่มีข้อมูล
2,3,22/1/2020,ไม่มีข้อมูล,หญิง,73.0,ปี,Thailand,นครปฐม,คนต่างชาติเดินทางมาจากต่างประเทศ,นครปฐม,เมือง
3,4,22/1/2020,ไม่มีข้อมูล,ชาย,68.0,ปี,China,กรุงเทพมหานคร,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,ไม่มีข้อมูล
4,5,24/1/2020,ไม่มีข้อมูล,หญิง,66.0,ปี,China,นนทบุรี,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,ไม่มีข้อมูล
...,...,...,...,...,...,...,...,...,...,...,...
839766,839767,12/8/2021,11/8/2021,ชาย,52.0,ปี,ไม่มีข้อมูล,กาญจนบุรี,ทัณฑสถาน/เรือนจำ,กาญจนบุรี,ไม่มีข้อมูล
839767,839768,12/8/2021,11/8/2021,ชาย,34.0,ปี,Thailand,กาญจนบุรี,ทัณฑสถาน/เรือนจำ,กาญจนบุรี,ไม่มีข้อมูล
839768,839769,12/8/2021,11/8/2021,ชาย,31.0,ปี,Thailand,กาญจนบุรี,ทัณฑสถาน/เรือนจำ,กาญจนบุรี,ไม่มีข้อมูล
839769,839770,12/8/2021,11/8/2021,ชาย,83.0,ปี,Thailand,กาญจนบุรี,ทัณฑสถาน/เรือนจำ,กาญจนบุรี,ไม่มีข้อมูล
839770,839771,12/8/2021,11/8/2021,ชาย,47.0,ปี,Thailand,กาญจนบุรี,ทัณฑสถาน/เรือนจำ,กาญจนบุรี,ไม่มีข้อมูล

### แทนค่า missing ของ age ด้วย mean()

In [102]:
avg_age = case[['age']].mean() #เติมค่าใหม่โดยคำสั่ง .fillna
case[['age']] = case[['age']].fillna('ปี')

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  """Entry point for launching an IPython kernel.

In [103]:
case.isnull().any()

No.                      False
announce_date            False
Notified date            False
sex                      False
age                      False
Unit                     False
nationality              False
province_of_isolation    False
risk                     False
province_of_onset        False
district_of_onset        False
dtype: bool

จากการเตรียมข้อมูลจะเห็นได้ว่า ข้อมูลของจำนวนติดเชื้อช่วงที่ 1 ไม่มีค่า missing แล้ว

In [104]:
case.isnull().sum()

No.                      0
announce_date            0
Notified date            0
sex                      0
age                      0
Unit                     0
nationality              0
province_of_isolation    0
risk                     0
province_of_onset        0
district_of_onset        0
dtype: int64

### เลือกข้อมูลที่สนใจ

In [105]:
data_01 = case[['announce_date','age','risk','province_of_onset','district_of_onset']]
data_01

,announce_date,age,risk,province_of_onset,district_of_onset
0,12/1/2020,61.0,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,ไม่มีข้อมูล
1,17/1/2020,74.0,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,ไม่มีข้อมูล
2,22/1/2020,73.0,คนต่างชาติเดินทางมาจากต่างประเทศ,นครปฐม,เมือง
3,22/1/2020,68.0,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,ไม่มีข้อมูล
4,24/1/2020,66.0,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,ไม่มีข้อมูล
...,...,...,...,...,...
839766,12/8/2021,52.0,ทัณฑสถาน/เรือนจำ,กาญจนบุรี,ไม่มีข้อมูล
839767,12/8/2021,34.0,ทัณฑสถาน/เรือนจำ,กาญจนบุรี,ไม่มีข้อมูล
839768,12/8/2021,31.0,ทัณฑสถาน/เรือนจำ,กาญจนบุรี,ไม่มีข้อมูล
839769,12/8/2021,83.0,ทัณฑสถาน/เรือนจำ,กาญจนบุรี,ไม่มีข้อมูล
839770,12/8/2021,47.0,ทัณฑสถาน/เรือนจำ,กาญจนบุรี,ไม่มีข้อมูล

## ข้อมูลจำนวนผู้เชื้อช่วงที่ 2

In [106]:
data_cases1.isnull().any()

No.                      False
announce_date            False
Notified date            False
sex                       True
age                       True
Unit                      True
nationality               True
province_of_isolation    False
risk                     False
province_of_onset         True
district_of_onset         True
dtype: bool

จากการตรวจสอบพบว่า มี column ที่มีค่า missing คือ

*   sex
*   age
*   Unit
*   nationality
*   province_of_onset
*   district_of_onset

In [107]:
casedrop2 = pd.read_csv(os.path.join(path, 'confirmed-cases-since-120864.csv'))

### dropna

In [108]:
casedrop2_clean = casedrop2.dropna() 
casedrop2_clean

,No.,announce_date,Notified date,sex,age,Unit,nationality,province_of_isolation,risk,province_of_onset,district_of_onset
249,817239,12/8/2021,11/8/2021,ชาย,48.0,ปี,Thailand,เพชรบูรณ์,สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้,เพชรบูรณ์,เมืองเพชรบูรณ์
250,817240,12/8/2021,11/8/2021,หญิง,19.0,ปี,Thailand,เพชรบูรณ์,สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้,เพชรบูรณ์,เมืองเพชรบูรณ์
251,817241,12/8/2021,11/8/2021,หญิง,37.0,ปี,Thailand,เพชรบูรณ์,สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้,เพชรบูรณ์,เมืองเพชรบูรณ์
252,817242,12/8/2021,11/8/2021,ชาย,46.0,ปี,Thailand,เพชรบูรณ์,สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้,เพชรบูรณ์,เมืองเพชรบูรณ์
253,817243,12/8/2021,11/8/2021,ชาย,60.0,ปี,Thailand,เพชรบูรณ์,สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้,เพชรบูรณ์,เมืองเพชรบูรณ์
...,...,...,...,...,...,...,...,...,...,...,...
1041962,1858952,25/10/2021,24/10/2021,ชาย,67.0,ปี,Thailand,กรุงเทพมหานคร,สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้,กรุงเทพมหานคร,บางพลัด
1041963,1858953,25/10/2021,24/10/2021,หญิง,39.0,ปี,Thailand,กรุงเทพมหานคร,สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้,กรุงเทพมหานคร,บางพลัด
1041964,1858954,25/10/2021,24/10/2021,ชาย,80.0,ปี,Thailand,กรุงเทพมหานคร,อื่นๆ,กรุงเทพมหานคร,สายไหม
1041965,1858955,25/10/2021,24/10/2021,หญิง,67.0,ปี,Thailand,กรุงเทพมหานคร,อื่นๆ,กรุงเทพมหานคร,สายไหม
1041966,1858956,25/10/2021,24/10/2021,หญิง,53.0,ปี,Thailand,กรุงเทพมหานคร,อื่นๆ,กรุงเทพมหานคร,สายไหม

In [109]:
casedrop2_clean.shape #ขนาดของตาราง dropna

(773368, 11)

In [110]:
removes = data_cases1.shape[0] - casedrop2_clean.shape[0]
print(f'size before drop = {data_cases1.shape[0]}')
print(f'size after drop = {casedrop2_clean.shape[0]}')
print(f'% from drop = {(removes/data_cases1.shape[0])*100}')
 #มีข้อมูลที่หายไป 25% ซึ่งไม่สามารถยอมรับได้

size before drop = 1042168
size after drop = 773368
% from drop = 25.792386640157826

### แทน missing ด้วยค่าที่เหมาะสม (fillna())

In [111]:
case1 = data_cases1.fillna(value={'sex':'ไม่มีข้อมูล','Unit':'ปี','nationality':'ไม่มีข้อมูล','province_of_onset':'ไม่มีข้อมูล','district_of_onset':'ไม่มีข้อมูล'})

In [112]:
case1

,No.,announce_date,Notified date,sex,age,Unit,nationality,province_of_isolation,risk,province_of_onset,district_of_onset
0,816990,12/8/2021,11/8/2021,ชาย,7.0,ปี,Thailand,เชียงราย,อื่นๆ,ไม่มีข้อมูล,ไม่มีข้อมูล
1,816991,12/8/2021,11/8/2021,ชาย,1.0,ปี,Thailand,เชียงราย,อื่นๆ,ไม่มีข้อมูล,ไม่มีข้อมูล
2,816992,12/8/2021,11/8/2021,ชาย,35.0,ปี,Thailand,เชียงราย,อื่นๆ,ไม่มีข้อมูล,ไม่มีข้อมูล
3,816993,12/8/2021,11/8/2021,หญิง,33.0,ปี,Thailand,เชียงราย,อื่นๆ,ไม่มีข้อมูล,ไม่มีข้อมูล
4,816994,12/8/2021,11/8/2021,หญิง,14.0,ปี,Thailand,เชียงราย,สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้,ไม่มีข้อมูล,ไม่มีข้อมูล
...,...,...,...,...,...,...,...,...,...,...,...
1042163,1859153,25/10/2021,24/10/2021,ชาย,45.0,ปี,ไม่มีข้อมูล,กรุงเทพมหานคร,ทัณฑสถาน/เรือนจำ,ไม่มีข้อมูล,ไม่มีข้อมูล
1042164,1859154,25/10/2021,24/10/2021,ชาย,31.0,ปี,ไม่มีข้อมูล,กรุงเทพมหานคร,ทัณฑสถาน/เรือนจำ,ไม่มีข้อมูล,ไม่มีข้อมูล
1042165,1859155,25/10/2021,24/10/2021,ชาย,31.0,ปี,ไม่มีข้อมูล,กรุงเทพมหานคร,ทัณฑสถาน/เรือนจำ,ไม่มีข้อมูล,ไม่มีข้อมูล
1042166,1859156,25/10/2021,24/10/2021,ชาย,24.0,ปี,ไม่มีข้อมูล,กรุงเทพมหานคร,ทัณฑสถาน/เรือนจำ,ไม่มีข้อมูล,ไม่มีข้อมูล
1042167,1859157,25/10/2021,24/10/2021,ชาย,25.0,ปี,ไม่มีข้อมูล,เชียงใหม่,ทัณฑสถาน/เรือนจำ,ไม่มีข้อมูล,ไม่มีข้อมูล

### แทนค่า missing ของ age ด้วย mean()

In [113]:
mean_age1 = case1[['age']].mean()

In [114]:
case1[['age']] = case1[['age']].fillna(mean_age1)

In [115]:
case1.isnull().any()

No.                      False
announce_date            False
Notified date            False
sex                      False
age                      False
Unit                     False
nationality              False
province_of_isolation    False
risk                     False
province_of_onset        False
district_of_onset        False
dtype: bool

In [116]:
case1.isnull().sum()

No.                      0
announce_date            0
Notified date            0
sex                      0
age                      0
Unit                     0
nationality              0
province_of_isolation    0
risk                     0
province_of_onset        0
district_of_onset        0
dtype: int64

จากการเตรียมข้อมูลจะเห็นได้ว่า ข้อมูลของจำนวนติดเชื้อช่วงที่ 2 ไม่มีค่า missing แล้ว

### เลือกข้อมูลที่สนใจ

In [117]:
data_02 = case1[['announce_date','age','risk','province_of_onset','district_of_onset']]
data_02

,announce_date,age,risk,province_of_onset,district_of_onset
0,12/8/2021,7.0,อื่นๆ,ไม่มีข้อมูล,ไม่มีข้อมูล
1,12/8/2021,1.0,อื่นๆ,ไม่มีข้อมูล,ไม่มีข้อมูล
2,12/8/2021,35.0,อื่นๆ,ไม่มีข้อมูล,ไม่มีข้อมูล
3,12/8/2021,33.0,อื่นๆ,ไม่มีข้อมูล,ไม่มีข้อมูล
4,12/8/2021,14.0,สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้,ไม่มีข้อมูล,ไม่มีข้อมูล
...,...,...,...,...,...
1042163,25/10/2021,45.0,ทัณฑสถาน/เรือนจำ,ไม่มีข้อมูล,ไม่มีข้อมูล
1042164,25/10/2021,31.0,ทัณฑสถาน/เรือนจำ,ไม่มีข้อมูล,ไม่มีข้อมูล
1042165,25/10/2021,31.0,ทัณฑสถาน/เรือนจำ,ไม่มีข้อมูล,ไม่มีข้อมูล
1042166,25/10/2021,24.0,ทัณฑสถาน/เรือนจำ,ไม่มีข้อมูล,ไม่มีข้อมูล
1042167,25/10/2021,25.0,ทัณฑสถาน/เรือนจำ,ไม่มีข้อมูล,ไม่มีข้อมูล

## ข้อมูลจำนวนผู้เชื้อช่วงที่ 3

In [118]:
data_cases2.isnull().any()

No.                      False
announce_date            False
Notified date            False
sex                       True
age                       True
Unit                      True
nationality               True
province_of_isolation     True
risk                      True
province_of_onset         True
district_of_onset         True
Unnamed: 11               True
dtype: bool

จากการตรวจสอบพบว่า มี column ที่มีค่า missing คือ

*   sex
*   age
*   Unit
*   nationality
*   province_of_isolation
*   risk
*   province_of_onset
*   district_of_onset
*   Unnamed:11

In [119]:
casedrop3 = pd.read_csv(os.path.join(path, 'confirmed-cases-since-271064.csv'))

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2882: DtypeWarning: Columns (4) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

### dropna

In [120]:
casedrop3_clean = casedrop3.dropna() 
casedrop3_clean

Empty DataFrame
Columns: [No., announce_date, Notified date, sex, age, Unit, nationality, province_of_isolation, risk, province_of_onset, district_of_onset, Unnamed: 11]
Index: []

In [121]:
casedrop3_clean.shape #ขนาดของตาราง dropna

(0, 12)

In [122]:
removes = data_cases2.shape[0] - casedrop3_clean.shape[0]
print(f'size before drop = {data_cases2.shape[0]}')
print(f'size after drop = {casedrop3_clean.shape[0]}')
print(f'% from drop = {(removes/data_cases2.shape[0])*100}')
 #มีข้อมูลที่หายไป 29% ซึ่งไม่สามารถยอมรับได้

size before drop = 1010459
size after drop = 0
% from drop = 100.0

### แทน missing ด้วยค่าที่เหมาะสม (fillna())

In [123]:
case2 = data_cases2.fillna(value={'sex':'ไม่มีข้อมูล','Unit':'ปี','nationality':'ไม่มีข้อมูล','province_of_isolation':'ไม่มีข้อมูล','risk':'ไม่มีข้อมูล','province_of_onset':'ไม่มีข้อมูล','district_of_onset':'ไม่มีข้อมูล'})
case2

,No.,announce_date,Notified date,sex,age,Unit,nationality,province_of_isolation,risk,province_of_onset,district_of_onset,Unnamed: 11
0,1859158,26/10/2021,25/10/2021,ชาย,20.0,ปี,Thailand,ลำปาง,อื่นๆ,ลำปาง,เมืองลำปาง,NaN
1,1859159,26/10/2021,25/10/2021,หญิง,42.0,ปี,Thailand,ลำปาง,อื่นๆ,ลำปาง,เมืองลำปาง,NaN
2,1859160,26/10/2021,25/10/2021,หญิง,33.0,ปี,Thailand,ลำปาง,ไปสถานที่ชุมชน เช่น ตลาดนัด สถานที่ท่องเที่ยว,ลำปาง,ห้างฉัตร,NaN
3,1859161,26/10/2021,25/10/2021,หญิง,52.0,ปี,Thailand,ลำปาง,ไปสถานที่ชุมชน เช่น ตลาดนัด สถานที่ท่องเที่ยว,ลำปาง,ห้างฉัตร,NaN
4,1859162,26/10/2021,25/10/2021,หญิง,84.0,ปี,Thailand,ลำปาง,สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้,ลำปาง,เมืองลำปาง,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
1010454,2869612,27/2/2022,26/2/2022,ชาย,NaN,ปี,ไม่มีข้อมูล,กรุงเทพมหานคร,ทัณฑสถาน/เรือนจำ,ไม่มีข้อมูล,ไม่มีข้อมูล,NaN
1010455,2869613,27/2/2022,26/2/2022,ชาย,NaN,ปี,ไม่มีข้อมูล,กรุงเทพมหานคร,ทัณฑสถาน/เรือนจำ,ไม่มีข้อมูล,ไม่มีข้อมูล,NaN
1010456,2869614,27/2/2022,26/2/2022,ชาย,NaN,ปี,ไม่มีข้อมูล,ปัตตานี,ทัณฑสถาน/เรือนจำ,ไม่มีข้อมูล,ไม่มีข้อมูล,NaN
1010457,2869615,27/2/2022,26/2/2022,ชาย,NaN,ปี,ไม่มีข้อมูล,ปัตตานี,ทัณฑสถาน/เรือนจำ,ไม่มีข้อมูล,ไม่มีข้อมูล,NaN
1010458,2869616,27/2/2022,26/2/2022,ชาย,NaN,ปี,ไม่มีข้อมูล,ปัตตานี,ทัณฑสถาน/เรือนจำ,ไม่มีข้อมูล,ไม่มีข้อมูล,NaN

### แทนค่า missing ของ age ด้วย mean()

In [124]:
avg_age3 = case2[['age']].mean() #เติมค่าใหม่โดยคำสั่ง .fillna
case2[['age']] = case2[['age']].fillna('ปี')

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  """Entry point for launching an IPython kernel.

In [125]:
case2.isnull().any()

No.                      False
announce_date            False
Notified date            False
sex                      False
age                      False
Unit                     False
nationality              False
province_of_isolation    False
risk                     False
province_of_onset        False
district_of_onset        False
Unnamed: 11               True
dtype: bool

In [126]:
case2.isnull().sum()

No.                            0
announce_date                  0
Notified date                  0
sex                            0
age                            0
Unit                           0
nationality                    0
province_of_isolation          0
risk                           0
province_of_onset              0
district_of_onset              0
Unnamed: 11              1010459
dtype: int64

ตัด column Unnamed: 11 ออกเนื่องจากไม่ทราบว่าเป็นข้อมูลเกี่ยวกับอะไรและเป็น column ที่ไม่มีความเกี่ยวข้องกัน

In [127]:
case2.drop(['Unnamed: 11'], axis=1, inplace=True)
case2

,No.,announce_date,Notified date,sex,age,Unit,nationality,province_of_isolation,risk,province_of_onset,district_of_onset
0,1859158,26/10/2021,25/10/2021,ชาย,20.0,ปี,Thailand,ลำปาง,อื่นๆ,ลำปาง,เมืองลำปาง
1,1859159,26/10/2021,25/10/2021,หญิง,42.0,ปี,Thailand,ลำปาง,อื่นๆ,ลำปาง,เมืองลำปาง
2,1859160,26/10/2021,25/10/2021,หญิง,33.0,ปี,Thailand,ลำปาง,ไปสถานที่ชุมชน เช่น ตลาดนัด สถานที่ท่องเที่ยว,ลำปาง,ห้างฉัตร
3,1859161,26/10/2021,25/10/2021,หญิง,52.0,ปี,Thailand,ลำปาง,ไปสถานที่ชุมชน เช่น ตลาดนัด สถานที่ท่องเที่ยว,ลำปาง,ห้างฉัตร
4,1859162,26/10/2021,25/10/2021,หญิง,84.0,ปี,Thailand,ลำปาง,สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้,ลำปาง,เมืองลำปาง
...,...,...,...,...,...,...,...,...,...,...,...
1010454,2869612,27/2/2022,26/2/2022,ชาย,ปี,ปี,ไม่มีข้อมูล,กรุงเทพมหานคร,ทัณฑสถาน/เรือนจำ,ไม่มีข้อมูล,ไม่มีข้อมูล
1010455,2869613,27/2/2022,26/2/2022,ชาย,ปี,ปี,ไม่มีข้อมูล,กรุงเทพมหานคร,ทัณฑสถาน/เรือนจำ,ไม่มีข้อมูล,ไม่มีข้อมูล
1010456,2869614,27/2/2022,26/2/2022,ชาย,ปี,ปี,ไม่มีข้อมูล,ปัตตานี,ทัณฑสถาน/เรือนจำ,ไม่มีข้อมูล,ไม่มีข้อมูล
1010457,2869615,27/2/2022,26/2/2022,ชาย,ปี,ปี,ไม่มีข้อมูล,ปัตตานี,ทัณฑสถาน/เรือนจำ,ไม่มีข้อมูล,ไม่มีข้อมูล
1010458,2869616,27/2/2022,26/2/2022,ชาย,ปี,ปี,ไม่มีข้อมูล,ปัตตานี,ทัณฑสถาน/เรือนจำ,ไม่มีข้อมูล,ไม่มีข้อมูล

In [128]:
case2.isnull().any()

No.                      False
announce_date            False
Notified date            False
sex                      False
age                      False
Unit                     False
nationality              False
province_of_isolation    False
risk                     False
province_of_onset        False
district_of_onset        False
dtype: bool

จากการเตรียมข้อมูลจะเห็นได้ว่า ข้อมูลของจำนวนติดเชื้อช่วงที่ 3 ไม่มีค่า missing แล้ว

In [129]:
casedrop3.drop(['Unnamed: 11'], axis=1, inplace=True)
casedrop3

,No.,announce_date,Notified date,sex,age,Unit,nationality,province_of_isolation,risk,province_of_onset,district_of_onset
0,1859158,26/10/2021,25/10/2021,ชาย,20.0,ปี,Thailand,ลำปาง,อื่นๆ,ลำปาง,เมืองลำปาง
1,1859159,26/10/2021,25/10/2021,หญิง,42.0,ปี,Thailand,ลำปาง,อื่นๆ,ลำปาง,เมืองลำปาง
2,1859160,26/10/2021,25/10/2021,หญิง,33.0,ปี,Thailand,ลำปาง,ไปสถานที่ชุมชน เช่น ตลาดนัด สถานที่ท่องเที่ยว,ลำปาง,ห้างฉัตร
3,1859161,26/10/2021,25/10/2021,หญิง,52.0,ปี,Thailand,ลำปาง,ไปสถานที่ชุมชน เช่น ตลาดนัด สถานที่ท่องเที่ยว,ลำปาง,ห้างฉัตร
4,1859162,26/10/2021,25/10/2021,หญิง,84.0,ปี,Thailand,ลำปาง,สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้,ลำปาง,เมืองลำปาง
...,...,...,...,...,...,...,...,...,...,...,...
1010454,2869612,27/2/2022,26/2/2022,ชาย,NaN,NaN,NaN,กรุงเทพมหานคร,ทัณฑสถาน/เรือนจำ,NaN,NaN
1010455,2869613,27/2/2022,26/2/2022,ชาย,NaN,NaN,NaN,กรุงเทพมหานคร,ทัณฑสถาน/เรือนจำ,NaN,NaN
1010456,2869614,27/2/2022,26/2/2022,ชาย,NaN,NaN,NaN,ปัตตานี,ทัณฑสถาน/เรือนจำ,NaN,NaN
1010457,2869615,27/2/2022,26/2/2022,ชาย,NaN,NaN,NaN,ปัตตานี,ทัณฑสถาน/เรือนจำ,NaN,NaN
1010458,2869616,27/2/2022,26/2/2022,ชาย,NaN,NaN,NaN,ปัตตานี,ทัณฑสถาน/เรือนจำ,NaN,NaN

### เลือกข้อมูลที่สนใจ

In [130]:
data_03 = case2[['announce_date','age','risk','province_of_onset','district_of_onset']]
data_03

,announce_date,age,risk,province_of_onset,district_of_onset
0,26/10/2021,20.0,อื่นๆ,ลำปาง,เมืองลำปาง
1,26/10/2021,42.0,อื่นๆ,ลำปาง,เมืองลำปาง
2,26/10/2021,33.0,ไปสถานที่ชุมชน เช่น ตลาดนัด สถานที่ท่องเที่ยว,ลำปาง,ห้างฉัตร
3,26/10/2021,52.0,ไปสถานที่ชุมชน เช่น ตลาดนัด สถานที่ท่องเที่ยว,ลำปาง,ห้างฉัตร
4,26/10/2021,84.0,สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้,ลำปาง,เมืองลำปาง
...,...,...,...,...,...
1010454,27/2/2022,ปี,ทัณฑสถาน/เรือนจำ,ไม่มีข้อมูล,ไม่มีข้อมูล
1010455,27/2/2022,ปี,ทัณฑสถาน/เรือนจำ,ไม่มีข้อมูล,ไม่มีข้อมูล
1010456,27/2/2022,ปี,ทัณฑสถาน/เรือนจำ,ไม่มีข้อมูล,ไม่มีข้อมูล
1010457,27/2/2022,ปี,ทัณฑสถาน/เรือนจำ,ไม่มีข้อมูล,ไม่มีข้อมูล
1010458,27/2/2022,ปี,ทัณฑสถาน/เรือนจำ,ไม่มีข้อมูล,ไม่มีข้อมูล

## ข้อมูลจำนวนผู้เชื้อช่วงที่ 4

In [131]:
data_cases3.isnull().any()

No.                      False
announce_date            False
Notified date            False
sex                       True
age                       True
Unit                      True
nationality               True
province_of_isolation    False
risk                      True
province_of_onset         True
district_of_onset         True
dtype: bool

จากการตรวจสอบพบว่า มี column ที่มีค่า missing คือ

*   sex
*   age
*   Unit
*   nationality
*   risk
*   province_of_onset
*   district_of_onset

In [132]:
casedrop4 = pd.read_csv(os.path.join(path, 'confirmed-cases-since-280265.csv'))

### dropna

In [133]:
casedrop4_clean = casedrop4.dropna() 
casedrop4_clean

,No.,announce_date,Notified date,sex,age,Unit,nationality,province_of_isolation,risk,province_of_onset,district_of_onset
0,2869617,28/2/2022,27/2/2022,ชาย,41.0,ปี,Thailand,พะเยา,สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้,พะเยา,เมืองพะเยา
1,2869618,28/2/2022,27/2/2022,หญิง,45.0,ปี,Thailand,พะเยา,สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้,พะเยา,เมืองพะเยา
2,2869619,28/2/2022,27/2/2022,หญิง,40.0,ปี,Thailand,พะเยา,สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้,พะเยา,เมืองพะเยา
3,2869620,28/2/2022,27/2/2022,ชาย,44.0,ปี,Thailand,พะเยา,สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้,พะเยา,เมืองพะเยา
4,2869621,28/2/2022,27/2/2022,ชาย,11.0,ปี,Thailand,พะเยา,สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้,พะเยา,เมืองพะเยา
...,...,...,...,...,...,...,...,...,...,...,...
357022,3226639,15/3/2022,14/3/2022,หญิง,66.0,ปี,Thailand,กรุงเทพมหานคร,อื่นๆ,กรุงเทพมหานคร,ห้วยขวาง
357023,3226640,15/3/2022,14/3/2022,หญิง,49.0,ปี,Thailand,กรุงเทพมหานคร,อื่นๆ,กรุงเทพมหานคร,ห้วยขวาง
357024,3226641,15/3/2022,14/3/2022,หญิง,19.0,ปี,Thailand,กรุงเทพมหานคร,อื่นๆ,กรุงเทพมหานคร,ราชเทวี
357025,3226642,15/3/2022,14/3/2022,ชาย,66.0,ปี,Thailand,กรุงเทพมหานคร,อื่นๆ,กรุงเทพมหานคร,ลาดพร้าว
357026,3226643,15/3/2022,14/3/2022,ชาย,46.0,ปี,Thailand,กรุงเทพมหานคร,อื่นๆ,กรุงเทพมหานคร,ห้วยขวาง

In [134]:
casedrop4_clean.shape #ขนาดของตาราง dropna

(272319, 11)

In [135]:
removes = data_cases3.shape[0] - casedrop4_clean.shape[0]
print(f'size before drop = {data_cases3.shape[0]}')
print(f'size after drop = {casedrop4_clean.shape[0]}')
print(f'% from drop = {(removes/data_cases3.shape[0])*100}')
 #มีข้อมูลที่หายไป 23% ซึ่งไม่สามารถยอมรับได้

size before drop = 357081
size after drop = 272319
% from drop = 23.737471330034364

### แทน missing ด้วยค่าที่เหมาะสม (fillna())

In [136]:
case3 = data_cases3.fillna(value={'sex':'ไม่มีข้อมูล','Unit':'ปี','nationality':'ไม่มีข้อมูล','risk':'ไม่มีข้อมูล','province_of_onset':'ไม่มีข้อมูล','district_of_onset':'ไม่มีข้อมูล'})
case3

,No.,announce_date,Notified date,sex,age,Unit,nationality,province_of_isolation,risk,province_of_onset,district_of_onset
0,2869617,28/2/2022,27/2/2022,ชาย,41.0,ปี,Thailand,พะเยา,สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้,พะเยา,เมืองพะเยา
1,2869618,28/2/2022,27/2/2022,หญิง,45.0,ปี,Thailand,พะเยา,สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้,พะเยา,เมืองพะเยา
2,2869619,28/2/2022,27/2/2022,หญิง,40.0,ปี,Thailand,พะเยา,สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้,พะเยา,เมืองพะเยา
3,2869620,28/2/2022,27/2/2022,ชาย,44.0,ปี,Thailand,พะเยา,สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้,พะเยา,เมืองพะเยา
4,2869621,28/2/2022,27/2/2022,ชาย,11.0,ปี,Thailand,พะเยา,สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้,พะเยา,เมืองพะเยา
...,...,...,...,...,...,...,...,...,...,...,...
357076,3226693,15/3/2022,14/3/2022,ชาย,NaN,ปี,ไม่มีข้อมูล,ปราจีนบุรี,ทัณฑสถาน/เรือนจำ,ไม่มีข้อมูล,ไม่มีข้อมูล
357077,3226694,15/3/2022,14/3/2022,ชาย,NaN,ปี,ไม่มีข้อมูล,ปราจีนบุรี,ทัณฑสถาน/เรือนจำ,ไม่มีข้อมูล,ไม่มีข้อมูล
357078,3226695,15/3/2022,14/3/2022,ชาย,NaN,ปี,ไม่มีข้อมูล,นครราชสีมา,ทัณฑสถาน/เรือนจำ,ไม่มีข้อมูล,ไม่มีข้อมูล
357079,3226696,15/3/2022,14/3/2022,ชาย,NaN,ปี,ไม่มีข้อมูล,นครราชสีมา,ทัณฑสถาน/เรือนจำ,ไม่มีข้อมูล,ไม่มีข้อมูล
357080,3226697,15/3/2022,14/3/2022,หญิง,NaN,ปี,ไม่มีข้อมูล,ขอนแก่น,ทัณฑสถาน/เรือนจำ,ไม่มีข้อมูล,ไม่มีข้อมูล

### แทนค่า missing ของ age ด้วย mean()

In [137]:
mean_age3 = case3[['age']].mean() 
mean_age3

age    36.943725
dtype: float64

In [138]:
case3[['age']] = case3[['age']].fillna(mean_age3)

In [139]:
case3.isnull().any()

No.                      False
announce_date            False
Notified date            False
sex                      False
age                      False
Unit                     False
nationality              False
province_of_isolation    False
risk                     False
province_of_onset        False
district_of_onset        False
dtype: bool

In [140]:
case3.isnull().sum()

No.                      0
announce_date            0
Notified date            0
sex                      0
age                      0
Unit                     0
nationality              0
province_of_isolation    0
risk                     0
province_of_onset        0
district_of_onset        0
dtype: int64

จากการเตรียมข้อมูลจะเห็นได้ว่า ข้อมูลของจำนวนติดเชื้อช่วงที่ 3 ไม่มีค่า missing แล้ว

### เลือกข้อมูลที่สนใจ

In [141]:
data_04 = case3[['announce_date','age','risk','province_of_onset','district_of_onset']]
data_04

,announce_date,age,risk,province_of_onset,district_of_onset
0,28/2/2022,41.000000,สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้,พะเยา,เมืองพะเยา
1,28/2/2022,45.000000,สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้,พะเยา,เมืองพะเยา
2,28/2/2022,40.000000,สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้,พะเยา,เมืองพะเยา
3,28/2/2022,44.000000,สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้,พะเยา,เมืองพะเยา
4,28/2/2022,11.000000,สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้,พะเยา,เมืองพะเยา
...,...,...,...,...,...
357076,15/3/2022,36.943725,ทัณฑสถาน/เรือนจำ,ไม่มีข้อมูล,ไม่มีข้อมูล
357077,15/3/2022,36.943725,ทัณฑสถาน/เรือนจำ,ไม่มีข้อมูล,ไม่มีข้อมูล
357078,15/3/2022,36.943725,ทัณฑสถาน/เรือนจำ,ไม่มีข้อมูล,ไม่มีข้อมูล
357079,15/3/2022,36.943725,ทัณฑสถาน/เรือนจำ,ไม่มีข้อมูล,ไม่มีข้อมูล
357080,15/3/2022,36.943725,ทัณฑสถาน/เรือนจำ,ไม่มีข้อมูล,ไม่มีข้อมูล

## แก้คำผิดของข้อมูลแต่ละช่วง

In [142]:
data_01['province_of_onset'].replace({'USA':'ไม่มีข้อมูล','\tประจวบคีรีขันธ์':'ประจวบคีรีขันธ์','\xa0กาญจนบุรี':'กาญจนบุรี','\xa0ชลบุรี':'ชลบุรี','\xa0ตราด':'ตราด','\xa0นครปฐม':'นครปฐม',
                                         '\xa0สมุทรสงคราม':'สมุทรสงคราม','\xa0สมุทรสาคร':'สมุทรสาคร','\xa0อุทัยธานี':'อุทัยธานี','กทม':'กรุงเทพมหานคร','กทม.':'กรุงเทพมหานคร','กบินทร์บุรี':'ปราจีนบุรี','กระบี่ี่':'กระบี่','กรุงเทพ':'กรุงเทพมหานคร',
                                         'กรุงเทพมหานคร.':'กรุงเทพมหานคร','กรุงเทพมหานคร. / พระนครศรีอยุธยา':'กรุงเทพมหานคร','กรุงเทพมหานคร. / ศรีสะเกษ':'กรุงเทพมหานคร','กรุงเทพฯ':'กรุงเทพมหานคร','กะทู้':'ภูเก็ต',
                                         'กัมพูชา':'ไม่มีข้อมูล','กาญจบุรี':'กาญจนบุรี','กาญนบุรี':'กาญจนบุรี','กาฬสิน':'กาฬสินธุ์','กาฬสินธิ์':'กาฬสินธุ์','กาฬสินธุ์\xa0':'กาฬสินธุ์','กาฬสินธ์':'กาฬสินธุ์',
                                         'กำเพงเพชร':'กำแพงเพชร','กำแพง':'กำแพงเพชร','กำแพงเพชร':'กำแพงเพชร','กำแพงเพชร\xa0':'กำแพงเพชร','กําแพงเพชร':'กำแพงเพชร',
                                         'ขอนแก่น\xa0':'ขอนแก่น','ขอนแก่่น':'ขอนแก่น','ขานุวรลักษณ์บุรี':'กำแพงเพชร','คนไทยเดินทางกลับจากต่างประเทศ':'ไม่มีข้อมูล','คลองเตย':'กรุงเทพมหานคร','จ.กรุงเทพมหานคร':'กรุงเทพมหานคร',
                                         'จ.ภูเก็ต':'ภูเก็ต','จ.ราชบุรี':'ราชบุรี','จ.สุราษฎร์ธานี':'สุราษฎร์ธานี','จังหวัดสมุทรสาคร':'สมุทรสาคร','ฉะเชองเทราร':'ฉะเชิงเทรา','ชมพร':'ชุมพร',
                                         'ชลบุรี\t':'ชลบุรี','ชลบุรี\xa0':'ชลบุรี','ชลบุุรี':'ชลบุรี','ชอนแก่น':'ขอนแก่น','ชัยนาถ':'ชัยนาท','ชัยบาดาล':'ลพบุรี','ชัยภูมิ\xa0':'ชัยภูมิ','ชุุมพร':'ชุมพร','ชุุุมพร':'ชุมพร',
                                         'ดอนมดแดง':'อุบลราชธานี','ดินแดง':'กรุงเทพมหานคร','ตรััง':'ตรัง','ตราด\xa0':'ตราด','ตากใบ':'นราธิวาส','ต่างจังหวัด':'ไม่มีข้อมูล','ทุ่งเสลี่ยม':'สุโขทัย',
                                         'ท้ายบ้าน':'สมุทรปราการ','ธารโต':'ยะลา','นคนปฐม':'นครปฐม','นคปฐม':'นครปฐม','นครนปฐม':'นครปฐม','นครนาชสีมา':'นครราชสีมา','นครปฐม\xa0':'นครปฐม',
                                         'นครปบม':'นครปฐม','นครพนม\xa0':'นครพนม','นครยายก':'นครนายก','นครราขสีมา':'นครราชสีมา','นครราชธานี':'นครราชสีมา','นครราชศรีมา':'นครราชสีมา','นครราชสสีมา':'นครราชสีมา',
                                         'นครราชสีมา ลพบุรี':'นครราชสีมา','นครราชสีมา\xa0':'นครราชสีมา','นครศรธรรมราช':'นครศรีธรรมราช','นครศรี':'นครศรีธรรมราช','นครศรีธรมมราช':'นครศรีธรรมราช',
                                         'นครศรีธรมราช':'นครศรีธรรมราช','นครศรีธรรมราข':'นครศรีธรรมราช','นครศรีฯ':'นครศรีธรรมราช','นครศรีีธรรมราช':'นครศรีธรรมราช','นครศร๊ธรรมราช':'นครศรีธรรมราช',
                                         'นครศร๊ะรรมราช':'นครศรีธรรมราช','นครสรรค์':'นครสวรรค์','นครสรีธรรมราช':'นครศรีธรรมราช','นครสวรรค':'นครสวรรค์','นครสวรรค์\xa0':'นครสวรรค์','นครสีธรรมราช':'นครศรีธรรมราช',
                                         'นครฯ':'นครศรีธรรมราช','นคราชสีมา':'นครราชสีมา','นครีศรีธรรมราช':'นครศรีธรรมราช','นตรนายก':'นครนายก','นตรปฐม':'นครปฐม','นนทบุรี\xa0':'นนทบุรี',
                                         'นนทบุุรี':'นนทบุรี','นนทุบรี':'นนทบุรี','นนทุรี':'นนทบุรี','นนมบุรี':'นนทบุรี','นรศรีธรรมราช':'นครศรีธรรมราช','นราธิวาส\u200b':'นราธิวาส','นราธฺวาส':'นราธิวาส','นอกเขต':'ไม่มีข้อมูล',
                                         'นาราธิวาส':'นราธิวาส','นาวัง':'หนองบัวลำภู','น่าน/ฉะเชิงเทรา':'น่าน','บางกรวย':'นนทบุรี','บางกะปิ':'กรุงเทพมหานคร','บางนา':'กรุงเทพมหานคร','บางปะอิน':'กรุงเทพมหานคร',
                                         'บางละมุง':'ชลบุรี','บางศรีเมือง':'นนทบุรี','บางเพียง':'สมุทรปราการ','บึงโขงหลง':'บึงกาฬ','บุรีรัมภ์':'บุรีรัมย์','บุรีรัมย์\xa0':'บุรีรัมย์','บุรีรัยม์':'บุรีรัมย์','บุรีรีมย์':'บุรีรัมย์',
                                         'บ้านหลวง':'น่าน','ปจ':'ไม่มีข้อมูล','ปทึมธานี':'ปทุมธานี','ปทุทธานี':'ปทุมธานี','ปทุมฑานี':'ปทุมธานี','ปทุมทานี':'ปทุมธานี','ปทุมธาน':'ปทุมธานี','ปทุมธานี\xa0':'ปทุมธานี','ปทุมาธานี':'ปทุมธานี',
                                         'ปธุมธานี':'ปทุมธานี','ปทุมธานี.':'ปทุมธานี','ปทุมธานีี':'ปทุมธานี','ปทุุมธานี':'ปทุมธานี','ปมุมธานี':'ปทุมธานี',
                                         'ประจวนคีรีขันธ็':'ประจวบคีรีขันธ์','ประจวบ':'ประจวบคีรีขันธ์','ประจวบคิรีขันธ์':'ประจวบคีรีขันธ์','ประจวบคีรขันธ์':'ประจวบคีรีขันธ์','ประจวบคีรขัันธ์':'ประจวบคีรีขันธ์','ประจวบคีรีขัน':'ประจวบคีรีขันธ์',
                                         'ประจวบคีรีขันธื':'ประจวบคีรีขันธ์','ประจวบคีรีขันธฺ':'ประจวบคีรีขันธ์','ประจวบคีรีขันธ์\xa0':'ประจวบคีรีขันธ์','ประจวบคีรีขันธ์์':'ประจวบคีรีขันธ์','ประจวบคีรีขัันธ์':'ประจวบคีรีขันธ์','ประจวบคีีรีขันธ์':'ประจวบคีรีขันธ์',
                                         'ประจวบฯ':'ประจวบคีรีขันธ์','ประทุมธานี':'ปทุมธานี', 'ประเทศกัมพูชา':'ไม่มีข้อมูล','ปราจีบุรี':'ปราจีนบุรี','ปลวกแดง':'ระยอง','ปลายพระยา':'กระบี่', 'ปอยเปต':'ไม่มีข้อมูล','ปัตตนรี':'ปัตตานี',
                                         'ปัตตานนี':'ปัตตานี','ปัตตานีี':'ปัตตานี','ปัว':'น่าน','ปััตตานี':'ปัตตานี','ปุทมธานี':'ปทุมธานี','ป่าโมก':'อ่างทอง','พม่า':'ไม่มีข้อมูล','พรหมพิราม':'พิษณุโลก','พระนครศรียุธยา':'พระนครศรีอยุธยา',
                                         'พระนครศรีอยุทธยา':'พระนครศรีอยุธยา','พระนครศรีอยุทยา':'พระนครศรีอยุธยา','พระนครศรีอยุธยา\xa0':'พระนครศรีอยุธยา','พัทยา':'ชลบุรี','พัทลุุง':'พัทลุง','พัังงา':'พังงา',
                                         'พิษณุโลก\xa0':'พิษณุโลก','พิษณูโลก':'พิษณุโลก','ฟินแลนด์':'ไม่มีข้อมูล','ภาษีเจริญ':'กรุงเทพมหานคร','ภุเก็ต':'ภูเก็ต','ภูุเก็ต':'ภูเก็ต','ภููเก็ต':'ภูเก็ต','ภูเก็็ต':'ภูเก็ต','ภูเพียง':'น่าน',
                                         'มหาสาคาม':'มหาสารคาม','มาเลเซีย':'ไม่มีข้อมูล','มุกาดหาร':'มุกดาหาร','ยานนาวา':'กรุงเทพมหานคร','ร.จ.จ.นราธิวาส':'นราธิวาส','รอ':'ร้อยเอ็ด','ระบุ':'ไม่มีข้อมูล','ระยอง\xa0':'ระยอง',
                                         'ระอยง':'ระยอง','ราชบบุรี':'ราชบุรี','ราชบุรีี':'ราชบุรี','ราชบุรี\u200b':'ราชบุรี','ราชุรี':'ราชบุรี','ราชเทวี':'กรุงเทพมหานคร','ร้องกวาง':'แพร่','ลบุรี':'ลพบุรี','ลพบุรี.':'ลพบุรี','ลพบุรี\xa0':'ลพบุรี','ลอง':'แพร่',
                                         'ลาดกระบัง':'กรุงเทพมหานคร','ลาดพร้าว':'กรุงเทพมหานคร','ลาว':'ไม่มีข้อมูล','ลำพูน\u200b':'ลำพูน','ลำพููน':'ลำพูน','ลำลูกกา':'ปทุมธานี','วังชิ้น':'ลำปาง','วังทอง':'พิษณุโลก',
                                         'วิเศษชัยชาญ':'อ่างทอง','ศรีษะสะเกษ':'ศรีสะเกษ','ศรีษะเกษ':'ศรีสะเกษ','ศรีสระเกษ':'ศรีสะเกษ','ศีรสะเกษ':'ศรีสะเกษ','สครสวรรค์':'นครสวรรค์',
                                         'สงขลา\u200b':'สงขลา','สถานที่ทำงาน':'ไม่มีข้อมูล','สพรรณบุรี':'สุพรรณบุรี','สมถทรปราการ':'สมุทรปราการ','สมทรสงคราม':'สมุทรสงคราม','สมทรสาคร':'สมุทรสาคร','สมุครปราการ':'สมุทรปราการ',
                                         'สมุครสาคร':'สมุทรสาคร','สมุท':'ไม่มีข้อมูล','สมุทปราการ':'สมุทรปราการ','สมุทรปรากร':'สมุทรปราการ','สมุทรปรากรร':'สมุทรปราการ','สมุทรปราการ\xa0':'สมุทรปราการ','สมุทรศาคร':'สมุทรสาคร',
                                         'สมุทรสาคร\xa0':'สมุทรสาคร','สมุทรสาคา':'สมุทรสาคร','สมุทรสาคาร':'สมุทรสาคร','สมุทรสาทร':'สมุทรสาคร','สมุทรสารคร':'สมุทรสาคร','สมุทราปราการ':'สมุทรปราการ',
                                         'สมุทราสาคร':'สมุทรสาคร','สมุทสงคราม':'สมุทรสงคราม','สมุทสาคร':'สมุทรสาคร','สมุย':'สุราษฎร์ธานี','สมุุทรปราการ':'สมุทรปราการ','สมุุทรสงคราม':'สมุทรสงคราม','สมุุทรสาคร':'สมุทรสาคร',
                                         'สระก้ว':'สระแก้ว','สระบุรี\xa0':'สระบุรี','สรินทร์':'สุรินทร์','สวิสเซอร์แลนด์':'ไม่มีข้อมูล','สอง':'แพร่','สองแคว':'น่าน','สะพานสูง':'กรุงเทพมหานคร',
                                         'สะแก้ว':'สระแก้ว','สัตหีบ':'ชลบุรี','สัมผัสผู้ป่วยยืนยัน COVID20':'ไม่มีข้อมูล','สามุทรสาคร':'สมุทรสาคร','สารคาม':'มหาสารคาม','สารภี':'เชียงใหม่','สิงห์บุรี\xa0':'สิงห์บุรี',
                                         'สุทรปราการ':'สมุทรปราการ','สุพรรญบุรี':'สุพรรณบุรี','สุพรรณบุรั':'สุพรรณบุรี','สุพรรณบุรี\xa0':'สุพรรณบุรี','สุมทรปราการ':'สมุทรปราการ',
                                         'สุมทรสาคร':'สมุทรสาคร','สุมุทรปราการ':'สมุทรปราการ','สุมุทรสาคร':'สมุทรสาคร','สุระบุรี':'สระบุรี','สุราษ':'สุราษฎร์ธานี','สุราษฎณ์ธานี':'สุราษฎร์ธานี','สุราษฎธานี':'สุราษฎร์ธานี',
                                         'สุราษฎร์':'สุราษฎร์ธานี','สุราษฎร์ฯ':'สุราษฎร์ธานี','สุราษฎร์์ธานี':'สุราษฎร์ธานี','สุราษฎ์ธานี':'สุราษฎร์ธานี','สุราษฏร์ธานี':'สุราษฎร์ธานี','สุราษธานี':'สุราษฎร์ธานี',
                                         'สุราษร์ฎธานี':'สุราษฎร์ธานี','สุราษร์ธานี':'สุราษฎร์ธานี','สุราษฯ':'สุราษฎร์ธานี','สุรินทรื':'สุรินทร์','สุรินทร์ 32150':'สุรินทร์','สุรินทร์,รีสะเกษ':'สุรินทร์','สุรินทร์\xa0':'สุรินทร์','สุริมทร์':'สุรินทร์',
                                         'สุริะแก้ว':'สระแก้ว','สุวรรณภูมิ':'สมุทรปราการ','สุุพรรณบุรี':'สุพรรณบุรี','สุุราษฎร์ธานี':'สุราษฎร์ธานี','สุุราษฏร์ธานี':'สุราษฎร์ธนี','สุุราษฯ':'สุราษฎร์ธนี','สุุรินทร์':'สุรินทร์',
                                         'สุุุโขทัย':'สุโขทัย','สุโขทับ':'สุโขทัย','สุโขทัย\xa0':'สุโขทัย','สูงเม่น':'แพร่','หนวงบัวลำภู':'หนองบัวลำภู','หนองงคาย':'หนองคาย','หนองบัวภู':'หนองบัวลำภู',
                                         'หนองบัวลำพูน':'หนองบัวลำภู','หนองบัวลําภู':'หนองบัวลำภู','หนองบััวลำภู':'หนองบัวลำภู','หนองม่วงไข่':'แพร่','หนอบัวลำภู':'หนองบัวลำภู','หลายจังหวัด':'ไม่มีข้อมูล','หัวหิน':'ประจวบคีรีขันธ์',
                                         'ห้วยขวาง':'กรุงเทพมหานคร','อยุทธยา':'พระนครศรีอยุธยา','อยุธยา':'พระนครศรีอยุธยา','อยุุธยา':'พระนครศรีอยุธยา','อำนาจเจิญ':'อำนาจเจริญ','อำนาญเจริญ':'อำนาจเจริญ','อำนาเจริญ':'อำนาจเจริญ',
                                         'อิสราเอล':'ไม่มีข้อมูล','อุดธานี':'อุดรธานี','อุดร':'อุดรธานี','อุดรธาณี':'อุดรธานี','อุดรธานี\xa0':'อุดรธานี','อุดรธานีี':'อุดรธานี','อุดรราชธานี':'อุดรธานี','อุตรดิตถ์\xa0':'อุตรดิตถ์',
                                         'อุตรดิตถ์์':'อุตรดิตถ์','อุตรดิษถ์':'อุตรดิตถ์','อุตรดิิตถ์':'อุตรดิตถ์','อุตรติดถ์':'อุตรดิตถ์','อุบลราขธานี':'อุบลราชธานี','อุบลราชธานี\xa0':'อุบลราชธานี','อุุครดิตถ์':'อุตรดิตถ์',
                                         'อุุดรธาน':'อุดรธานี','อุุดรธานี':'อุดรธานี','อุุตรดิตถ์':'อุตรดิตถ์','อุุทัยธานี':'อุทัยธานี','อุุบลราชธานี':'อุบลราชธานี','อ่งทอง':'อ่างทอง','อ่างทอง\xa0':'อ่างทอง','อํานาจเจริญ':'อำนาจเจริญ',
                                         'เชิงเทรา':'ฉะเชิงเทรา','เชียรใหญ่':'นครศรีธรรมราช','เชีียงราย':'เชียงราย','เชีียงใหม่':'เชียงใหม่','เด่นชัย':'แพร่',
                                         'เพขรบุรี':'เพชรบูรณ์','เพขรบูรณื':'เพชรบูรณ์','เพขรบูรณ์':'เพชรบูรณ์','เพชรบุรณ์':'เพชรบูรณ์','เพชรบุรี':'เพชรบูรณ์','เพชรบุรึ':'เพชรบูรณ์','เพชรบุุรี':'เพชรบูรณ์','เพชรบุูรณ์':'เพชรบูรณ์','เพชรบูรณ์\xa0':'เพชรบูรณ์',
                                         'เพชรบูร์':'เพชรบูรณ์','เพชรบููรณ์':'เพชรบูรณ์','เมือง':'แพร่','เมืองตาก':'ตาก','เมืองน่าน':'น่าน','เมืองปัตตานี':'ปัตตานี','เรือ':'เลย','เลย\xa0':'เลย','เวียงจันทร์':'ไม่มีข้อมูล','เวียงสา':'น่าน','แม่ทะ':'ลำปาง',
                                         'แล้วป่วย':'ไม่มีข้อมูล','โพธิ์ทอง':'อ่างทอง','ไชโย':'อ่างทอง','ไม่มีข้อมูล':'ไม่มีข้อมูล','ไม่มีชื่อหอพัก':'ไม่มีข้อมูล','ไม่ระบุ':'ไม่มีข้อมูล','สมุทรปรากา':'สมุทรปราการ'}, inplace=True)# แก้ไขข้อมูลที่พิมพ์จังหวัดผิด ให้อยู่ในชื่อจังหวัดที่ถูกต้อง

/usr/local/lib/python3.7/dist-packages/pandas/core/generic.py:6619: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return self._update_inplace(result)

In [143]:
data_02['province_of_onset'].replace({'USA':'ไม่มีข้อมูล','\tประจวบคีรีขันธ์':'ประจวบคีรีขันธ์','\xa0กาญจนบุรี':'กาญจนบุรี','\xa0ชลบุรี':'ชลบุรี','\xa0ตราด':'ตราด','\xa0นครปฐม':'นครปฐม',
                                         '\xa0สมุทรสงคราม':'สมุทรสงคราม','\xa0สมุทรสาคร':'สมุทรสาคร','\xa0อุทัยธานี':'อุทัยธานี','กทม':'กรุงเทพมหานคร','กทม.':'กรุงเทพมหานคร','กบินทร์บุรี':'ปราจีนบุรี','กระบี่ี่':'กระบี่','กรุงเทพ':'กรุงเทพมหานคร',
                                         'กรุงเทพมหานคร.':'กรุงเทพมหานคร','กรุงเทพมหานคร. / พระนครศรีอยุธยา':'กรุงเทพมหานคร','กรุงเทพมหานคร. / ศรีสะเกษ':'กรุงเทพมหานคร','กรุงเทพฯ':'กรุงเทพมหานคร','กะทู้':'ภูเก็ต',
                                         'กัมพูชา':'ไม่มีข้อมูล','กาญจบุรี':'กาญจนบุรี','กาญนบุรี':'กาญจนบุรี','กาฬสิน':'กาฬสินธุ์','กาฬสินธิ์':'กาฬสินธุ์','กาฬสินธุ์\xa0':'กาฬสินธุ์','กาฬสินธ์':'กาฬสินธุ์',
                                         'กำเพงเพชร':'กำแพงเพชร','กำแพง':'กำแพงเพชร','กำแพงเพชร':'กำแพงเพชร','กำแพงเพชร\xa0':'กำแพงเพชร','กําแพงเพชร':'กำแพงเพชร',
                                         'ขอนแก่น\xa0':'ขอนแก่น','ขอนแก่่น':'ขอนแก่น','ขานุวรลักษณ์บุรี':'กำแพงเพชร','คนไทยเดินทางกลับจากต่างประเทศ':'ไม่มีข้อมูล','คลองเตย':'กรุงเทพมหานคร','จ.กรุงเทพมหานคร':'กรุงเทพมหานคร',
                                         'จ.ภูเก็ต':'ภูเก็ต','จ.ราชบุรี':'ราชบุรี','จ.สุราษฎร์ธานี':'สุราษฎร์ธานี','จังหวัดสมุทรสาคร':'สมุทรสาคร','ฉะเชองเทราร':'ฉะเชิงเทรา','ชมพร':'ชุมพร',
                                         'ชลบุรี\t':'ชลบุรี','ชลบุรี\xa0':'ชลบุรี','ชลบุุรี':'ชลบุรี','ชอนแก่น':'ขอนแก่น','ชัยนาถ':'ชัยนาท','ชัยบาดาล':'ลพบุรี','ชัยภูมิ\xa0':'ชัยภูมิ','ชุุมพร':'ชุมพร','ชุุุมพร':'ชุมพร',
                                         'ดอนมดแดง':'อุบลราชธานี','ดินแดง':'กรุงเทพมหานคร','ตรััง':'ตรัง','ตราด\xa0':'ตราด','ตากใบ':'นราธิวาส','ต่างจังหวัด':'ไม่มีข้อมูล','ทุ่งเสลี่ยม':'สุโขทัย',
                                         'ท้ายบ้าน':'สมุทรปราการ','ธารโต':'ยะลา','นคนปฐม':'นครปฐม','นคปฐม':'นครปฐม','นครนปฐม':'นครปฐม','นครนาชสีมา':'นครราชสีมา','นครปฐม\xa0':'นครปฐม',
                                         'นครปบม':'นครปฐม','นครพนม\xa0':'นครพนม','นครยายก':'นครนายก','นครราขสีมา':'นครราชสีมา','นครราชธานี':'นครราชสีมา','นครราชศรีมา':'นครราชสีมา','นครราชสสีมา':'นครราชสีมา',
                                         'นครราชสีมา ลพบุรี':'นครราชสีมา','นครราชสีมา\xa0':'นครราชสีมา','นครศรธรรมราช':'นครศรีธรรมราช','นครศรี':'นครศรีธรรมราช','นครศรีธรมมราช':'นครศรีธรรมราช',
                                         'นครศรีธรมราช':'นครศรีธรรมราช','นครศรีธรรมราข':'นครศรีธรรมราช','นครศรีฯ':'นครศรีธรรมราช','นครศรีีธรรมราช':'นครศรีธรรมราช','นครศร๊ธรรมราช':'นครศรีธรรมราช',
                                         'นครศร๊ะรรมราช':'นครศรีธรรมราช','นครสรรค์':'นครสวรรค์','นครสรีธรรมราช':'นครศรีธรรมราช','นครสวรรค':'นครสวรรค์','นครสวรรค์\xa0':'นครสวรรค์','นครสีธรรมราช':'นครศรีธรรมราช',
                                         'นครฯ':'นครศรีธรรมราช','นคราชสีมา':'นครราชสีมา','นครีศรีธรรมราช':'นครศรีธรรมราช','นตรนายก':'นครนายก','นตรปฐม':'นครปฐม','นนทบุรี\xa0':'นนทบุรี',
                                         'นนทบุุรี':'นนทบุรี','นนทุบรี':'นนทบุรี','นนทุรี':'นนทบุรี','นนมบุรี':'นนทบุรี','นรศรีธรรมราช':'นครศรีธรรมราช','นราธิวาส\u200b':'นราธิวาส','นราธฺวาส':'นราธิวาส','นอกเขต':'ไม่มีข้อมูล',
                                         'นาราธิวาส':'นราธิวาส','นาวัง':'หนองบัวลำภู','น่าน/ฉะเชิงเทรา':'น่าน','บางกรวย':'นนทบุรี','บางกะปิ':'กรุงเทพมหานคร','บางนา':'กรุงเทพมหานคร','บางปะอิน':'กรุงเทพมหานคร',
                                         'บางละมุง':'ชลบุรี','บางศรีเมือง':'นนทบุรี','บางเพียง':'สมุทรปราการ','บึงโขงหลง':'บึงกาฬ','บุรีรัมภ์':'บุรีรัมย์','บุรีรัมย์\xa0':'บุรีรัมย์','บุรีรัยม์':'บุรีรัมย์','บุรีรีมย์':'บุรีรัมย์',
                                         'บ้านหลวง':'น่าน','ปจ':'ไม่มีข้อมูล','ปทึมธานี':'ปทุมธานี','ปทุทธานี':'ปทุมธานี','ปทุมฑานี':'ปทุมธานี','ปทุมทานี':'ปทุมธานี','ปทุมธาน':'ปทุมธานี','ปทุมธานี\xa0':'ปทุมธานี','ปทุมาธานี':'ปทุมธานี',
                                         'ปธุมธานี':'ปทุมธานี','ปทุมธานี.':'ปทุมธานี','ปทุมธานีี':'ปทุมธานี','ปทุุมธานี':'ปทุมธานี','ปมุมธานี':'ปทุมธานี',
                                         'ประจวนคีรีขันธ็':'ประจวบคีรีขันธ์','ประจวบ':'ประจวบคีรีขันธ์','ประจวบคิรีขันธ์':'ประจวบคีรีขันธ์','ประจวบคีรขันธ์':'ประจวบคีรีขันธ์','ประจวบคีรขัันธ์':'ประจวบคีรีขันธ์','ประจวบคีรีขัน':'ประจวบคีรีขันธ์',
                                         'ประจวบคีรีขันธื':'ประจวบคีรีขันธ์','ประจวบคีรีขันธฺ':'ประจวบคีรีขันธ์','ประจวบคีรีขันธ์\xa0':'ประจวบคีรีขันธ์','ประจวบคีรีขันธ์์':'ประจวบคีรีขันธ์','ประจวบคีรีขัันธ์':'ประจวบคีรีขันธ์','ประจวบคีีรีขันธ์':'ประจวบคีรีขันธ์',
                                         'ประจวบฯ':'ประจวบคีรีขันธ์','ประทุมธานี':'ปทุมธานี', 'ประเทศกัมพูชา':'ไม่มีข้อมูล','ปราจีบุรี':'ปราจีนบุรี','ปลวกแดง':'ระยอง','ปลายพระยา':'กระบี่', 'ปอยเปต':'ไม่มีข้อมูล','ปัตตนรี':'ปัตตานี',
                                         'ปัตตานนี':'ปัตตานี','ปัตตานีี':'ปัตตานี','ปัว':'น่าน','ปััตตานี':'ปัตตานี','ปุทมธานี':'ปทุมธานี','ป่าโมก':'อ่างทอง','พม่า':'ไม่มีข้อมูล','พรหมพิราม':'พิษณุโลก','พระนครศรียุธยา':'พระนครศรีอยุธยา',
                                         'พระนครศรีอยุทธยา':'พระนครศรีอยุธยา','พระนครศรีอยุทยา':'พระนครศรีอยุธยา','พระนครศรีอยุธยา\xa0':'พระนครศรีอยุธยา','พัทยา':'ชลบุรี','พัทลุุง':'พัทลุง','พัังงา':'พังงา',
                                         'พิษณุโลก\xa0':'พิษณุโลก','พิษณูโลก':'พิษณุโลก','ฟินแลนด์':'ไม่มีข้อมูล','ภาษีเจริญ':'กรุงเทพมหานคร','ภุเก็ต':'ภูเก็ต','ภูุเก็ต':'ภูเก็ต','ภููเก็ต':'ภูเก็ต','ภูเก็็ต':'ภูเก็ต','ภูเพียง':'น่าน',
                                         'มหาสาคาม':'มหาสารคาม','มาเลเซีย':'ไม่มีข้อมูล','มุกาดหาร':'มุกดาหาร','ยานนาวา':'กรุงเทพมหานคร','ร.จ.จ.นราธิวาส':'นราธิวาส','รอ':'ร้อยเอ็ด','ระบุ':'ไม่มีข้อมูล','ระยอง\xa0':'ระยอง',
                                         'ระอยง':'ระยอง','ราชบบุรี':'ราชบุรี','ราชบุรีี':'ราชบุรี','ราชบุรี\u200b':'ราชบุรี','ราชุรี':'ราชบุรี','ราชเทวี':'กรุงเทพมหานคร','ร้องกวาง':'แพร่','ลบุรี':'ลพบุรี','ลพบุรี.':'ลพบุรี','ลพบุรี\xa0':'ลพบุรี','ลอง':'แพร่',
                                         'ลาดกระบัง':'กรุงเทพมหานคร','ลาดพร้าว':'กรุงเทพมหานคร','ลาว':'ไม่มีข้อมูล','ลำพูน\u200b':'ลำพูน','ลำพููน':'ลำพูน','ลำลูกกา':'ปทุมธานี','วังชิ้น':'ลำปาง','วังทอง':'พิษณุโลก',
                                         'วิเศษชัยชาญ':'อ่างทอง','ศรีษะสะเกษ':'ศรีสะเกษ','ศรีษะเกษ':'ศรีสะเกษ','ศรีสระเกษ':'ศรีสะเกษ','ศีรสะเกษ':'ศรีสะเกษ','สครสวรรค์':'นครสวรรค์',
                                         'สงขลา\u200b':'สงขลา','สถานที่ทำงาน':'ไม่มีข้อมูล','สพรรณบุรี':'สุพรรณบุรี','สมถทรปราการ':'สมุทรปราการ','สมทรสงคราม':'สมุทรสงคราม','สมทรสาคร':'สมุทรสาคร','สมุครปราการ':'สมุทรปราการ',
                                         'สมุครสาคร':'สมุทรสาคร','สมุท':'ไม่มีข้อมูล','สมุทปราการ':'สมุทรปราการ','สมุทรปรากร':'สมุทรปราการ','สมุทรปรากรร':'สมุทรปราการ','สมุทรปราการ\xa0':'สมุทรปราการ','สมุทรศาคร':'สมุทรสาคร',
                                         'สมุทรสาคร\xa0':'สมุทรสาคร','สมุทรสาคา':'สมุทรสาคร','สมุทรสาคาร':'สมุทรสาคร','สมุทรสาทร':'สมุทรสาคร','สมุทรสารคร':'สมุทรสาคร','สมุทราปราการ':'สมุทรปราการ',
                                         'สมุทราสาคร':'สมุทรสาคร','สมุทสงคราม':'สมุทรสงคราม','สมุทสาคร':'สมุทรสาคร','สมุย':'สุราษฎร์ธานี','สมุุทรปราการ':'สมุทรปราการ','สมุุทรสงคราม':'สมุทรสงคราม','สมุุทรสาคร':'สมุทรสาคร',
                                         'สระก้ว':'สระแก้ว','สระบุรี\xa0':'สระบุรี','สรินทร์':'สุรินทร์','สวิสเซอร์แลนด์':'ไม่มีข้อมูล','สอง':'แพร่','สองแคว':'น่าน','สะพานสูง':'กรุงเทพมหานคร',
                                         'สะแก้ว':'สระแก้ว','สัตหีบ':'ชลบุรี','สัมผัสผู้ป่วยยืนยัน COVID20':'ไม่มีข้อมูล','สามุทรสาคร':'สมุทรสาคร','สารคาม':'มหาสารคาม','สารภี':'เชียงใหม่','สิงห์บุรี\xa0':'สิงห์บุรี',
                                         'สุทรปราการ':'สมุทรปราการ','สุพรรญบุรี':'สุพรรณบุรี','สุพรรณบุรั':'สุพรรณบุรี','สุพรรณบุรี\xa0':'สุพรรณบุรี','สุมทรปราการ':'สมุทรปราการ',
                                         'สุมทรสาคร':'สมุทรสาคร','สุมุทรปราการ':'สมุทรปราการ','สุมุทรสาคร':'สมุทรสาคร','สุระบุรี':'สระบุรี','สุราษ':'สุราษฎร์ธานี','สุราษฎณ์ธานี':'สุราษฎร์ธานี','สุราษฎธานี':'สุราษฎร์ธานี',
                                         'สุราษฎร์':'สุราษฎร์ธานี','สุราษฎร์ฯ':'สุราษฎร์ธานี','สุราษฎร์์ธานี':'สุราษฎร์ธานี','สุราษฎ์ธานี':'สุราษฎร์ธานี','สุราษฏร์ธานี':'สุราษฎร์ธานี','สุราษธานี':'สุราษฎร์ธานี',
                                         'สุราษร์ฎธานี':'สุราษฎร์ธานี','สุราษร์ธานี':'สุราษฎร์ธานี','สุราษฯ':'สุราษฎร์ธานี','สุรินทรื':'สุรินทร์','สุรินทร์ 32150':'สุรินทร์','สุรินทร์,รีสะเกษ':'สุรินทร์','สุรินทร์\xa0':'สุรินทร์','สุริมทร์':'สุรินทร์',
                                         'สุริะแก้ว':'สระแก้ว','สุวรรณภูมิ':'สมุทรปราการ','สุุพรรณบุรี':'สุพรรณบุรี','สุุราษฎร์ธานี':'สุราษฎร์ธานี','สุุราษฏร์ธานี':'สุราษฎร์ธนี','สุุราษฯ':'สุราษฎร์ธนี','สุุรินทร์':'สุรินทร์',
                                         'สุุุโขทัย':'สุโขทัย','สุโขทับ':'สุโขทัย','สุโขทัย\xa0':'สุโขทัย','สูงเม่น':'แพร่','หนวงบัวลำภู':'หนองบัวลำภู','หนองงคาย':'หนองคาย','หนองบัวภู':'หนองบัวลำภู',
                                         'หนองบัวลำพูน':'หนองบัวลำภู','หนองบัวลําภู':'หนองบัวลำภู','หนองบััวลำภู':'หนองบัวลำภู','หนองม่วงไข่':'แพร่','หนอบัวลำภู':'หนองบัวลำภู','หลายจังหวัด':'ไม่มีข้อมูล','หัวหิน':'ประจวบคีรีขันธ์',
                                         'ห้วยขวาง':'กรุงเทพมหานคร','อยุทธยา':'พระนครศรีอยุธยา','อยุธยา':'พระนครศรีอยุธยา','อยุุธยา':'พระนครศรีอยุธยา','อำนาจเจิญ':'อำนาจเจริญ','อำนาญเจริญ':'อำนาจเจริญ','อำนาเจริญ':'อำนาจเจริญ',
                                         'อิสราเอล':'ไม่มีข้อมูล','อุดธานี':'อุดรธานี','อุดร':'อุดรธานี','อุดรธาณี':'อุดรธานี','อุดรธานี\xa0':'อุดรธานี','อุดรธานีี':'อุดรธานี','อุดรราชธานี':'อุดรธานี','อุตรดิตถ์\xa0':'อุตรดิตถ์',
                                         'อุตรดิตถ์์':'อุตรดิตถ์','อุตรดิษถ์':'อุตรดิตถ์','อุตรดิิตถ์':'อุตรดิตถ์','อุตรติดถ์':'อุตรดิตถ์','อุบลราขธานี':'อุบลราชธานี','อุบลราชธานี\xa0':'อุบลราชธานี','อุุครดิตถ์':'อุตรดิตถ์',
                                         'อุุดรธาน':'อุดรธานี','อุุดรธานี':'อุดรธานี','อุุตรดิตถ์':'อุตรดิตถ์','อุุทัยธานี':'อุทัยธานี','อุุบลราชธานี':'อุบลราชธานี','อ่งทอง':'อ่างทอง','อ่างทอง\xa0':'อ่างทอง','อํานาจเจริญ':'อำนาจเจริญ',
                                         'เชิงเทรา':'ฉะเชิงเทรา','เชียรใหญ่':'นครศรีธรรมราช','เชีียงราย':'เชียงราย','เชีียงใหม่':'เชียงใหม่','เด่นชัย':'แพร่',
                                         'เพขรบุรี':'เพชรบูรณ์','เพขรบูรณื':'เพชรบูรณ์','เพขรบูรณ์':'เพชรบูรณ์','เพชรบุรณ์':'เพชรบูรณ์','เพชรบุรี':'เพชรบูรณ์','เพชรบุรึ':'เพชรบูรณ์','เพชรบุุรี':'เพชรบูรณ์','เพชรบุูรณ์':'เพชรบูรณ์','เพชรบูรณ์\xa0':'เพชรบูรณ์',
                                         'เพชรบูร์':'เพชรบูรณ์','เพชรบููรณ์':'เพชรบูรณ์','เมือง':'แพร่','เมืองตาก':'ตาก','เมืองน่าน':'น่าน','เมืองปัตตานี':'ปัตตานี','เรือ':'เลย','เลย\xa0':'เลย','เวียงจันทร์':'ไม่มีข้อมูล','เวียงสา':'น่าน','แม่ทะ':'ลำปาง',
                                         'แล้วป่วย':'ไม่มีข้อมูล','โพธิ์ทอง':'อ่างทอง','ไชโย':'อ่างทอง','ไม่มีข้อมูล':'ไม่มีข้อมูล','ไม่มีชื่อหอพัก':'ไม่มีข้อมูล','ไม่ระบุ':'ไม่มีข้อมูล','สมุทรปรากา':'สมุทรปราการ'}, inplace=True)# แก้ไขข้อมูลที่พิมพ์จังหวัดผิด ให้อยู่ในชื่อจังหวัดที่ถูกต้อง

/usr/local/lib/python3.7/dist-packages/pandas/core/generic.py:6619: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return self._update_inplace(result)

In [144]:
data_03['province_of_onset'].replace({'USA':'ไม่มีข้อมูล','\tประจวบคีรีขันธ์':'ประจวบคีรีขันธ์','\xa0กาญจนบุรี':'กาญจนบุรี','\xa0ชลบุรี':'ชลบุรี','\xa0ตราด':'ตราด','\xa0นครปฐม':'นครปฐม',
                                         '\xa0สมุทรสงคราม':'สมุทรสงคราม','\xa0สมุทรสาคร':'สมุทรสาคร','\xa0อุทัยธานี':'อุทัยธานี','กทม':'กรุงเทพมหานคร','กทม.':'กรุงเทพมหานคร','กบินทร์บุรี':'ปราจีนบุรี','กระบี่ี่':'กระบี่','กรุงเทพ':'กรุงเทพมหานคร',
                                         'กรุงเทพมหานคร.':'กรุงเทพมหานคร','กรุงเทพมหานคร. / พระนครศรีอยุธยา':'กรุงเทพมหานคร','กรุงเทพมหานคร. / ศรีสะเกษ':'กรุงเทพมหานคร','กรุงเทพฯ':'กรุงเทพมหานคร','กะทู้':'ภูเก็ต',
                                         'กัมพูชา':'ไม่มีข้อมูล','กาญจบุรี':'กาญจนบุรี','กาญนบุรี':'กาญจนบุรี','กาฬสิน':'กาฬสินธุ์','กาฬสินธิ์':'กาฬสินธุ์','กาฬสินธุ์\xa0':'กาฬสินธุ์','กาฬสินธ์':'กาฬสินธุ์',
                                         'กำเพงเพชร':'กำแพงเพชร','กำแพง':'กำแพงเพชร','กำแพงเพชร':'กำแพงเพชร','กำแพงเพชร\xa0':'กำแพงเพชร','กําแพงเพชร':'กำแพงเพชร',
                                         'ขอนแก่น\xa0':'ขอนแก่น','ขอนแก่่น':'ขอนแก่น','ขานุวรลักษณ์บุรี':'กำแพงเพชร','คนไทยเดินทางกลับจากต่างประเทศ':'ไม่มีข้อมูล','คลองเตย':'กรุงเทพมหานคร','จ.กรุงเทพมหานคร':'กรุงเทพมหานคร',
                                         'จ.ภูเก็ต':'ภูเก็ต','จ.ราชบุรี':'ราชบุรี','จ.สุราษฎร์ธานี':'สุราษฎร์ธานี','จังหวัดสมุทรสาคร':'สมุทรสาคร','ฉะเชองเทราร':'ฉะเชิงเทรา','ชมพร':'ชุมพร',
                                         'ชลบุรี\t':'ชลบุรี','ชลบุรี\xa0':'ชลบุรี','ชลบุุรี':'ชลบุรี','ชอนแก่น':'ขอนแก่น','ชัยนาถ':'ชัยนาท','ชัยบาดาล':'ลพบุรี','ชัยภูมิ\xa0':'ชัยภูมิ','ชุุมพร':'ชุมพร','ชุุุมพร':'ชุมพร',
                                         'ดอนมดแดง':'อุบลราชธานี','ดินแดง':'กรุงเทพมหานคร','ตรััง':'ตรัง','ตราด\xa0':'ตราด','ตากใบ':'นราธิวาส','ต่างจังหวัด':'ไม่มีข้อมูล','ทุ่งเสลี่ยม':'สุโขทัย',
                                         'ท้ายบ้าน':'สมุทรปราการ','ธารโต':'ยะลา','นคนปฐม':'นครปฐม','นคปฐม':'นครปฐม','นครนปฐม':'นครปฐม','นครนาชสีมา':'นครราชสีมา','นครปฐม\xa0':'นครปฐม',
                                         'นครปบม':'นครปฐม','นครพนม\xa0':'นครพนม','นครยายก':'นครนายก','นครราขสีมา':'นครราชสีมา','นครราชธานี':'นครราชสีมา','นครราชศรีมา':'นครราชสีมา','นครราชสสีมา':'นครราชสีมา',
                                         'นครราชสีมา ลพบุรี':'นครราชสีมา','นครราชสีมา\xa0':'นครราชสีมา','นครศรธรรมราช':'นครศรีธรรมราช','นครศรี':'นครศรีธรรมราช','นครศรีธรมมราช':'นครศรีธรรมราช',
                                         'นครศรีธรมราช':'นครศรีธรรมราช','นครศรีธรรมราข':'นครศรีธรรมราช','นครศรีฯ':'นครศรีธรรมราช','นครศรีีธรรมราช':'นครศรีธรรมราช','นครศร๊ธรรมราช':'นครศรีธรรมราช',
                                         'นครศร๊ะรรมราช':'นครศรีธรรมราช','นครสรรค์':'นครสวรรค์','นครสรีธรรมราช':'นครศรีธรรมราช','นครสวรรค':'นครสวรรค์','นครสวรรค์\xa0':'นครสวรรค์','นครสีธรรมราช':'นครศรีธรรมราช',
                                         'นครฯ':'นครศรีธรรมราช','นคราชสีมา':'นครราชสีมา','นครีศรีธรรมราช':'นครศรีธรรมราช','นตรนายก':'นครนายก','นตรปฐม':'นครปฐม','นนทบุรี\xa0':'นนทบุรี',
                                         'นนทบุุรี':'นนทบุรี','นนทุบรี':'นนทบุรี','นนทุรี':'นนทบุรี','นนมบุรี':'นนทบุรี','นรศรีธรรมราช':'นครศรีธรรมราช','นราธิวาส\u200b':'นราธิวาส','นราธฺวาส':'นราธิวาส','นอกเขต':'ไม่มีข้อมูล',
                                         'นาราธิวาส':'นราธิวาส','นาวัง':'หนองบัวลำภู','น่าน/ฉะเชิงเทรา':'น่าน','บางกรวย':'นนทบุรี','บางกะปิ':'กรุงเทพมหานคร','บางนา':'กรุงเทพมหานคร','บางปะอิน':'กรุงเทพมหานคร',
                                         'บางละมุง':'ชลบุรี','บางศรีเมือง':'นนทบุรี','บางเพียง':'สมุทรปราการ','บึงโขงหลง':'บึงกาฬ','บุรีรัมภ์':'บุรีรัมย์','บุรีรัมย์\xa0':'บุรีรัมย์','บุรีรัยม์':'บุรีรัมย์','บุรีรีมย์':'บุรีรัมย์',
                                         'บ้านหลวง':'น่าน','ปจ':'ไม่มีข้อมูล','ปทึมธานี':'ปทุมธานี','ปทุทธานี':'ปทุมธานี','ปทุมฑานี':'ปทุมธานี','ปทุมทานี':'ปทุมธานี','ปทุมธาน':'ปทุมธานี','ปทุมธานี\xa0':'ปทุมธานี','ปทุมาธานี':'ปทุมธานี',
                                         'ปธุมธานี':'ปทุมธานี','ปทุมธานี.':'ปทุมธานี','ปทุมธานีี':'ปทุมธานี','ปทุุมธานี':'ปทุมธานี','ปมุมธานี':'ปทุมธานี',
                                         'ประจวนคีรีขันธ็':'ประจวบคีรีขันธ์','ประจวบ':'ประจวบคีรีขันธ์','ประจวบคิรีขันธ์':'ประจวบคีรีขันธ์','ประจวบคีรขันธ์':'ประจวบคีรีขันธ์','ประจวบคีรขัันธ์':'ประจวบคีรีขันธ์','ประจวบคีรีขัน':'ประจวบคีรีขันธ์',
                                         'ประจวบคีรีขันธื':'ประจวบคีรีขันธ์','ประจวบคีรีขันธฺ':'ประจวบคีรีขันธ์','ประจวบคีรีขันธ์\xa0':'ประจวบคีรีขันธ์','ประจวบคีรีขันธ์์':'ประจวบคีรีขันธ์','ประจวบคีรีขัันธ์':'ประจวบคีรีขันธ์','ประจวบคีีรีขันธ์':'ประจวบคีรีขันธ์',
                                         'ประจวบฯ':'ประจวบคีรีขันธ์','ประทุมธานี':'ปทุมธานี', 'ประเทศกัมพูชา':'ไม่มีข้อมูล','ปราจีบุรี':'ปราจีนบุรี','ปลวกแดง':'ระยอง','ปลายพระยา':'กระบี่', 'ปอยเปต':'ไม่มีข้อมูล','ปัตตนรี':'ปัตตานี',
                                         'ปัตตานนี':'ปัตตานี','ปัตตานีี':'ปัตตานี','ปัว':'น่าน','ปััตตานี':'ปัตตานี','ปุทมธานี':'ปทุมธานี','ป่าโมก':'อ่างทอง','พม่า':'ไม่มีข้อมูล','พรหมพิราม':'พิษณุโลก','พระนครศรียุธยา':'พระนครศรีอยุธยา',
                                         'พระนครศรีอยุทธยา':'พระนครศรีอยุธยา','พระนครศรีอยุทยา':'พระนครศรีอยุธยา','พระนครศรีอยุธยา\xa0':'พระนครศรีอยุธยา','พัทยา':'ชลบุรี','พัทลุุง':'พัทลุง','พัังงา':'พังงา',
                                         'พิษณุโลก\xa0':'พิษณุโลก','พิษณูโลก':'พิษณุโลก','ฟินแลนด์':'ไม่มีข้อมูล','ภาษีเจริญ':'กรุงเทพมหานคร','ภุเก็ต':'ภูเก็ต','ภูุเก็ต':'ภูเก็ต','ภููเก็ต':'ภูเก็ต','ภูเก็็ต':'ภูเก็ต','ภูเพียง':'น่าน',
                                         'มหาสาคาม':'มหาสารคาม','มาเลเซีย':'ไม่มีข้อมูล','มุกาดหาร':'มุกดาหาร','ยานนาวา':'กรุงเทพมหานคร','ร.จ.จ.นราธิวาส':'นราธิวาส','รอ':'ร้อยเอ็ด','ระบุ':'ไม่มีข้อมูล','ระยอง\xa0':'ระยอง',
                                         'ระอยง':'ระยอง','ราชบบุรี':'ราชบุรี','ราชบุรีี':'ราชบุรี','ราชบุรี\u200b':'ราชบุรี','ราชุรี':'ราชบุรี','ราชเทวี':'กรุงเทพมหานคร','ร้องกวาง':'แพร่','ลบุรี':'ลพบุรี','ลพบุรี.':'ลพบุรี','ลพบุรี\xa0':'ลพบุรี','ลอง':'แพร่',
                                         'ลาดกระบัง':'กรุงเทพมหานคร','ลาดพร้าว':'กรุงเทพมหานคร','ลาว':'ไม่มีข้อมูล','ลำพูน\u200b':'ลำพูน','ลำพููน':'ลำพูน','ลำลูกกา':'ปทุมธานี','วังชิ้น':'ลำปาง','วังทอง':'พิษณุโลก',
                                         'วิเศษชัยชาญ':'อ่างทอง','ศรีษะสะเกษ':'ศรีสะเกษ','ศรีษะเกษ':'ศรีสะเกษ','ศรีสระเกษ':'ศรีสะเกษ','ศีรสะเกษ':'ศรีสะเกษ','สครสวรรค์':'นครสวรรค์',
                                         'สงขลา\u200b':'สงขลา','สถานที่ทำงาน':'ไม่มีข้อมูล','สพรรณบุรี':'สุพรรณบุรี','สมถทรปราการ':'สมุทรปราการ','สมทรสงคราม':'สมุทรสงคราม','สมทรสาคร':'สมุทรสาคร','สมุครปราการ':'สมุทรปราการ',
                                         'สมุครสาคร':'สมุทรสาคร','สมุท':'ไม่มีข้อมูล','สมุทปราการ':'สมุทรปราการ','สมุทรปรากร':'สมุทรปราการ','สมุทรปรากรร':'สมุทรปราการ','สมุทรปราการ\xa0':'สมุทรปราการ','สมุทรศาคร':'สมุทรสาคร',
                                         'สมุทรสาคร\xa0':'สมุทรสาคร','สมุทรสาคา':'สมุทรสาคร','สมุทรสาคาร':'สมุทรสาคร','สมุทรสาทร':'สมุทรสาคร','สมุทรสารคร':'สมุทรสาคร','สมุทราปราการ':'สมุทรปราการ',
                                         'สมุทราสาคร':'สมุทรสาคร','สมุทสงคราม':'สมุทรสงคราม','สมุทสาคร':'สมุทรสาคร','สมุย':'สุราษฎร์ธานี','สมุุทรปราการ':'สมุทรปราการ','สมุุทรสงคราม':'สมุทรสงคราม','สมุุทรสาคร':'สมุทรสาคร',
                                         'สระก้ว':'สระแก้ว','สระบุรี\xa0':'สระบุรี','สรินทร์':'สุรินทร์','สวิสเซอร์แลนด์':'ไม่มีข้อมูล','สอง':'แพร่','สองแคว':'น่าน','สะพานสูง':'กรุงเทพมหานคร',
                                         'สะแก้ว':'สระแก้ว','สัตหีบ':'ชลบุรี','สัมผัสผู้ป่วยยืนยัน COVID20':'ไม่มีข้อมูล','สามุทรสาคร':'สมุทรสาคร','สารคาม':'มหาสารคาม','สารภี':'เชียงใหม่','สิงห์บุรี\xa0':'สิงห์บุรี',
                                         'สุทรปราการ':'สมุทรปราการ','สุพรรญบุรี':'สุพรรณบุรี','สุพรรณบุรั':'สุพรรณบุรี','สุพรรณบุรี\xa0':'สุพรรณบุรี','สุมทรปราการ':'สมุทรปราการ',
                                         'สุมทรสาคร':'สมุทรสาคร','สุมุทรปราการ':'สมุทรปราการ','สุมุทรสาคร':'สมุทรสาคร','สุระบุรี':'สระบุรี','สุราษ':'สุราษฎร์ธานี','สุราษฎณ์ธานี':'สุราษฎร์ธานี','สุราษฎธานี':'สุราษฎร์ธานี',
                                         'สุราษฎร์':'สุราษฎร์ธานี','สุราษฎร์ฯ':'สุราษฎร์ธานี','สุราษฎร์์ธานี':'สุราษฎร์ธานี','สุราษฎ์ธานี':'สุราษฎร์ธานี','สุราษฏร์ธานี':'สุราษฎร์ธานี','สุราษธานี':'สุราษฎร์ธานี',
                                         'สุราษร์ฎธานี':'สุราษฎร์ธานี','สุราษร์ธานี':'สุราษฎร์ธานี','สุราษฯ':'สุราษฎร์ธานี','สุรินทรื':'สุรินทร์','สุรินทร์ 32150':'สุรินทร์','สุรินทร์,รีสะเกษ':'สุรินทร์','สุรินทร์\xa0':'สุรินทร์','สุริมทร์':'สุรินทร์',
                                         'สุริะแก้ว':'สระแก้ว','สุวรรณภูมิ':'สมุทรปราการ','สุุพรรณบุรี':'สุพรรณบุรี','สุุราษฎร์ธานี':'สุราษฎร์ธานี','สุุราษฏร์ธานี':'สุราษฎร์ธนี','สุุราษฯ':'สุราษฎร์ธนี','สุุรินทร์':'สุรินทร์',
                                         'สุุุโขทัย':'สุโขทัย','สุโขทับ':'สุโขทัย','สุโขทัย\xa0':'สุโขทัย','สูงเม่น':'แพร่','หนวงบัวลำภู':'หนองบัวลำภู','หนองงคาย':'หนองคาย','หนองบัวภู':'หนองบัวลำภู',
                                         'หนองบัวลำพูน':'หนองบัวลำภู','หนองบัวลําภู':'หนองบัวลำภู','หนองบััวลำภู':'หนองบัวลำภู','หนองม่วงไข่':'แพร่','หนอบัวลำภู':'หนองบัวลำภู','หลายจังหวัด':'ไม่มีข้อมูล','หัวหิน':'ประจวบคีรีขันธ์',
                                         'ห้วยขวาง':'กรุงเทพมหานคร','อยุทธยา':'พระนครศรีอยุธยา','อยุธยา':'พระนครศรีอยุธยา','อยุุธยา':'พระนครศรีอยุธยา','อำนาจเจิญ':'อำนาจเจริญ','อำนาญเจริญ':'อำนาจเจริญ','อำนาเจริญ':'อำนาจเจริญ',
                                         'อิสราเอล':'ไม่มีข้อมูล','อุดธานี':'อุดรธานี','อุดร':'อุดรธานี','อุดรธาณี':'อุดรธานี','อุดรธานี\xa0':'อุดรธานี','อุดรธานีี':'อุดรธานี','อุดรราชธานี':'อุดรธานี','อุตรดิตถ์\xa0':'อุตรดิตถ์',
                                         'อุตรดิตถ์์':'อุตรดิตถ์','อุตรดิษถ์':'อุตรดิตถ์','อุตรดิิตถ์':'อุตรดิตถ์','อุตรติดถ์':'อุตรดิตถ์','อุบลราขธานี':'อุบลราชธานี','อุบลราชธานี\xa0':'อุบลราชธานี','อุุครดิตถ์':'อุตรดิตถ์',
                                         'อุุดรธาน':'อุดรธานี','อุุดรธานี':'อุดรธานี','อุุตรดิตถ์':'อุตรดิตถ์','อุุทัยธานี':'อุทัยธานี','อุุบลราชธานี':'อุบลราชธานี','อ่งทอง':'อ่างทอง','อ่างทอง\xa0':'อ่างทอง','อํานาจเจริญ':'อำนาจเจริญ',
                                         'เชิงเทรา':'ฉะเชิงเทรา','เชียรใหญ่':'นครศรีธรรมราช','เชีียงราย':'เชียงราย','เชีียงใหม่':'เชียงใหม่','เด่นชัย':'แพร่',
                                         'เพขรบุรี':'เพชรบูรณ์','เพขรบูรณื':'เพชรบูรณ์','เพขรบูรณ์':'เพชรบูรณ์','เพชรบุรณ์':'เพชรบูรณ์','เพชรบุรี':'เพชรบูรณ์','เพชรบุรึ':'เพชรบูรณ์','เพชรบุุรี':'เพชรบูรณ์','เพชรบุูรณ์':'เพชรบูรณ์','เพชรบูรณ์\xa0':'เพชรบูรณ์',
                                         'เพชรบูร์':'เพชรบูรณ์','เพชรบููรณ์':'เพชรบูรณ์','เมือง':'แพร่','เมืองตาก':'ตาก','เมืองน่าน':'น่าน','เมืองปัตตานี':'ปัตตานี','เรือ':'เลย','เลย\xa0':'เลย','เวียงจันทร์':'ไม่มีข้อมูล','เวียงสา':'น่าน','แม่ทะ':'ลำปาง',
                                         'แล้วป่วย':'ไม่มีข้อมูล','โพธิ์ทอง':'อ่างทอง','ไชโย':'อ่างทอง','ไม่มีข้อมูล':'ไม่มีข้อมูล','ไม่มีชื่อหอพัก':'ไม่มีข้อมูล','ไม่ระบุ':'ไม่มีข้อมูล','สมุทรปรากา':'สมุทรปราการ'}, inplace=True)# แก้ไขข้อมูลที่พิมพ์จังหวัดผิด ให้อยู่ในชื่อจังหวัดที่ถูกต้อง

/usr/local/lib/python3.7/dist-packages/pandas/core/generic.py:6619: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return self._update_inplace(result)

In [145]:
data_04['province_of_onset'].replace({'USA':'ไม่มีข้อมูล','\tประจวบคีรีขันธ์':'ประจวบคีรีขันธ์','\xa0กาญจนบุรี':'กาญจนบุรี','\xa0ชลบุรี':'ชลบุรี','\xa0ตราด':'ตราด','\xa0นครปฐม':'นครปฐม',
                                         '\xa0สมุทรสงคราม':'สมุทรสงคราม','\xa0สมุทรสาคร':'สมุทรสาคร','\xa0อุทัยธานี':'อุทัยธานี','กทม':'กรุงเทพมหานคร','กทม.':'กรุงเทพมหานคร','กบินทร์บุรี':'ปราจีนบุรี','กระบี่ี่':'กระบี่','กรุงเทพ':'กรุงเทพมหานคร',
                                         'กรุงเทพมหานคร.':'กรุงเทพมหานคร','กรุงเทพมหานคร. / พระนครศรีอยุธยา':'กรุงเทพมหานคร','กรุงเทพมหานคร. / ศรีสะเกษ':'กรุงเทพมหานคร','กรุงเทพฯ':'กรุงเทพมหานคร','กะทู้':'ภูเก็ต',
                                         'กัมพูชา':'ไม่มีข้อมูล','กาญจบุรี':'กาญจนบุรี','กาญนบุรี':'กาญจนบุรี','กาฬสิน':'กาฬสินธุ์','กาฬสินธิ์':'กาฬสินธุ์','กาฬสินธุ์\xa0':'กาฬสินธุ์','กาฬสินธ์':'กาฬสินธุ์',
                                         'กำเพงเพชร':'กำแพงเพชร','กำแพง':'กำแพงเพชร','กำแพงเพชร':'กำแพงเพชร','กำแพงเพชร\xa0':'กำแพงเพชร','กําแพงเพชร':'กำแพงเพชร',
                                         'ขอนแก่น\xa0':'ขอนแก่น','ขอนแก่่น':'ขอนแก่น','ขานุวรลักษณ์บุรี':'กำแพงเพชร','คนไทยเดินทางกลับจากต่างประเทศ':'ไม่มีข้อมูล','คลองเตย':'กรุงเทพมหานคร','จ.กรุงเทพมหานคร':'กรุงเทพมหานคร',
                                         'จ.ภูเก็ต':'ภูเก็ต','จ.ราชบุรี':'ราชบุรี','จ.สุราษฎร์ธานี':'สุราษฎร์ธานี','จังหวัดสมุทรสาคร':'สมุทรสาคร','ฉะเชองเทราร':'ฉะเชิงเทรา','ชมพร':'ชุมพร',
                                         'ชลบุรี\t':'ชลบุรี','ชลบุรี\xa0':'ชลบุรี','ชลบุุรี':'ชลบุรี','ชอนแก่น':'ขอนแก่น','ชัยนาถ':'ชัยนาท','ชัยบาดาล':'ลพบุรี','ชัยภูมิ\xa0':'ชัยภูมิ','ชุุมพร':'ชุมพร','ชุุุมพร':'ชุมพร',
                                         'ดอนมดแดง':'อุบลราชธานี','ดินแดง':'กรุงเทพมหานคร','ตรััง':'ตรัง','ตราด\xa0':'ตราด','ตากใบ':'นราธิวาส','ต่างจังหวัด':'ไม่มีข้อมูล','ทุ่งเสลี่ยม':'สุโขทัย',
                                         'ท้ายบ้าน':'สมุทรปราการ','ธารโต':'ยะลา','นคนปฐม':'นครปฐม','นคปฐม':'นครปฐม','นครนปฐม':'นครปฐม','นครนาชสีมา':'นครราชสีมา','นครปฐม\xa0':'นครปฐม',
                                         'นครปบม':'นครปฐม','นครพนม\xa0':'นครพนม','นครยายก':'นครนายก','นครราขสีมา':'นครราชสีมา','นครราชธานี':'นครราชสีมา','นครราชศรีมา':'นครราชสีมา','นครราชสสีมา':'นครราชสีมา',
                                         'นครราชสีมา ลพบุรี':'นครราชสีมา','นครราชสีมา\xa0':'นครราชสีมา','นครศรธรรมราช':'นครศรีธรรมราช','นครศรี':'นครศรีธรรมราช','นครศรีธรมมราช':'นครศรีธรรมราช',
                                         'นครศรีธรมราช':'นครศรีธรรมราช','นครศรีธรรมราข':'นครศรีธรรมราช','นครศรีฯ':'นครศรีธรรมราช','นครศรีีธรรมราช':'นครศรีธรรมราช','นครศร๊ธรรมราช':'นครศรีธรรมราช',
                                         'นครศร๊ะรรมราช':'นครศรีธรรมราช','นครสรรค์':'นครสวรรค์','นครสรีธรรมราช':'นครศรีธรรมราช','นครสวรรค':'นครสวรรค์','นครสวรรค์\xa0':'นครสวรรค์','นครสีธรรมราช':'นครศรีธรรมราช',
                                         'นครฯ':'นครศรีธรรมราช','นคราชสีมา':'นครราชสีมา','นครีศรีธรรมราช':'นครศรีธรรมราช','นตรนายก':'นครนายก','นตรปฐม':'นครปฐม','นนทบุรี\xa0':'นนทบุรี',
                                         'นนทบุุรี':'นนทบุรี','นนทุบรี':'นนทบุรี','นนทุรี':'นนทบุรี','นนมบุรี':'นนทบุรี','นรศรีธรรมราช':'นครศรีธรรมราช','นราธิวาส\u200b':'นราธิวาส','นราธฺวาส':'นราธิวาส','นอกเขต':'ไม่มีข้อมูล',
                                         'นาราธิวาส':'นราธิวาส','นาวัง':'หนองบัวลำภู','น่าน/ฉะเชิงเทรา':'น่าน','บางกรวย':'นนทบุรี','บางกะปิ':'กรุงเทพมหานคร','บางนา':'กรุงเทพมหานคร','บางปะอิน':'กรุงเทพมหานคร',
                                         'บางละมุง':'ชลบุรี','บางศรีเมือง':'นนทบุรี','บางเพียง':'สมุทรปราการ','บึงโขงหลง':'บึงกาฬ','บุรีรัมภ์':'บุรีรัมย์','บุรีรัมย์\xa0':'บุรีรัมย์','บุรีรัยม์':'บุรีรัมย์','บุรีรีมย์':'บุรีรัมย์',
                                         'บ้านหลวง':'น่าน','ปจ':'ไม่มีข้อมูล','ปทึมธานี':'ปทุมธานี','ปทุทธานี':'ปทุมธานี','ปทุมฑานี':'ปทุมธานี','ปทุมทานี':'ปทุมธานี','ปทุมธาน':'ปทุมธานี','ปทุมธานี\xa0':'ปทุมธานี','ปทุมาธานี':'ปทุมธานี',
                                         'ปธุมธานี':'ปทุมธานี','ปทุมธานี.':'ปทุมธานี','ปทุมธานีี':'ปทุมธานี','ปทุุมธานี':'ปทุมธานี','ปมุมธานี':'ปทุมธานี',
                                         'ประจวนคีรีขันธ็':'ประจวบคีรีขันธ์','ประจวบ':'ประจวบคีรีขันธ์','ประจวบคิรีขันธ์':'ประจวบคีรีขันธ์','ประจวบคีรขันธ์':'ประจวบคีรีขันธ์','ประจวบคีรขัันธ์':'ประจวบคีรีขันธ์','ประจวบคีรีขัน':'ประจวบคีรีขันธ์',
                                         'ประจวบคีรีขันธื':'ประจวบคีรีขันธ์','ประจวบคีรีขันธฺ':'ประจวบคีรีขันธ์','ประจวบคีรีขันธ์\xa0':'ประจวบคีรีขันธ์','ประจวบคีรีขันธ์์':'ประจวบคีรีขันธ์','ประจวบคีรีขัันธ์':'ประจวบคีรีขันธ์','ประจวบคีีรีขันธ์':'ประจวบคีรีขันธ์',
                                         'ประจวบฯ':'ประจวบคีรีขันธ์','ประทุมธานี':'ปทุมธานี', 'ประเทศกัมพูชา':'ไม่มีข้อมูล','ปราจีบุรี':'ปราจีนบุรี','ปลวกแดง':'ระยอง','ปลายพระยา':'กระบี่', 'ปอยเปต':'ไม่มีข้อมูล','ปัตตนรี':'ปัตตานี',
                                         'ปัตตานนี':'ปัตตานี','ปัตตานีี':'ปัตตานี','ปัว':'น่าน','ปััตตานี':'ปัตตานี','ปุทมธานี':'ปทุมธานี','ป่าโมก':'อ่างทอง','พม่า':'ไม่มีข้อมูล','พรหมพิราม':'พิษณุโลก','พระนครศรียุธยา':'พระนครศรีอยุธยา',
                                         'พระนครศรีอยุทธยา':'พระนครศรีอยุธยา','พระนครศรีอยุทยา':'พระนครศรีอยุธยา','พระนครศรีอยุธยา\xa0':'พระนครศรีอยุธยา','พัทยา':'ชลบุรี','พัทลุุง':'พัทลุง','พัังงา':'พังงา',
                                         'พิษณุโลก\xa0':'พิษณุโลก','พิษณูโลก':'พิษณุโลก','ฟินแลนด์':'ไม่มีข้อมูล','ภาษีเจริญ':'กรุงเทพมหานคร','ภุเก็ต':'ภูเก็ต','ภูุเก็ต':'ภูเก็ต','ภููเก็ต':'ภูเก็ต','ภูเก็็ต':'ภูเก็ต','ภูเพียง':'น่าน',
                                         'มหาสาคาม':'มหาสารคาม','มาเลเซีย':'ไม่มีข้อมูล','มุกาดหาร':'มุกดาหาร','ยานนาวา':'กรุงเทพมหานคร','ร.จ.จ.นราธิวาส':'นราธิวาส','รอ':'ร้อยเอ็ด','ระบุ':'ไม่มีข้อมูล','ระยอง\xa0':'ระยอง',
                                         'ระอยง':'ระยอง','ราชบบุรี':'ราชบุรี','ราชบุรีี':'ราชบุรี','ราชบุรี\u200b':'ราชบุรี','ราชุรี':'ราชบุรี','ราชเทวี':'กรุงเทพมหานคร','ร้องกวาง':'แพร่','ลบุรี':'ลพบุรี','ลพบุรี.':'ลพบุรี','ลพบุรี\xa0':'ลพบุรี','ลอง':'แพร่',
                                         'ลาดกระบัง':'กรุงเทพมหานคร','ลาดพร้าว':'กรุงเทพมหานคร','ลาว':'ไม่มีข้อมูล','ลำพูน\u200b':'ลำพูน','ลำพููน':'ลำพูน','ลำลูกกา':'ปทุมธานี','วังชิ้น':'ลำปาง','วังทอง':'พิษณุโลก',
                                         'วิเศษชัยชาญ':'อ่างทอง','ศรีษะสะเกษ':'ศรีสะเกษ','ศรีษะเกษ':'ศรีสะเกษ','ศรีสระเกษ':'ศรีสะเกษ','ศีรสะเกษ':'ศรีสะเกษ','สครสวรรค์':'นครสวรรค์',
                                         'สงขลา\u200b':'สงขลา','สถานที่ทำงาน':'ไม่มีข้อมูล','สพรรณบุรี':'สุพรรณบุรี','สมถทรปราการ':'สมุทรปราการ','สมทรสงคราม':'สมุทรสงคราม','สมทรสาคร':'สมุทรสาคร','สมุครปราการ':'สมุทรปราการ',
                                         'สมุครสาคร':'สมุทรสาคร','สมุท':'ไม่มีข้อมูล','สมุทปราการ':'สมุทรปราการ','สมุทรปรากร':'สมุทรปราการ','สมุทรปรากรร':'สมุทรปราการ','สมุทรปราการ\xa0':'สมุทรปราการ','สมุทรศาคร':'สมุทรสาคร',
                                         'สมุทรสาคร\xa0':'สมุทรสาคร','สมุทรสาคา':'สมุทรสาคร','สมุทรสาคาร':'สมุทรสาคร','สมุทรสาทร':'สมุทรสาคร','สมุทรสารคร':'สมุทรสาคร','สมุทราปราการ':'สมุทรปราการ',
                                         'สมุทราสาคร':'สมุทรสาคร','สมุทสงคราม':'สมุทรสงคราม','สมุทสาคร':'สมุทรสาคร','สมุย':'สุราษฎร์ธานี','สมุุทรปราการ':'สมุทรปราการ','สมุุทรสงคราม':'สมุทรสงคราม','สมุุทรสาคร':'สมุทรสาคร',
                                         'สระก้ว':'สระแก้ว','สระบุรี\xa0':'สระบุรี','สรินทร์':'สุรินทร์','สวิสเซอร์แลนด์':'ไม่มีข้อมูล','สอง':'แพร่','สองแคว':'น่าน','สะพานสูง':'กรุงเทพมหานคร',
                                         'สะแก้ว':'สระแก้ว','สัตหีบ':'ชลบุรี','สัมผัสผู้ป่วยยืนยัน COVID20':'ไม่มีข้อมูล','สามุทรสาคร':'สมุทรสาคร','สารคาม':'มหาสารคาม','สารภี':'เชียงใหม่','สิงห์บุรี\xa0':'สิงห์บุรี',
                                         'สุทรปราการ':'สมุทรปราการ','สุพรรญบุรี':'สุพรรณบุรี','สุพรรณบุรั':'สุพรรณบุรี','สุพรรณบุรี\xa0':'สุพรรณบุรี','สุมทรปราการ':'สมุทรปราการ',
                                         'สุมทรสาคร':'สมุทรสาคร','สุมุทรปราการ':'สมุทรปราการ','สุมุทรสาคร':'สมุทรสาคร','สุระบุรี':'สระบุรี','สุราษ':'สุราษฎร์ธานี','สุราษฎณ์ธานี':'สุราษฎร์ธานี','สุราษฎธานี':'สุราษฎร์ธานี',
                                         'สุราษฎร์':'สุราษฎร์ธานี','สุราษฎร์ฯ':'สุราษฎร์ธานี','สุราษฎร์์ธานี':'สุราษฎร์ธานี','สุราษฎ์ธานี':'สุราษฎร์ธานี','สุราษฏร์ธานี':'สุราษฎร์ธานี','สุราษธานี':'สุราษฎร์ธานี',
                                         'สุราษร์ฎธานี':'สุราษฎร์ธานี','สุราษร์ธานี':'สุราษฎร์ธานี','สุราษฯ':'สุราษฎร์ธานี','สุรินทรื':'สุรินทร์','สุรินทร์ 32150':'สุรินทร์','สุรินทร์,รีสะเกษ':'สุรินทร์','สุรินทร์\xa0':'สุรินทร์','สุริมทร์':'สุรินทร์',
                                         'สุริะแก้ว':'สระแก้ว','สุวรรณภูมิ':'สมุทรปราการ','สุุพรรณบุรี':'สุพรรณบุรี','สุุราษฎร์ธานี':'สุราษฎร์ธานี','สุุราษฏร์ธานี':'สุราษฎร์ธนี','สุุราษฯ':'สุราษฎร์ธนี','สุุรินทร์':'สุรินทร์',
                                         'สุุุโขทัย':'สุโขทัย','สุโขทับ':'สุโขทัย','สุโขทัย\xa0':'สุโขทัย','สูงเม่น':'แพร่','หนวงบัวลำภู':'หนองบัวลำภู','หนองงคาย':'หนองคาย','หนองบัวภู':'หนองบัวลำภู',
                                         'หนองบัวลำพูน':'หนองบัวลำภู','หนองบัวลําภู':'หนองบัวลำภู','หนองบััวลำภู':'หนองบัวลำภู','หนองม่วงไข่':'แพร่','หนอบัวลำภู':'หนองบัวลำภู','หลายจังหวัด':'ไม่มีข้อมูล','หัวหิน':'ประจวบคีรีขันธ์',
                                         'ห้วยขวาง':'กรุงเทพมหานคร','อยุทธยา':'พระนครศรีอยุธยา','อยุธยา':'พระนครศรีอยุธยา','อยุุธยา':'พระนครศรีอยุธยา','อำนาจเจิญ':'อำนาจเจริญ','อำนาญเจริญ':'อำนาจเจริญ','อำนาเจริญ':'อำนาจเจริญ',
                                         'อิสราเอล':'ไม่มีข้อมูล','อุดธานี':'อุดรธานี','อุดร':'อุดรธานี','อุดรธาณี':'อุดรธานี','อุดรธานี\xa0':'อุดรธานี','อุดรธานีี':'อุดรธานี','อุดรราชธานี':'อุดรธานี','อุตรดิตถ์\xa0':'อุตรดิตถ์',
                                         'อุตรดิตถ์์':'อุตรดิตถ์','อุตรดิษถ์':'อุตรดิตถ์','อุตรดิิตถ์':'อุตรดิตถ์','อุตรติดถ์':'อุตรดิตถ์','อุบลราขธานี':'อุบลราชธานี','อุบลราชธานี\xa0':'อุบลราชธานี','อุุครดิตถ์':'อุตรดิตถ์',
                                         'อุุดรธาน':'อุดรธานี','อุุดรธานี':'อุดรธานี','อุุตรดิตถ์':'อุตรดิตถ์','อุุทัยธานี':'อุทัยธานี','อุุบลราชธานี':'อุบลราชธานี','อ่งทอง':'อ่างทอง','อ่างทอง\xa0':'อ่างทอง','อํานาจเจริญ':'อำนาจเจริญ',
                                         'เชิงเทรา':'ฉะเชิงเทรา','เชียรใหญ่':'นครศรีธรรมราช','เชีียงราย':'เชียงราย','เชีียงใหม่':'เชียงใหม่','เด่นชัย':'แพร่',
                                         'เพขรบุรี':'เพชรบูรณ์','เพขรบูรณื':'เพชรบูรณ์','เพขรบูรณ์':'เพชรบูรณ์','เพชรบุรณ์':'เพชรบูรณ์','เพชรบุรี':'เพชรบูรณ์','เพชรบุรึ':'เพชรบูรณ์','เพชรบุุรี':'เพชรบูรณ์','เพชรบุูรณ์':'เพชรบูรณ์','เพชรบูรณ์\xa0':'เพชรบูรณ์',
                                         'เพชรบูร์':'เพชรบูรณ์','เพชรบููรณ์':'เพชรบูรณ์','เมือง':'แพร่','เมืองตาก':'ตาก','เมืองน่าน':'น่าน','เมืองปัตตานี':'ปัตตานี','เรือ':'เลย','เลย\xa0':'เลย','เวียงจันทร์':'ไม่มีข้อมูล','เวียงสา':'น่าน','แม่ทะ':'ลำปาง',
                                         'แล้วป่วย':'ไม่มีข้อมูล','โพธิ์ทอง':'อ่างทอง','ไชโย':'อ่างทอง','ไม่มีข้อมูล':'ไม่มีข้อมูล','ไม่มีชื่อหอพัก':'ไม่มีข้อมูล','ไม่ระบุ':'ไม่มีข้อมูล','สมุทรปรากา':'สมุทรปราการ'}, inplace=True)# แก้ไขข้อมูลที่พิมพ์จังหวัดผิด ให้อยู่ในชื่อจังหวัดที่ถูกต้อง

/usr/local/lib/python3.7/dist-packages/pandas/core/generic.py:6619: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return self._update_inplace(result)

## รวมตารางข้อมูลจำนวนผู้ติดเชื้อ

### รวมตารางข้อมูลจำนวนผู้ติดเชื้อช่วงที่ 1 ,ข้อมูลจำนวนผู้ติดเชื้อช่วงที่ 2, ข้อมูลจำนวนผู้ติดเชื้อช่วงที่ 3 และข้อมูลจำนวนผู้ติดเชื้อช่วงที่ 4

In [146]:
data1234= pd.concat([data_01, data_02, data_03, data_04],axis=0) #vertical_concat
data1234

,announce_date,age,risk,province_of_onset,district_of_onset
0,12/1/2020,61.0,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,ไม่มีข้อมูล
1,17/1/2020,74.0,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,ไม่มีข้อมูล
2,22/1/2020,73.0,คนต่างชาติเดินทางมาจากต่างประเทศ,นครปฐม,เมือง
3,22/1/2020,68.0,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,ไม่มีข้อมูล
4,24/1/2020,66.0,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,ไม่มีข้อมูล
...,...,...,...,...,...
357076,15/3/2022,36.943725,ทัณฑสถาน/เรือนจำ,ไม่มีข้อมูล,ไม่มีข้อมูล
357077,15/3/2022,36.943725,ทัณฑสถาน/เรือนจำ,ไม่มีข้อมูล,ไม่มีข้อมูล
357078,15/3/2022,36.943725,ทัณฑสถาน/เรือนจำ,ไม่มีข้อมูล,ไม่มีข้อมูล
357079,15/3/2022,36.943725,ทัณฑสถาน/เรือนจำ,ไม่มีข้อมูล,ไม่มีข้อมูล
357080,15/3/2022,36.943725,ทัณฑสถาน/เรือนจำ,ไม่มีข้อมูล,ไม่มีข้อมูล

In [147]:
set(data1234['province_of_onset'])

{'กระบี่',
 'กรุงเทพมหานคร',
 'กาญจนบุรี',
 'กาฬสินธุ์',
 'กำแพงเพชร',
 'ขอนแก่น',
 'ขัยนาท',
 'ขัยภูมิ',
 'จันทบุรี',
 'ฉะเชิงเทรา',
 'ชลบุรี',
 'ชัยนาท',
 'ชัยภูมิ',
 'ชุมพร',
 'ตรัง',
 'ตราด',
 'ตาก',
 'นครนายก',
 'นครปฐม',
 'นครพนม',
 'นครราชสีมา',
 'นครศรีธรรมราช',
 'นครสวรรค์',
 'นนทบุรี',
 'นราธิวาส',
 'น่าน',
 'บึงกาฬ',
 'บุรีรัมย์',
 'ปทุมธานี',
 'ประจวบคีรีขันธ์',
 'ปราจีนบุรี',
 'ปัตตานี',
 'ปัตาตานี',
 'พระนครศรีอยุธยา',
 'พะเยา',
 'พังงา',
 'พัทลุง',
 'พิจิตร',
 'พิษณุโลก',
 'ภูเก็ต',
 'มหาสารคาม',
 'มุกดาหาร',
 'ยะลา',
 'ยโสธร',
 'ระนอง',
 'ระยอง',
 'ราชบุรี',
 'ร้อยเอ็ด',
 'ลพบุรี',
 'ลำปาง',
 'ลำพูน',
 'ศรีสะเกษ',
 'สกลนคร',
 'สงขลา',
 'สตูล',
 'สมุทรปราการ',
 'สมุทรสงคราม',
 'สมุทรสาคร',
 'สระบุรี',
 'สระแก้ว',
 'สิงห์บุรี',
 'สุพรรณบุรี',
 'สุราษฎร์ธนี',
 'สุราษฎร์ธานี',
 'สุรินทร์',
 'สุโขทัย',
 'หนองคาย',
 'หนองบัวลำภู',
 'อำนาจเจริญ',
 'อุดรธานี',
 'อุตรดิตถ์',
 'อุทัยธานี',
 'อุทัยานี',
 'อุบลราชธานี',
 'อ่างทอง',
 'เชียงราย',
 'เชียงใหม่',
 'เพชรบูรณ์',
 'เลย',
 'แพร่',
 'แม่ฮ่องสอน',
 'ไม่มีข้อมูล'}

# ข้อมูลจังหวัดแต่ละภูมิภาค

In [148]:
import pandas as pd

In [149]:
data_province = {'province': ['อำนาจเจริญ', 'บึงกาฬ', 'บุรีรัมย์', 'ชัยภูมิ', 'กาฬสินธุ์', 'ขอนแก่น', 'เลย', 'มหาสารคาม', 'มุกดาหาร', 'นครพนม', 'นครราชสีมา', 'หนองบัวลำภู', 'หนองคาย', 'ร้อยเอ็ด', 'สกลนคร', 'ศรีสะเกษ', 'สุรินทร์', 'อุบลราชธานี', 'อุดรธานี', 'ยโสธร','เชียงใหม่', 'เชียงราย', 'ลำปาง', 'ลำพูน', 'แม่ฮ่องสอน', 'น่าน', 'พะเยา', 'แพร่', 'อุตรดิตถ์','ตาก','สุโขทัย', 'พิษณุโลก', 'พิจิตร', 'กำแพงเพชร', 'เพชรบูรณ์','นครสวรรค์', 'อุทัยธานี','อ่างทอง', 'ชัยนาท', 'พระนครศรีอยุธยา', 'กรุงเทพมหานคร', 'ลพบุรี', 'นครปฐม', 'นนทบุรี', 'ปทุมธานี', 'สมุทรปราการ','สมุทรสาคร', 'สมุทรสงคราม','สระบุรี', 'สิงห์บุรี', 'สุพรรณบุรี','นครนายก','ฉะเชิงเทรา', 'จันทบุรี', 'ชลบุรี', 'ปราจีนบุรี', 'ระยอง', 'สระแก้ว', 'ตราด','กาญจนบุรี', 'ราชบุรี','เพชรบุรี', 'ประจวบคีรีขันธ์','ชุมพร', 'นครศรีธรรมราช', 'นราธิวาส', 'ปัตตานี', 'พัทลุง', 'สงขลา', 'สุราษฎร์ธานี', 'ยะลา','กระบี่', 'พังงา', 'ภูเก็ต', 'ระนอง', 'สตูล', 'ตรัง'],
            '6 ภูมิภาค (ภูมิศาสตร์)': ['ตะวันออกเฉียงเหนือ','ตะวันออกเฉียงเหนือ','ตะวันออกเฉียงเหนือ','ตะวันออกเฉียงเหนือ','ตะวันออกเฉียงเหนือ','ตะวันออกเฉียงเหนือ','ตะวันออกเฉียงเหนือ','ตะวันออกเฉียงเหนือ','ตะวันออกเฉียงเหนือ','ตะวันออกเฉียงเหนือ','ตะวันออกเฉียงเหนือ','ตะวันออกเฉียงเหนือ','ตะวันออกเฉียงเหนือ','ตะวันออกเฉียงเหนือ','ตะวันออกเฉียงเหนือ','ตะวันออกเฉียงเหนือ','ตะวันออกเฉียงเหนือ','ตะวันออกเฉียงเหนือ','ตะวันออกเฉียงเหนือ','ตะวันออกเฉียงเหนือ','เหนือ','เหนือ','เหนือ','เหนือ','เหนือ','เหนือ','เหนือ','เหนือ','เหนือ','ตะวันตก','กลาง','กลาง','กลาง','กลาง','กลาง','กลาง','กลาง','กลาง','กลาง','กลาง','กลาง','กลาง','กลาง','กลาง','กลาง','กลาง','กลาง','กลาง','กลาง','กลาง','กลาง','กลาง','ตะวันออก','ตะวันออก','ตะวันออก','ตะวันออก','ตะวันออก','ตะวันออก','ตะวันออก','ตะวันตก','ตะวันตก','ตะวันตก','ตะวันตก','ใต้','ใต้','ใต้','ใต้','ใต้','ใต้','ใต้','ใต้','ใต้','ใต้','ใต้','ใต้','ใต้','ใต้']
}

In [150]:
province_df = pd.DataFrame.from_dict(data_province) #คำสั่งสร้างตาราง Dataframe
province_df

      province 6 ภูมิภาค (ภูมิศาสตร์)
0   อำนาจเจริญ     ตะวันออกเฉียงเหนือ
1       บึงกาฬ     ตะวันออกเฉียงเหนือ
2    บุรีรัมย์     ตะวันออกเฉียงเหนือ
3      ชัยภูมิ     ตะวันออกเฉียงเหนือ
4    กาฬสินธุ์     ตะวันออกเฉียงเหนือ
..         ...                    ...
72       พังงา                    ใต้
73      ภูเก็ต                    ใต้
74       ระนอง                    ใต้
75        สตูล                    ใต้
76        ตรัง                    ใต้

[77 rows x 2 columns]

## รวมตารางข้อมูลจำนวนผู้ติดเชื้อกับข้อมูลจังหวัดแต่ละภูมิภาค

In [151]:
case_pro = data1234.merge(province_df,how='left',left_on='province_of_onset',right_on = 'province') 
case_pro

,announce_date,age,risk,province_of_onset,district_of_onset,province,6 ภูมิภาค (ภูมิศาสตร์)
0,12/1/2020,61.0,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,ไม่มีข้อมูล,กรุงเทพมหานคร,กลาง
1,17/1/2020,74.0,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,ไม่มีข้อมูล,กรุงเทพมหานคร,กลาง
2,22/1/2020,73.0,คนต่างชาติเดินทางมาจากต่างประเทศ,นครปฐม,เมือง,นครปฐม,กลาง
3,22/1/2020,68.0,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,ไม่มีข้อมูล,กรุงเทพมหานคร,กลาง
4,24/1/2020,66.0,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,ไม่มีข้อมูล,กรุงเทพมหานคร,กลาง
...,...,...,...,...,...,...,...
3249474,15/3/2022,36.943725,ทัณฑสถาน/เรือนจำ,ไม่มีข้อมูล,ไม่มีข้อมูล,NaN,NaN
3249475,15/3/2022,36.943725,ทัณฑสถาน/เรือนจำ,ไม่มีข้อมูล,ไม่มีข้อมูล,NaN,NaN
3249476,15/3/2022,36.943725,ทัณฑสถาน/เรือนจำ,ไม่มีข้อมูล,ไม่มีข้อมูล,NaN,NaN
3249477,15/3/2022,36.943725,ทัณฑสถาน/เรือนจำ,ไม่มีข้อมูล,ไม่มีข้อมูล,NaN,NaN
3249478,15/3/2022,36.943725,ทัณฑสถาน/เรือนจำ,ไม่มีข้อมูล,ไม่มีข้อมูล,NaN,NaN

In [152]:
case_pro.isnull().any()

announce_date             False
age                       False
risk                      False
province_of_onset         False
district_of_onset         False
province                   True
6 ภูมิภาค (ภูมิศาสตร์)     True
dtype: bool

แทน missing ด้วยค่าที่เหมาะสม (fillna())

In [153]:
case_pro01 = case_pro.fillna(value={'province':'ไม่มีข้อมูล','6 ภูมิภาค (ภูมิศาสตร์)':'ไม่มีข้อมูล'})
case_pro01

,announce_date,age,risk,province_of_onset,district_of_onset,province,6 ภูมิภาค (ภูมิศาสตร์)
0,12/1/2020,61.0,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,ไม่มีข้อมูล,กรุงเทพมหานคร,กลาง
1,17/1/2020,74.0,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,ไม่มีข้อมูล,กรุงเทพมหานคร,กลาง
2,22/1/2020,73.0,คนต่างชาติเดินทางมาจากต่างประเทศ,นครปฐม,เมือง,นครปฐม,กลาง
3,22/1/2020,68.0,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,ไม่มีข้อมูล,กรุงเทพมหานคร,กลาง
4,24/1/2020,66.0,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,ไม่มีข้อมูล,กรุงเทพมหานคร,กลาง
...,...,...,...,...,...,...,...
3249474,15/3/2022,36.943725,ทัณฑสถาน/เรือนจำ,ไม่มีข้อมูล,ไม่มีข้อมูล,ไม่มีข้อมูล,ไม่มีข้อมูล
3249475,15/3/2022,36.943725,ทัณฑสถาน/เรือนจำ,ไม่มีข้อมูล,ไม่มีข้อมูล,ไม่มีข้อมูล,ไม่มีข้อมูล
3249476,15/3/2022,36.943725,ทัณฑสถาน/เรือนจำ,ไม่มีข้อมูล,ไม่มีข้อมูล,ไม่มีข้อมูล,ไม่มีข้อมูล
3249477,15/3/2022,36.943725,ทัณฑสถาน/เรือนจำ,ไม่มีข้อมูล,ไม่มีข้อมูล,ไม่มีข้อมูล,ไม่มีข้อมูล
3249478,15/3/2022,36.943725,ทัณฑสถาน/เรือนจำ,ไม่มีข้อมูล,ไม่มีข้อมูล,ไม่มีข้อมูล,ไม่มีข้อมูล

### ตารางข้อมูลจำนวนผู้ติดเชื้อช่วงที่ 1 และภูมิภาคจังหวัด

In [154]:
data_pro1 = data_01.merge(province_df,how='left',left_on='province_of_onset',right_on = 'province') 
data_pro1

,announce_date,age,risk,province_of_onset,district_of_onset,province,6 ภูมิภาค (ภูมิศาสตร์)
0,12/1/2020,61.0,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,ไม่มีข้อมูล,กรุงเทพมหานคร,กลาง
1,17/1/2020,74.0,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,ไม่มีข้อมูล,กรุงเทพมหานคร,กลาง
2,22/1/2020,73.0,คนต่างชาติเดินทางมาจากต่างประเทศ,นครปฐม,เมือง,นครปฐม,กลาง
3,22/1/2020,68.0,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,ไม่มีข้อมูล,กรุงเทพมหานคร,กลาง
4,24/1/2020,66.0,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,ไม่มีข้อมูล,กรุงเทพมหานคร,กลาง
...,...,...,...,...,...,...,...
839766,12/8/2021,52.0,ทัณฑสถาน/เรือนจำ,กาญจนบุรี,ไม่มีข้อมูล,กาญจนบุรี,ตะวันตก
839767,12/8/2021,34.0,ทัณฑสถาน/เรือนจำ,กาญจนบุรี,ไม่มีข้อมูล,กาญจนบุรี,ตะวันตก
839768,12/8/2021,31.0,ทัณฑสถาน/เรือนจำ,กาญจนบุรี,ไม่มีข้อมูล,กาญจนบุรี,ตะวันตก
839769,12/8/2021,83.0,ทัณฑสถาน/เรือนจำ,กาญจนบุรี,ไม่มีข้อมูล,กาญจนบุรี,ตะวันตก
839770,12/8/2021,47.0,ทัณฑสถาน/เรือนจำ,กาญจนบุรี,ไม่มีข้อมูล,กาญจนบุรี,ตะวันตก

In [155]:
data_pro1.isnull().any()

announce_date             False
age                       False
risk                      False
province_of_onset         False
district_of_onset         False
province                   True
6 ภูมิภาค (ภูมิศาสตร์)     True
dtype: bool

In [156]:
data_pro001 = data_pro1.fillna(value={'province':'ไม่มีข้อมูล','6 ภูมิภาค (ภูมิศาสตร์)':'ไม่มีข้อมูล'})
data_pro001

,announce_date,age,risk,province_of_onset,district_of_onset,province,6 ภูมิภาค (ภูมิศาสตร์)
0,12/1/2020,61.0,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,ไม่มีข้อมูล,กรุงเทพมหานคร,กลาง
1,17/1/2020,74.0,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,ไม่มีข้อมูล,กรุงเทพมหานคร,กลาง
2,22/1/2020,73.0,คนต่างชาติเดินทางมาจากต่างประเทศ,นครปฐม,เมือง,นครปฐม,กลาง
3,22/1/2020,68.0,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,ไม่มีข้อมูล,กรุงเทพมหานคร,กลาง
4,24/1/2020,66.0,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,ไม่มีข้อมูล,กรุงเทพมหานคร,กลาง
...,...,...,...,...,...,...,...
839766,12/8/2021,52.0,ทัณฑสถาน/เรือนจำ,กาญจนบุรี,ไม่มีข้อมูล,กาญจนบุรี,ตะวันตก
839767,12/8/2021,34.0,ทัณฑสถาน/เรือนจำ,กาญจนบุรี,ไม่มีข้อมูล,กาญจนบุรี,ตะวันตก
839768,12/8/2021,31.0,ทัณฑสถาน/เรือนจำ,กาญจนบุรี,ไม่มีข้อมูล,กาญจนบุรี,ตะวันตก
839769,12/8/2021,83.0,ทัณฑสถาน/เรือนจำ,กาญจนบุรี,ไม่มีข้อมูล,กาญจนบุรี,ตะวันตก
839770,12/8/2021,47.0,ทัณฑสถาน/เรือนจำ,กาญจนบุรี,ไม่มีข้อมูล,กาญจนบุรี,ตะวันตก

### ตารางข้อมูลจำนวนผู้ติดเชื้อช่วงที่ 2 และภูมิภาคจังหวัด

In [157]:
data_pro2 = data_02.merge(province_df,how='left',left_on='province_of_onset',right_on = 'province') 
data_pro2

,announce_date,age,risk,province_of_onset,district_of_onset,province,6 ภูมิภาค (ภูมิศาสตร์)
0,12/8/2021,7.0,อื่นๆ,ไม่มีข้อมูล,ไม่มีข้อมูล,NaN,NaN
1,12/8/2021,1.0,อื่นๆ,ไม่มีข้อมูล,ไม่มีข้อมูล,NaN,NaN
2,12/8/2021,35.0,อื่นๆ,ไม่มีข้อมูล,ไม่มีข้อมูล,NaN,NaN
3,12/8/2021,33.0,อื่นๆ,ไม่มีข้อมูล,ไม่มีข้อมูล,NaN,NaN
4,12/8/2021,14.0,สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้,ไม่มีข้อมูล,ไม่มีข้อมูล,NaN,NaN
...,...,...,...,...,...,...,...
1042163,25/10/2021,45.0,ทัณฑสถาน/เรือนจำ,ไม่มีข้อมูล,ไม่มีข้อมูล,NaN,NaN
1042164,25/10/2021,31.0,ทัณฑสถาน/เรือนจำ,ไม่มีข้อมูล,ไม่มีข้อมูล,NaN,NaN
1042165,25/10/2021,31.0,ทัณฑสถาน/เรือนจำ,ไม่มีข้อมูล,ไม่มีข้อมูล,NaN,NaN
1042166,25/10/2021,24.0,ทัณฑสถาน/เรือนจำ,ไม่มีข้อมูล,ไม่มีข้อมูล,NaN,NaN
1042167,25/10/2021,25.0,ทัณฑสถาน/เรือนจำ,ไม่มีข้อมูล,ไม่มีข้อมูล,NaN,NaN

In [158]:
data_pro2.isnull().any()

announce_date             False
age                       False
risk                      False
province_of_onset         False
district_of_onset         False
province                   True
6 ภูมิภาค (ภูมิศาสตร์)     True
dtype: bool

In [159]:
data_pro002 = data_pro2.fillna(value={'province':'ไม่มีข้อมูล','6 ภูมิภาค (ภูมิศาสตร์)':'ไม่มีข้อมูล'})
data_pro002

,announce_date,age,risk,province_of_onset,district_of_onset,province,6 ภูมิภาค (ภูมิศาสตร์)
0,12/8/2021,7.0,อื่นๆ,ไม่มีข้อมูล,ไม่มีข้อมูล,ไม่มีข้อมูล,ไม่มีข้อมูล
1,12/8/2021,1.0,อื่นๆ,ไม่มีข้อมูล,ไม่มีข้อมูล,ไม่มีข้อมูล,ไม่มีข้อมูล
2,12/8/2021,35.0,อื่นๆ,ไม่มีข้อมูล,ไม่มีข้อมูล,ไม่มีข้อมูล,ไม่มีข้อมูล
3,12/8/2021,33.0,อื่นๆ,ไม่มีข้อมูล,ไม่มีข้อมูล,ไม่มีข้อมูล,ไม่มีข้อมูล
4,12/8/2021,14.0,สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้,ไม่มีข้อมูล,ไม่มีข้อมูล,ไม่มีข้อมูล,ไม่มีข้อมูล
...,...,...,...,...,...,...,...
1042163,25/10/2021,45.0,ทัณฑสถาน/เรือนจำ,ไม่มีข้อมูล,ไม่มีข้อมูล,ไม่มีข้อมูล,ไม่มีข้อมูล
1042164,25/10/2021,31.0,ทัณฑสถาน/เรือนจำ,ไม่มีข้อมูล,ไม่มีข้อมูล,ไม่มีข้อมูล,ไม่มีข้อมูล
1042165,25/10/2021,31.0,ทัณฑสถาน/เรือนจำ,ไม่มีข้อมูล,ไม่มีข้อมูล,ไม่มีข้อมูล,ไม่มีข้อมูล
1042166,25/10/2021,24.0,ทัณฑสถาน/เรือนจำ,ไม่มีข้อมูล,ไม่มีข้อมูล,ไม่มีข้อมูล,ไม่มีข้อมูล
1042167,25/10/2021,25.0,ทัณฑสถาน/เรือนจำ,ไม่มีข้อมูล,ไม่มีข้อมูล,ไม่มีข้อมูล,ไม่มีข้อมูล

### ตารางข้อมูลจำนวนผู้ติดเชื้อช่วงที่ 3 และภูมิภาคจังหวัด

In [160]:
data_pro3 = data_03.merge(province_df,how='left',left_on='province_of_onset',right_on = 'province') 
data_pro3

,announce_date,age,risk,province_of_onset,district_of_onset,province,6 ภูมิภาค (ภูมิศาสตร์)
0,26/10/2021,20.0,อื่นๆ,ลำปาง,เมืองลำปาง,ลำปาง,เหนือ
1,26/10/2021,42.0,อื่นๆ,ลำปาง,เมืองลำปาง,ลำปาง,เหนือ
2,26/10/2021,33.0,ไปสถานที่ชุมชน เช่น ตลาดนัด สถานที่ท่องเที่ยว,ลำปาง,ห้างฉัตร,ลำปาง,เหนือ
3,26/10/2021,52.0,ไปสถานที่ชุมชน เช่น ตลาดนัด สถานที่ท่องเที่ยว,ลำปาง,ห้างฉัตร,ลำปาง,เหนือ
4,26/10/2021,84.0,สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้,ลำปาง,เมืองลำปาง,ลำปาง,เหนือ
...,...,...,...,...,...,...,...
1010454,27/2/2022,ปี,ทัณฑสถาน/เรือนจำ,ไม่มีข้อมูล,ไม่มีข้อมูล,NaN,NaN
1010455,27/2/2022,ปี,ทัณฑสถาน/เรือนจำ,ไม่มีข้อมูล,ไม่มีข้อมูล,NaN,NaN
1010456,27/2/2022,ปี,ทัณฑสถาน/เรือนจำ,ไม่มีข้อมูล,ไม่มีข้อมูล,NaN,NaN
1010457,27/2/2022,ปี,ทัณฑสถาน/เรือนจำ,ไม่มีข้อมูล,ไม่มีข้อมูล,NaN,NaN
1010458,27/2/2022,ปี,ทัณฑสถาน/เรือนจำ,ไม่มีข้อมูล,ไม่มีข้อมูล,NaN,NaN

In [161]:
data_pro3.isnull().any()

announce_date             False
age                       False
risk                      False
province_of_onset         False
district_of_onset         False
province                   True
6 ภูมิภาค (ภูมิศาสตร์)     True
dtype: bool

In [162]:
data_pro003 = data_pro3.fillna(value={'province':'ไม่มีข้อมูล','6 ภูมิภาค (ภูมิศาสตร์)':'ไม่มีข้อมูล'})
data_pro003

,announce_date,age,risk,province_of_onset,district_of_onset,province,6 ภูมิภาค (ภูมิศาสตร์)
0,26/10/2021,20.0,อื่นๆ,ลำปาง,เมืองลำปาง,ลำปาง,เหนือ
1,26/10/2021,42.0,อื่นๆ,ลำปาง,เมืองลำปาง,ลำปาง,เหนือ
2,26/10/2021,33.0,ไปสถานที่ชุมชน เช่น ตลาดนัด สถานที่ท่องเที่ยว,ลำปาง,ห้างฉัตร,ลำปาง,เหนือ
3,26/10/2021,52.0,ไปสถานที่ชุมชน เช่น ตลาดนัด สถานที่ท่องเที่ยว,ลำปาง,ห้างฉัตร,ลำปาง,เหนือ
4,26/10/2021,84.0,สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้,ลำปาง,เมืองลำปาง,ลำปาง,เหนือ
...,...,...,...,...,...,...,...
1010454,27/2/2022,ปี,ทัณฑสถาน/เรือนจำ,ไม่มีข้อมูล,ไม่มีข้อมูล,ไม่มีข้อมูล,ไม่มีข้อมูล
1010455,27/2/2022,ปี,ทัณฑสถาน/เรือนจำ,ไม่มีข้อมูล,ไม่มีข้อมูล,ไม่มีข้อมูล,ไม่มีข้อมูล
1010456,27/2/2022,ปี,ทัณฑสถาน/เรือนจำ,ไม่มีข้อมูล,ไม่มีข้อมูล,ไม่มีข้อมูล,ไม่มีข้อมูล
1010457,27/2/2022,ปี,ทัณฑสถาน/เรือนจำ,ไม่มีข้อมูล,ไม่มีข้อมูล,ไม่มีข้อมูล,ไม่มีข้อมูล
1010458,27/2/2022,ปี,ทัณฑสถาน/เรือนจำ,ไม่มีข้อมูล,ไม่มีข้อมูล,ไม่มีข้อมูล,ไม่มีข้อมูล

### ตารางข้อมูลจำนวนผู้ติดเชื้อช่วงที่ 4 และภูมิภาคจังหวัด

In [163]:
data_pro4 = data_04.merge(province_df,how='left',left_on='province_of_onset',right_on = 'province') 
data_pro4

,announce_date,age,risk,province_of_onset,district_of_onset,province,6 ภูมิภาค (ภูมิศาสตร์)
0,28/2/2022,41.000000,สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้,พะเยา,เมืองพะเยา,พะเยา,เหนือ
1,28/2/2022,45.000000,สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้,พะเยา,เมืองพะเยา,พะเยา,เหนือ
2,28/2/2022,40.000000,สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้,พะเยา,เมืองพะเยา,พะเยา,เหนือ
3,28/2/2022,44.000000,สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้,พะเยา,เมืองพะเยา,พะเยา,เหนือ
4,28/2/2022,11.000000,สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้,พะเยา,เมืองพะเยา,พะเยา,เหนือ
...,...,...,...,...,...,...,...
357076,15/3/2022,36.943725,ทัณฑสถาน/เรือนจำ,ไม่มีข้อมูล,ไม่มีข้อมูล,NaN,NaN
357077,15/3/2022,36.943725,ทัณฑสถาน/เรือนจำ,ไม่มีข้อมูล,ไม่มีข้อมูล,NaN,NaN
357078,15/3/2022,36.943725,ทัณฑสถาน/เรือนจำ,ไม่มีข้อมูล,ไม่มีข้อมูล,NaN,NaN
357079,15/3/2022,36.943725,ทัณฑสถาน/เรือนจำ,ไม่มีข้อมูล,ไม่มีข้อมูล,NaN,NaN
357080,15/3/2022,36.943725,ทัณฑสถาน/เรือนจำ,ไม่มีข้อมูล,ไม่มีข้อมูล,NaN,NaN

In [164]:
data_pro4.isnull().any()

announce_date             False
age                       False
risk                      False
province_of_onset         False
district_of_onset         False
province                   True
6 ภูมิภาค (ภูมิศาสตร์)     True
dtype: bool

In [165]:
data_pro004 = data_pro4.fillna(value={'province':'ไม่มีข้อมูล','6 ภูมิภาค (ภูมิศาสตร์)':'ไม่มีข้อมูล'})
data_pro004

,announce_date,age,risk,province_of_onset,district_of_onset,province,6 ภูมิภาค (ภูมิศาสตร์)
0,28/2/2022,41.000000,สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้,พะเยา,เมืองพะเยา,พะเยา,เหนือ
1,28/2/2022,45.000000,สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้,พะเยา,เมืองพะเยา,พะเยา,เหนือ
2,28/2/2022,40.000000,สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้,พะเยา,เมืองพะเยา,พะเยา,เหนือ
3,28/2/2022,44.000000,สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้,พะเยา,เมืองพะเยา,พะเยา,เหนือ
4,28/2/2022,11.000000,สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้,พะเยา,เมืองพะเยา,พะเยา,เหนือ
...,...,...,...,...,...,...,...
357076,15/3/2022,36.943725,ทัณฑสถาน/เรือนจำ,ไม่มีข้อมูล,ไม่มีข้อมูล,ไม่มีข้อมูล,ไม่มีข้อมูล
357077,15/3/2022,36.943725,ทัณฑสถาน/เรือนจำ,ไม่มีข้อมูล,ไม่มีข้อมูล,ไม่มีข้อมูล,ไม่มีข้อมูล
357078,15/3/2022,36.943725,ทัณฑสถาน/เรือนจำ,ไม่มีข้อมูล,ไม่มีข้อมูล,ไม่มีข้อมูล,ไม่มีข้อมูล
357079,15/3/2022,36.943725,ทัณฑสถาน/เรือนจำ,ไม่มีข้อมูล,ไม่มีข้อมูล,ไม่มีข้อมูล,ไม่มีข้อมูล
357080,15/3/2022,36.943725,ทัณฑสถาน/เรือนจำ,ไม่มีข้อมูล,ไม่มีข้อมูล,ไม่มีข้อมูล,ไม่มีข้อมูล

# ข้อมูลรายชื่อห้องปฏิบัติการเครือข่ายตรวจโควิด-19

In [166]:
lab = pd.read_csv('labscovid19_update080365.csv', encoding="TIS-620") # TIS-620 คือ Decoding ที่เราใช้อ่านจาก file.csv แล้วนำค่ากลับมา Encodingเป็น UTF-8-sig เพื่อให้ตัว microsoft excel ในเครื่องเราที่มีdefault ในการอ่านค่าเป็น utf-8 อ่านได้ 
lab

,orgth,orgen,telephone,address,website,healtharea,agency,province,district,area,npsts,pooledsaliva,pooledswab
0,ศูนย์วิทยาศาสตร์การแพทย์ที่ 1 เชียงใหม่,Regional Medical Sciences Center 1 Chiang Mai,0-5311-2188-90,191 หมู่ 8 ต.ดอนแก้ว อ.แม่ริม จ.เชียงใหม่ 50180,http://webapp1.dmsc.moph.go.th/cm1/web/post-gr...,เขต 1,ภาครัฐ,เชียงใหม่,แม่ริม,ต่างจังหวัด,เปิดตรวจแล้ว,เปิดตรวจแล้ว,เปิดตรวจแล้ว
1,ศูนย์วิทยาศาสตร์การแพทย์ที่ 1/1 เชียงราย,Regional Medical Sciences Center 1/1 Chiang Rai,0-5317-6224-6,148 หมู่ 3 ตำบลนางแล อำเภอเมือง จังหวัดเชียงรา...,http://cri.dmsc.moph.go.th/,เขต 1,ภาครัฐ,เชียงราย,เมืองเชียงราย,ต่างจังหวัด,เปิดตรวจแล้ว,เปิดตรวจแล้ว,เปิดตรวจแล้ว
2,สำนักงานป้องกันควบคุมโรคที่ 1 เชียงใหม่,The Office of Disease Prevention and Control 1...,0-5314-0774,447 ถนนเชียงใหม่-ลำพูน ตำบลวัดเกต อำเภอเมือง จ...,https://ddc.moph.go.th/odpc1/,เขต 1,ภาครัฐ,เชียงใหม่,เมืองเชียงใหม่,ต่างจังหวัด,เปิดตรวจแล้ว,NaN,เปิดตรวจแล้ว
3,โรงพยาบาลนครพิงค์,Nakornping Hospital,0-5399-9200,159 ม.10 ถ.โชตนา ต.ดอนแก้ว อ.แม่ริม จ.เชียงใหม...,http://www.nkp-hospital.go.th/th/,เขต 1,ภาครัฐ,เชียงใหม่,แม่ริม,ต่างจังหวัด,เปิดตรวจแล้ว,เปิดตรวจแล้ว,เปิดตรวจแล้ว
4,โรงพยาบาลลำปาง,Lampang Hospital,0-5423-7400,28/3 ห้องอณูชีวโมเลกุล กลุ่มงานเทคนิคการแพทย์ ...,http://www.lph.go.th/lpweb/,เขต 1,ภาครัฐ,ลำปาง,เมืองลำปาง,ต่างจังหวัด,เปิดตรวจแล้ว,เปิดตรวจแล้ว,เปิดตรวจแล้ว
...,...,...,...,...,...,...,...,...,...,...,...,...,...
508,งานอณูชีววิทยา โรงพยาบาลราชวิถี,NaN,0-2206-2900 ต่อ 40610-2,NaN,http://www.rajavithi.go.th/rj/medtech/biomolec...,เขต 13,ภาครัฐ,กรุงเทพมหานคร,ราชเทวี,กรุงเทพและปริมณฑล,เปิดตรวจแล้ว,NaN,NaN
509,งานจุลชีววิทยา โรงพยาบาลราชวิถี,NaN,"0-2206-2900 ต่อ 3142, 3143",NaN,http://www.rajavithi.go.th/rj/medtech/microbio...,เขต 13,ภาครัฐ,กรุงเทพมหานคร,ราชเทวี,กรุงเทพและปริมณฑล,เปิดตรวจแล้ว,NaN,NaN
510,โรงพยาบาลประโคนชัย,NaN,0-4467-0103,NaN,https://www.facebook.com/pkchospital,เขต 9,ภาครัฐ,บุรีรัมย์,ประโคนชัย,ต่างจังหวัด,เปิดตรวจแล้ว,NaN,NaN
511,กรุงเทพพยาธิ-แลป คลินิกเทคนิคการแพทย์,NaN,0-2619-2909,NaN,https://www.bpl.co.th/pweb/,เขต 13,เอกชน,กรุงเทพมหานคร,พญาไท,กรุงเทพและปริมณฑล,เปิดตรวจแล้ว,NaN,NaN
512,เอ็นเฮลท์ คลินิกเทคนิคการแพทย์,NaN,"0-2019-9921, 09-8650-6735",NaN,https://www.nhealth-asia.com/th/product/14,เขต 13,เอกชน,กรุงเทพมหานคร,บางแค,กรุงเทพและปริมณฑล,เปิดตรวจแล้ว,NaN,NaN

จากในตารางมีข้อมูลดังนี้

*   orgth = ชื่อห้องปฏิบัติการภาษาไทย
*   orgen = ชื่อห้องปฏิบัติการภาษาอังกฤษ
*   telephone = หมายเลขโทรศัพท์
*   address = ที่อยู่ของห้องปฏิบัติการ
*   website = เว็บไซต์
*   healtharea = เขต
*   agency = หน่วยงาน
*   province = จังหวัด
*   district = อำเภอ
*   area = บริเวณพื้นที่
*   npsts = สถานะ (NPS+TS = การตรวจด้วยตัวอย่างป้ายหลังโพรงจมูก และป้ายลำคอ)
*   pooledsaliva = สถานะ (การตรวจด้วยตัวอย่างน้ำลาย)
*   pooledswab = สถานะ (การตรวจด้วยตัวอย่างในโพรงจมูก

In [167]:
lab.isnull().any()

orgth           False
orgen            True
telephone        True
address          True
website          True
healtharea      False
agency          False
province        False
district         True
area            False
npsts           False
pooledsaliva     True
pooledswab       True
dtype: bool

จากการตรวจสอบพบว่า มี column ที่มีค่า missing คือ

*  orgen            
*  telephone        
*  address          
*  website          
*  district         
*  pooledsaliva     
*  pooledswab

## แทน missing ด้วยค่าที่เหมาะสม (fillna())

In [168]:
lab_clean = lab.fillna(value={'orgen':'ไม่ระบุ','telephone':'ไม่ระบุ','address':'ไม่ระบุ','website':'ไม่ระบุ','district':'ไม่ระบุ','pooledsaliva':'ไม่ระบุ','pooledswab':'ไม่ระบุ'})
lab_clean

,orgth,orgen,telephone,address,website,healtharea,agency,province,district,area,npsts,pooledsaliva,pooledswab
0,ศูนย์วิทยาศาสตร์การแพทย์ที่ 1 เชียงใหม่,Regional Medical Sciences Center 1 Chiang Mai,0-5311-2188-90,191 หมู่ 8 ต.ดอนแก้ว อ.แม่ริม จ.เชียงใหม่ 50180,http://webapp1.dmsc.moph.go.th/cm1/web/post-gr...,เขต 1,ภาครัฐ,เชียงใหม่,แม่ริม,ต่างจังหวัด,เปิดตรวจแล้ว,เปิดตรวจแล้ว,เปิดตรวจแล้ว
1,ศูนย์วิทยาศาสตร์การแพทย์ที่ 1/1 เชียงราย,Regional Medical Sciences Center 1/1 Chiang Rai,0-5317-6224-6,148 หมู่ 3 ตำบลนางแล อำเภอเมือง จังหวัดเชียงรา...,http://cri.dmsc.moph.go.th/,เขต 1,ภาครัฐ,เชียงราย,เมืองเชียงราย,ต่างจังหวัด,เปิดตรวจแล้ว,เปิดตรวจแล้ว,เปิดตรวจแล้ว
2,สำนักงานป้องกันควบคุมโรคที่ 1 เชียงใหม่,The Office of Disease Prevention and Control 1...,0-5314-0774,447 ถนนเชียงใหม่-ลำพูน ตำบลวัดเกต อำเภอเมือง จ...,https://ddc.moph.go.th/odpc1/,เขต 1,ภาครัฐ,เชียงใหม่,เมืองเชียงใหม่,ต่างจังหวัด,เปิดตรวจแล้ว,ไม่ระบุ,เปิดตรวจแล้ว
3,โรงพยาบาลนครพิงค์,Nakornping Hospital,0-5399-9200,159 ม.10 ถ.โชตนา ต.ดอนแก้ว อ.แม่ริม จ.เชียงใหม...,http://www.nkp-hospital.go.th/th/,เขต 1,ภาครัฐ,เชียงใหม่,แม่ริม,ต่างจังหวัด,เปิดตรวจแล้ว,เปิดตรวจแล้ว,เปิดตรวจแล้ว
4,โรงพยาบาลลำปาง,Lampang Hospital,0-5423-7400,28/3 ห้องอณูชีวโมเลกุล กลุ่มงานเทคนิคการแพทย์ ...,http://www.lph.go.th/lpweb/,เขต 1,ภาครัฐ,ลำปาง,เมืองลำปาง,ต่างจังหวัด,เปิดตรวจแล้ว,เปิดตรวจแล้ว,เปิดตรวจแล้ว
...,...,...,...,...,...,...,...,...,...,...,...,...,...
508,งานอณูชีววิทยา โรงพยาบาลราชวิถี,ไม่ระบุ,0-2206-2900 ต่อ 40610-2,ไม่ระบุ,http://www.rajavithi.go.th/rj/medtech/biomolec...,เขต 13,ภาครัฐ,กรุงเทพมหานคร,ราชเทวี,กรุงเทพและปริมณฑล,เปิดตรวจแล้ว,ไม่ระบุ,ไม่ระบุ
509,งานจุลชีววิทยา โรงพยาบาลราชวิถี,ไม่ระบุ,"0-2206-2900 ต่อ 3142, 3143",ไม่ระบุ,http://www.rajavithi.go.th/rj/medtech/microbio...,เขต 13,ภาครัฐ,กรุงเทพมหานคร,ราชเทวี,กรุงเทพและปริมณฑล,เปิดตรวจแล้ว,ไม่ระบุ,ไม่ระบุ
510,โรงพยาบาลประโคนชัย,ไม่ระบุ,0-4467-0103,ไม่ระบุ,https://www.facebook.com/pkchospital,เขต 9,ภาครัฐ,บุรีรัมย์,ประโคนชัย,ต่างจังหวัด,เปิดตรวจแล้ว,ไม่ระบุ,ไม่ระบุ
511,กรุงเทพพยาธิ-แลป คลินิกเทคนิคการแพทย์,ไม่ระบุ,0-2619-2909,ไม่ระบุ,https://www.bpl.co.th/pweb/,เขต 13,เอกชน,กรุงเทพมหานคร,พญาไท,กรุงเทพและปริมณฑล,เปิดตรวจแล้ว,ไม่ระบุ,ไม่ระบุ
512,เอ็นเฮลท์ คลินิกเทคนิคการแพทย์,ไม่ระบุ,"0-2019-9921, 09-8650-6735",ไม่ระบุ,https://www.nhealth-asia.com/th/product/14,เขต 13,เอกชน,กรุงเทพมหานคร,บางแค,กรุงเทพและปริมณฑล,เปิดตรวจแล้ว,ไม่ระบุ,ไม่ระบุ

In [169]:
lab_clean.isnull().any()

orgth           False
orgen           False
telephone       False
address         False
website         False
healtharea      False
agency          False
province        False
district        False
area            False
npsts           False
pooledsaliva    False
pooledswab      False
dtype: bool

จากการเตรียมข้อมูลจะเห็นได้ว่า ข้อมูลรายชื่อห้องปฏิบัติการเครือข่ายตรวจโควิด-19 ไม่มีค่า missing แล้ว

## dropna

In [170]:
#labdrop = pd.read_csv('labscovid19_update080365.csv', encoding="TIS-620") # TIS-620 คือ Decoding ที่เราใช้อ่านจาก file.csv แล้วนำค่ากลับมา Encodingเป็น UTF-8-sig เพื่อให้ตัว microsoft excel ในเครื่องเราที่มีdefault ในการอ่านค่าเป็น utf-8 อ่านได้

In [171]:
#labdrop_clean = labdrop.dropna()
#labdrop_clean

## เลือกมาเฉพาะข้อมูลที่สนใจ

In [225]:
data_lab = lab_clean[['orgth','telephone','address','district','npsts','pooledsaliva','pooledswab','province']]
data_lab

,orgth,telephone,address,district,npsts,pooledsaliva,pooledswab,province
0,ศูนย์วิทยาศาสตร์การแพทย์ที่ 1 เชียงใหม่,0-5311-2188-90,191 หมู่ 8 ต.ดอนแก้ว อ.แม่ริม จ.เชียงใหม่ 50180,แม่ริม,เปิดตรวจแล้ว,เปิดตรวจแล้ว,เปิดตรวจแล้ว,เชียงใหม่
1,ศูนย์วิทยาศาสตร์การแพทย์ที่ 1/1 เชียงราย,0-5317-6224-6,148 หมู่ 3 ตำบลนางแล อำเภอเมือง จังหวัดเชียงรา...,เมืองเชียงราย,เปิดตรวจแล้ว,เปิดตรวจแล้ว,เปิดตรวจแล้ว,เชียงราย
2,สำนักงานป้องกันควบคุมโรคที่ 1 เชียงใหม่,0-5314-0774,447 ถนนเชียงใหม่-ลำพูน ตำบลวัดเกต อำเภอเมือง จ...,เมืองเชียงใหม่,เปิดตรวจแล้ว,ไม่ระบุ,เปิดตรวจแล้ว,เชียงใหม่
3,โรงพยาบาลนครพิงค์,0-5399-9200,159 ม.10 ถ.โชตนา ต.ดอนแก้ว อ.แม่ริม จ.เชียงใหม...,แม่ริม,เปิดตรวจแล้ว,เปิดตรวจแล้ว,เปิดตรวจแล้ว,เชียงใหม่
4,โรงพยาบาลลำปาง,0-5423-7400,28/3 ห้องอณูชีวโมเลกุล กลุ่มงานเทคนิคการแพทย์ ...,เมืองลำปาง,เปิดตรวจแล้ว,เปิดตรวจแล้ว,เปิดตรวจแล้ว,ลำปาง
...,...,...,...,...,...,...,...,...
508,งานอณูชีววิทยา โรงพยาบาลราชวิถี,0-2206-2900 ต่อ 40610-2,ไม่ระบุ,ราชเทวี,เปิดตรวจแล้ว,ไม่ระบุ,ไม่ระบุ,กรุงเทพมหานคร
509,งานจุลชีววิทยา โรงพยาบาลราชวิถี,"0-2206-2900 ต่อ 3142, 3143",ไม่ระบุ,ราชเทวี,เปิดตรวจแล้ว,ไม่ระบุ,ไม่ระบุ,กรุงเทพมหานคร
510,โรงพยาบาลประโคนชัย,0-4467-0103,ไม่ระบุ,ประโคนชัย,เปิดตรวจแล้ว,ไม่ระบุ,ไม่ระบุ,บุรีรัมย์
511,กรุงเทพพยาธิ-แลป คลินิกเทคนิคการแพทย์,0-2619-2909,ไม่ระบุ,พญาไท,เปิดตรวจแล้ว,ไม่ระบุ,ไม่ระบุ,กรุงเทพมหานคร
512,เอ็นเฮลท์ คลินิกเทคนิคการแพทย์,"0-2019-9921, 09-8650-6735",ไม่ระบุ,บางแค,เปิดตรวจแล้ว,ไม่ระบุ,ไม่ระบุ,กรุงเทพมหานคร

### เช็คคำผิดของข้อมูลจังหวัด

In [173]:
set(lab_clean['province'])

{'กระบี่',
 'กรุงเทพมหานคร',
 'กาญจนบุรี',
 'กาฬสินธุ์',
 'กำแพงเพชร',
 'ขอนแก่น',
 'จันทบุรี',
 'ฉะเชิงเทรา',
 'ชลบุรี',
 'ชัยนาท',
 'ชัยภูมิ',
 'ชุมพร',
 'ตรัง',
 'ตราด',
 'ตาก',
 'นครนายก',
 'นครปฐม',
 'นครพนม',
 'นครราชสีมา',
 'นครศรีธรรมราช',
 'นครสวรรค์',
 'นนทบุรี',
 'นราธิวาส',
 'น่าน',
 'บึงกาฬ',
 'บุรีรัมย์',
 'ปทุมธานี',
 'ประจวบคีรีขันธ์',
 'ปราจีนบุรี',
 'ปัตตานี',
 'พระนครศรีอยุธยา',
 'พะเยา',
 'พังงา',
 'พัทลุง',
 'พิจิตร',
 'พิษณุโลก',
 'ภูเก็ต',
 'มหาสารคาม',
 'มุกดาหาร',
 'ยะลา',
 'ยโสธร',
 'ระนอง',
 'ระยอง',
 'ราชบุรี',
 'ร้อยเอ็ด',
 'ลพบุรี',
 'ลำปาง',
 'ลำพูน',
 'ศรีสะเกษ',
 'สกลนคร',
 'สงขลา',
 'สตูล',
 'สมุทรปราการ',
 'สมุทรสงคราม',
 'สมุทรสาคร',
 'สระบุรี',
 'สระแก้ว',
 'สิงห์บุรี',
 'สุพรรณบุรี',
 'สุราษฎร์ธานี',
 'สุรินทร์',
 'สุโขทัย',
 'หนองคาย',
 'หนองบัวลำภู',
 'อำนาจเจริญ',
 'อุดรธานี',
 'อุตรดิตถ์',
 'อุทัยธานี',
 'อุบลราชธานี',
 'อ่างทอง',
 'เชียงราย',
 'เชียงใหม่',
 'เพชรบุรี',
 'เพชรบูรณ์',
 'เลย',
 'แพร่',
 'แม่ฮ่องสอน'}

In [174]:
set(lab_clean['district'])

{'กบินทร์บุรี',
 'กระทุ่มแบน',
 'กระนวน',
 'กระบุรี',
 'กะทู้',
 'กันทรลักษณ์',
 'กาญจนดิษฐ์',
 'กุมภวาปี',
 'ขุขันธ์',
 'ครบุรี',
 'คลองสาน',
 'คลองหลวง',
 'คลองเตย',
 'ควนขนุน',
 'คันนายาว',
 'จตุจักร',
 'จอมทอง',
 'ชัยบาดาล',
 'ชุมแพ',
 'ดุสิต',
 'ด่านช้าง',
 'ตระการพืชผล',
 'ตลิ่งชัน',
 'ตะกั่วป่า',
 'ตากใบ',
 'ถลาง',
 'ทวีวัฒนา',
 'ทุ่งสง',
 'ท่าบ่อ',
 'ท่ามะกา',
 'ท่ายาง',
 'ท่าศาลา',
 'ท่าสองยาง',
 'ธนบุรี',
 'ธัญบุรี',
 'นากลาง',
 'นางรอง',
 'นาทวี',
 'น้ำยืน',
 'บัวใหญ่',
 'บางกรวย',
 'บางกอกน้อย',
 'บางกะปิ',
 'บางขุนเทียน',
 'บางคอแหลม',
 'บางซื่อ',
 'บางนา',
 'บางบอน',
 'บางบัวทอง',
 'บางบ่อ',
 'บางปะกง',
 'บางปะอิน',
 'บางพลัด',
 'บางพลี',
 'บางรัก',
 'บางละมุง',
 'บางสะพาน',
 'บางเขน',
 'บางเสาธง',
 'บางแค',
 'บางใหญ่',
 'บึงกุ่ม',
 'บุณฑริก',
 'บ้านนาสาร',
 'บ้านหมี่',
 'บ้านแพ้ว',
 'บ้านแฮด',
 'บ้านโป่ง',
 'ปทุมวัน',
 'ประเวศ',
 'ประโคนชัย',
 'ปราณบุรี',
 'ปราสาท',
 'ปลวกแดง',
 'ปากช่อง',
 'ปากท่อ',
 'ปากพนัง',
 'ปากเกร็ด',
 'ป้อมปราบศัตรูพ่าย',
 'ฝาง',
 'พญาไท',
 'พบพระ',
 'พระนครศรีอยุธยา',
 'พระประแดง',
 'พระพุทธบาท',
 'พระสมุทรเจดีย์',
 'พระโขนง',
 'พล',
 'พิบูลมังสาหาร',
 'พิมาย',
 'พุทธมณฑล',
 'พุนพิน',
 'ภาษีเจริญ',
 'ภูเขียว',
 'มวกเหล็ก',
 'มีนบุรี',
 'ยะรัง',
 'ยะหา',
 'ยางตลาด',
 'ยานนาวา',
 'ระแงะ',
 'ราชเทวี',
 'รามัน',
 'ลาดพร้าว',
 'ลำปลายมาศ',
 'ลำลูกกา',
 'วังทองหลาง',
 'วังสะพุง',
 'วัฒนา',
 'วานรนิวาส',
 'วารินชำราบ',
 'วิเชียรบุรี',
 'ศรีมหาโพธิ',
 'ศรีรัตนะ',
 'ศรีราชา',
 'ศรีสมเด็จ',
 'ศรีสำโรง',
 'ศีขรภูมิ',
 'สตึก',
 'สมเด็จ',
 'สวนหลวง',
 'สว่างแดนดิน',
 'สองพี่น้อง',
 'สะพานสูง',
 'สัตหีบ',
 'สันกำแพง',
 'สันทราย',
 'สันป่าตอง',
 'สาทร',
 'สามพราน',
 'สายบุรี',
 'สายไหม',
 'สิชล',
 'สุวรรณภูมิ',
 'สุไหงโก-ลก',
 'หนองแขม',
 'หนองแค',
 'หลักสี่',
 'หลังสวน',
 'หัวหิน',
 'หาดใหญ่',
 'ห้วยขวาง',
 'องครักษ์',
 'อรัญประเทศ',
 'อำเภอเมืองหนองคาย',
 'อุทัย',
 'อุทุมพรพิสัย',
 'อุ้มผาง',
 'เกษตรวิสัย',
 'เกาะพะงัน',
 'เกาะสมุย',
 'เขื่องใน',
 'เชียงคาน',
 'เชียงคำ',
 'เซกา',
 'เดชอุดม',
 'เบตง',
 'เมือง',
 'เมืองกระบี่',
 'เมืองกาญจนบุรี',
 'เมืองกาฬสินธุ์',
 'เมืองกำแพงเพชร',
 'เมืองขอนแก่น',
 'เมืองจันทบุรี',
 'เมืองฉะเชิงเทรา',
 'เมืองชลบุรี',
 'เมืองชัยนาท',
 'เมืองชัยภูมิ',
 'เมืองชุมพร',
 'เมืองตรัง',
 'เมืองตราด',
 'เมืองตาก',
 'เมืองนครนายก',
 'เมืองนครปฐม',
 'เมืองนครพนม',
 'เมืองนครราชสีมา',
 'เมืองนครศรีธรรมราช',
 'เมืองนครสวรรค์',
 'เมืองนนทบุรี',
 'เมืองนราธิวาส',
 'เมืองน่าน',
 'เมืองบึงกาฬ',
 'เมืองบุรีรัมย์',
 'เมืองปทุมธานี',
 'เมืองประจวบคีรีขันธ์',
 'เมืองปราจีนบุรี',
 'เมืองปัตตานี',
 'เมืองพะเยา',
 'เมืองพังงา',
 'เมืองพัทลุง',
 'เมืองพิจิตร',
 'เมืองพิษณุโลก',
 'เมืองภูเก็ต',
 'เมืองมหาสารคาม',
 'เมืองมุกดาหาร',
 'เมืองยะลา',
 'เมืองยโสธร',
 'เมืองระนอง',
 'เมืองระยอง',
 'เมืองราชบุรี',
 'เมืองร้อยเอ็ด',
 'เมืองลพบุรี',
 'เมืองลำปาง',
 'เมืองลำพูน',
 'เมืองศรีสะเกษ',
 'เมืองสกลนคร',
 'เมืองสงขลา',
 'เมืองสตูล',
 'เมืองสมุทรปราการ',
 'เมืองสมุทรสงคราม',
 'เมืองสมุทรสาคร',
 'เมืองสระบุรี',
 'เมืองสระแก้ว',
 'เมืองสิงห์บุรี',
 'เมืองสุพรรณบุรี',
 'เมืองสุราษฎร์ธานี',
 'เมืองสุรินทร์',
 'เมืองสุโขทัย',
 'เมืองหนองคาย',
 'เมืองหนองบัวลำภู',
 'เมืองอำนาจเจริญ',
 'เมืองอุดรธานี',
 'เมืองอุตรดิตถ์',
 'เมืองอุทัยธานี',
 'เมืองอุบลราชธานี',
 'เมืองอ่างทอง',
 'เมืองเชียงราย',
 'เมืองเชียงใหม่',
 'เมืองเพชรบุรี',
 'เมืองเพชรบูรณ์',
 'เมืองเลย',
 'เมืองแพร่',
 'เมืองแม่ฮ่องสอน',
 'เวียงสระ',
 'เสนา',
 'แม่ระมาด',
 'แม่ริม',
 'แม่สอด',
 'โคกโพธิ์',
 'โพธาราม',
 'โพนทอง',
 'ไทรน้อย',
 'ไม่ระบุ'}

# รวมตารางข้อมูลจำนวนผู้ติดเชื้อกับข้อมูลห้องLab

## ตารางข้อมูลจำนวนผู้ติดเชื้อช่วงที่ 1 กับข้อมูลห้องLab

In [175]:
data_pro_lab = data_pro001.merge(data_lab,how='left',left_on='district_of_onset',right_on = 'district') 
data_pro_lab

,announce_date,age,risk,province_of_onset,district_of_onset,province,6 ภูมิภาค (ภูมิศาสตร์),orgth,telephone,address,district,npsts,pooledsaliva,pooledswab
0,12/1/2020,61.0,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,ไม่มีข้อมูล,กรุงเทพมหานคร,กลาง,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,17/1/2020,74.0,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,ไม่มีข้อมูล,กรุงเทพมหานคร,กลาง,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,22/1/2020,73.0,คนต่างชาติเดินทางมาจากต่างประเทศ,นครปฐม,เมือง,นครปฐม,กลาง,โรงพยาบาลราชพฤกษ์,0-4333-3555,456 หมู่ 14 ถนนมิตรภาพ ตำบลในเมือง อำเภอเมือง ...,เมือง,เปิดตรวจแล้ว,ไม่ระบุ,ไม่ระบุ
3,22/1/2020,73.0,คนต่างชาติเดินทางมาจากต่างประเทศ,นครปฐม,เมือง,นครปฐม,กลาง,บริษัท เนชั่นแนล เฮลท์แคร์ ซิสเท็มส์ จำกัด สาข...,076298298 ต่อ5111,ไม่ระบุ,เมือง,เปิดตรวจแล้ว,ไม่ระบุ,ไม่ระบุ
4,22/1/2020,68.0,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,ไม่มีข้อมูล,กรุงเทพมหานคร,กลาง,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2034500,12/8/2021,52.0,ทัณฑสถาน/เรือนจำ,กาญจนบุรี,ไม่มีข้อมูล,กาญจนบุรี,ตะวันตก,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2034501,12/8/2021,34.0,ทัณฑสถาน/เรือนจำ,กาญจนบุรี,ไม่มีข้อมูล,กาญจนบุรี,ตะวันตก,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2034502,12/8/2021,31.0,ทัณฑสถาน/เรือนจำ,กาญจนบุรี,ไม่มีข้อมูล,กาญจนบุรี,ตะวันตก,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2034503,12/8/2021,83.0,ทัณฑสถาน/เรือนจำ,กาญจนบุรี,ไม่มีข้อมูล,กาญจนบุรี,ตะวันตก,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2034504,12/8/2021,47.0,ทัณฑสถาน/เรือนจำ,กาญจนบุรี,ไม่มีข้อมูล,กาญจนบุรี,ตะวันตก,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [176]:
data_pro_labdp = data_pro_lab.dropna() 
data_pro_labdp

,announce_date,age,risk,province_of_onset,district_of_onset,province,6 ภูมิภาค (ภูมิศาสตร์),orgth,telephone,address,district,npsts,pooledsaliva,pooledswab
2,22/1/2020,73.0,คนต่างชาติเดินทางมาจากต่างประเทศ,นครปฐม,เมือง,นครปฐม,กลาง,โรงพยาบาลราชพฤกษ์,0-4333-3555,456 หมู่ 14 ถนนมิตรภาพ ตำบลในเมือง อำเภอเมือง ...,เมือง,เปิดตรวจแล้ว,ไม่ระบุ,ไม่ระบุ
3,22/1/2020,73.0,คนต่างชาติเดินทางมาจากต่างประเทศ,นครปฐม,เมือง,นครปฐม,กลาง,บริษัท เนชั่นแนล เฮลท์แคร์ ซิสเท็มส์ จำกัด สาข...,076298298 ต่อ5111,ไม่ระบุ,เมือง,เปิดตรวจแล้ว,ไม่ระบุ,ไม่ระบุ
8,26/1/2020,73.0,คนต่างชาติเดินทางมาจากต่างประเทศ,ประจวบคีรีขันธ์,หัวหิน,ประจวบคีรีขันธ์,ตะวันตก,โรงพยาบาลหัวหิน,0-3252-3000,กลุ่มงานเทคนิคการแพทย์ 30/2 ต.หัวหิน อ.หัวหิน ...,หัวหิน,เปิดตรวจแล้ว,เปิดตรวจแล้ว,เปิดตรวจแล้ว
14,28/1/2020,32.0,คนต่างชาติเดินทางมาจากต่างประเทศ,ภูเก็ต,เมือง,ภูเก็ต,ใต้,โรงพยาบาลราชพฤกษ์,0-4333-3555,456 หมู่ 14 ถนนมิตรภาพ ตำบลในเมือง อำเภอเมือง ...,เมือง,เปิดตรวจแล้ว,ไม่ระบุ,ไม่ระบุ
15,28/1/2020,32.0,คนต่างชาติเดินทางมาจากต่างประเทศ,ภูเก็ต,เมือง,ภูเก็ต,ใต้,บริษัท เนชั่นแนล เฮลท์แคร์ ซิสเท็มส์ จำกัด สาข...,076298298 ต่อ5111,ไม่ระบุ,เมือง,เปิดตรวจแล้ว,ไม่ระบุ,ไม่ระบุ
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2034125,12/8/2021,43.0,ไปสถานที่ชุมชน เช่น ตลาดนัด สถานที่ท่องเที่ยว,กรุงเทพมหานคร,ประเวศ,กรุงเทพมหานคร,กลาง,คลินิกเทคนิคการแพทย์ ฟีนิกซ์ โมเลกุลาร์,080-0064557,ไม่ระบุ,ประเวศ,เปิดตรวจแล้ว,เปิดตรวจแล้ว,เปิดตรวจแล้ว
2034126,12/8/2021,74.0,ไปสถานที่ชุมชน เช่น ตลาดนัด สถานที่ท่องเที่ยว,กรุงเทพมหานคร,ธนบุรี,กรุงเทพมหานคร,กลาง,โรงพยาบาลสมเด็จพระปิ่นเกล้า,0-2460-0000 ต่อ 41592,504 กลุ่มงานพยาธิวิทยา รพ.สมเด็จพระปิ่นเกล้า พ...,ธนบุรี,เปิดตรวจแล้ว,เปิดตรวจแล้ว,เปิดตรวจแล้ว
2034127,12/8/2021,29.0,อาชีพเสี่ยง เช่น ทำงานในสถานที่แออัด หรือทำงาน...,กรุงเทพมหานคร,ประเวศ,กรุงเทพมหานคร,กลาง,โรงพยาบาลสิรินธร,0-2328-6901,20 ซอย อ่อนนุช 90 แขวง ประเวศ เขต ประเวศ กรุงเ...,ประเวศ,เปิดตรวจแล้ว,ไม่ระบุ,ไม่ระบุ
2034128,12/8/2021,29.0,อาชีพเสี่ยง เช่น ทำงานในสถานที่แออัด หรือทำงาน...,กรุงเทพมหานคร,ประเวศ,กรุงเทพมหานคร,กลาง,โรงพยาบาลสินแพทย์ ศรีนครินทร์,0-2006-8888,ไม่ระบุ,ประเวศ,เปิดตรวจแล้ว,ไม่ระบุ,ไม่ระบุ
2034129,12/8/2021,29.0,อาชีพเสี่ยง เช่น ทำงานในสถานที่แออัด หรือทำงาน...,กรุงเทพมหานคร,ประเวศ,กรุงเทพมหานคร,กลาง,คลินิกเทคนิคการแพทย์ ฟีนิกซ์ โมเลกุลาร์,080-0064557,ไม่ระบุ,ประเวศ,เปิดตรวจแล้ว,เปิดตรวจแล้ว,เปิดตรวจแล้ว

In [177]:
data_pro_labdp.shape #ขนาดของตาราง dropna

(1674243, 14)

In [178]:
removes = data_pro_lab.shape[0] - data_pro_labdp.shape[0]
print(f'size before drop = {data_pro_lab.shape[0]}')
print(f'size after drop = {data_pro_labdp.shape[0]}')
print(f'% from drop = {(removes/data_pro_lab.shape[0])*100}')
 #มีข้อมูลที่หายไป 17% ซึ่งสามารถยอมรับได้

size before drop = 2034505
size after drop = 1674243
% from drop = 17.707599637258202

In [179]:
data_pro_labcn = data_pro_lab.fillna(value={'orgth':'ไม่สามารถระบุได้','telephone':'ไม่สามารถระบุได้','address':'ไม่สามารถระบุได้','district':'ไม่สามารถระบุได้','npsts':'ไม่สามารถระบุได้','pooledsaliva':'ไม่สามารถระบุได้','pooledswab':'ไม่สามารถระบุได้'})
data_pro_labcn

,announce_date,age,risk,province_of_onset,district_of_onset,province,6 ภูมิภาค (ภูมิศาสตร์),orgth,telephone,address,district,npsts,pooledsaliva,pooledswab
0,12/1/2020,61.0,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,ไม่มีข้อมูล,กรุงเทพมหานคร,กลาง,ไม่สามารถระบุได้,ไม่สามารถระบุได้,ไม่สามารถระบุได้,ไม่สามารถระบุได้,ไม่สามารถระบุได้,ไม่สามารถระบุได้,ไม่สามารถระบุได้
1,17/1/2020,74.0,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,ไม่มีข้อมูล,กรุงเทพมหานคร,กลาง,ไม่สามารถระบุได้,ไม่สามารถระบุได้,ไม่สามารถระบุได้,ไม่สามารถระบุได้,ไม่สามารถระบุได้,ไม่สามารถระบุได้,ไม่สามารถระบุได้
2,22/1/2020,73.0,คนต่างชาติเดินทางมาจากต่างประเทศ,นครปฐม,เมือง,นครปฐม,กลาง,โรงพยาบาลราชพฤกษ์,0-4333-3555,456 หมู่ 14 ถนนมิตรภาพ ตำบลในเมือง อำเภอเมือง ...,เมือง,เปิดตรวจแล้ว,ไม่ระบุ,ไม่ระบุ
3,22/1/2020,73.0,คนต่างชาติเดินทางมาจากต่างประเทศ,นครปฐม,เมือง,นครปฐม,กลาง,บริษัท เนชั่นแนล เฮลท์แคร์ ซิสเท็มส์ จำกัด สาข...,076298298 ต่อ5111,ไม่ระบุ,เมือง,เปิดตรวจแล้ว,ไม่ระบุ,ไม่ระบุ
4,22/1/2020,68.0,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,ไม่มีข้อมูล,กรุงเทพมหานคร,กลาง,ไม่สามารถระบุได้,ไม่สามารถระบุได้,ไม่สามารถระบุได้,ไม่สามารถระบุได้,ไม่สามารถระบุได้,ไม่สามารถระบุได้,ไม่สามารถระบุได้
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2034500,12/8/2021,52.0,ทัณฑสถาน/เรือนจำ,กาญจนบุรี,ไม่มีข้อมูล,กาญจนบุรี,ตะวันตก,ไม่สามารถระบุได้,ไม่สามารถระบุได้,ไม่สามารถระบุได้,ไม่สามารถระบุได้,ไม่สามารถระบุได้,ไม่สามารถระบุได้,ไม่สามารถระบุได้
2034501,12/8/2021,34.0,ทัณฑสถาน/เรือนจำ,กาญจนบุรี,ไม่มีข้อมูล,กาญจนบุรี,ตะวันตก,ไม่สามารถระบุได้,ไม่สามารถระบุได้,ไม่สามารถระบุได้,ไม่สามารถระบุได้,ไม่สามารถระบุได้,ไม่สามารถระบุได้,ไม่สามารถระบุได้
2034502,12/8/2021,31.0,ทัณฑสถาน/เรือนจำ,กาญจนบุรี,ไม่มีข้อมูล,กาญจนบุรี,ตะวันตก,ไม่สามารถระบุได้,ไม่สามารถระบุได้,ไม่สามารถระบุได้,ไม่สามารถระบุได้,ไม่สามารถระบุได้,ไม่สามารถระบุได้,ไม่สามารถระบุได้
2034503,12/8/2021,83.0,ทัณฑสถาน/เรือนจำ,กาญจนบุรี,ไม่มีข้อมูล,กาญจนบุรี,ตะวันตก,ไม่สามารถระบุได้,ไม่สามารถระบุได้,ไม่สามารถระบุได้,ไม่สามารถระบุได้,ไม่สามารถระบุได้,ไม่สามารถระบุได้,ไม่สามารถระบุได้
2034504,12/8/2021,47.0,ทัณฑสถาน/เรือนจำ,กาญจนบุรี,ไม่มีข้อมูล,กาญจนบุรี,ตะวันตก,ไม่สามารถระบุได้,ไม่สามารถระบุได้,ไม่สามารถระบุได้,ไม่สามารถระบุได้,ไม่สามารถระบุได้,ไม่สามารถระบุได้,ไม่สามารถระบุได้

## ตารางข้อมูลจำนวนผู้ติดเชื้อช่วงที่ 2 กับข้อมูลห้องLab

In [180]:
data_pro_lab2 = data_pro002.merge(data_lab,how='left',left_on='district_of_onset',right_on = 'district') 
data_pro_lab2

,announce_date,age,risk,province_of_onset,district_of_onset,province,6 ภูมิภาค (ภูมิศาสตร์),orgth,telephone,address,district,npsts,pooledsaliva,pooledswab
0,12/8/2021,7.0,อื่นๆ,ไม่มีข้อมูล,ไม่มีข้อมูล,ไม่มีข้อมูล,ไม่มีข้อมูล,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,12/8/2021,1.0,อื่นๆ,ไม่มีข้อมูล,ไม่มีข้อมูล,ไม่มีข้อมูล,ไม่มีข้อมูล,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,12/8/2021,35.0,อื่นๆ,ไม่มีข้อมูล,ไม่มีข้อมูล,ไม่มีข้อมูล,ไม่มีข้อมูล,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,12/8/2021,33.0,อื่นๆ,ไม่มีข้อมูล,ไม่มีข้อมูล,ไม่มีข้อมูล,ไม่มีข้อมูล,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,12/8/2021,14.0,สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้,ไม่มีข้อมูล,ไม่มีข้อมูล,ไม่มีข้อมูล,ไม่มีข้อมูล,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2389516,25/10/2021,45.0,ทัณฑสถาน/เรือนจำ,ไม่มีข้อมูล,ไม่มีข้อมูล,ไม่มีข้อมูล,ไม่มีข้อมูล,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2389517,25/10/2021,31.0,ทัณฑสถาน/เรือนจำ,ไม่มีข้อมูล,ไม่มีข้อมูล,ไม่มีข้อมูล,ไม่มีข้อมูล,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2389518,25/10/2021,31.0,ทัณฑสถาน/เรือนจำ,ไม่มีข้อมูล,ไม่มีข้อมูล,ไม่มีข้อมูล,ไม่มีข้อมูล,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2389519,25/10/2021,24.0,ทัณฑสถาน/เรือนจำ,ไม่มีข้อมูล,ไม่มีข้อมูล,ไม่มีข้อมูล,ไม่มีข้อมูล,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2389520,25/10/2021,25.0,ทัณฑสถาน/เรือนจำ,ไม่มีข้อมูล,ไม่มีข้อมูล,ไม่มีข้อมูล,ไม่มีข้อมูล,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [181]:
data_pro_lab2dp = data_pro_lab2.dropna() 
data_pro_lab2dp

,announce_date,age,risk,province_of_onset,district_of_onset,province,6 ภูมิภาค (ภูมิศาสตร์),orgth,telephone,address,district,npsts,pooledsaliva,pooledswab
249,12/8/2021,48.0,สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้,เพชรบูรณ์,เมืองเพชรบูรณ์,เพชรบูรณ์,กลาง,โรงพยาบาลเพชรบูรณ์,0-5671-7600,203 ถนนสามัคคีชัย อำเภอเมือง จังหวัดเพชรบูรณ์,เมืองเพชรบูรณ์,เปิดตรวจแล้ว,เปิดตรวจแล้ว,เปิดตรวจแล้ว
250,12/8/2021,48.0,สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้,เพชรบูรณ์,เมืองเพชรบูรณ์,เพชรบูรณ์,กลาง,โรงพยาบาลเพชรรัตน์,0-5672-0680,ไม่ระบุ,เมืองเพชรบูรณ์,เปิดตรวจแล้ว,ไม่ระบุ,ไม่ระบุ
251,12/8/2021,19.0,สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้,เพชรบูรณ์,เมืองเพชรบูรณ์,เพชรบูรณ์,กลาง,โรงพยาบาลเพชรบูรณ์,0-5671-7600,203 ถนนสามัคคีชัย อำเภอเมือง จังหวัดเพชรบูรณ์,เมืองเพชรบูรณ์,เปิดตรวจแล้ว,เปิดตรวจแล้ว,เปิดตรวจแล้ว
252,12/8/2021,19.0,สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้,เพชรบูรณ์,เมืองเพชรบูรณ์,เพชรบูรณ์,กลาง,โรงพยาบาลเพชรรัตน์,0-5672-0680,ไม่ระบุ,เมืองเพชรบูรณ์,เปิดตรวจแล้ว,ไม่ระบุ,ไม่ระบุ
253,12/8/2021,37.0,สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้,เพชรบูรณ์,เมืองเพชรบูรณ์,เพชรบูรณ์,กลาง,โรงพยาบาลเพชรบูรณ์,0-5671-7600,203 ถนนสามัคคีชัย อำเภอเมือง จังหวัดเพชรบูรณ์,เมืองเพชรบูรณ์,เปิดตรวจแล้ว,เปิดตรวจแล้ว,เปิดตรวจแล้ว
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2389315,25/10/2021,80.0,อื่นๆ,กรุงเทพมหานคร,สายไหม,กรุงเทพมหานคร,กลาง,โรงพยาบาล บี.แคร์ เมดิคอล เซ็นเตอร์,02-523-3360-71,ไม่ระบุ,สายไหม,เปิดตรวจแล้ว,ไม่ระบุ,ไม่ระบุ
2389316,25/10/2021,67.0,อื่นๆ,กรุงเทพมหานคร,สายไหม,กรุงเทพมหานคร,กลาง,โรงพยาบาลภูมิพลอดุลยเดช,0-2534-7647,ห้องปฏิบัติการจุลชีววิทยา อาคาร14 รพ.ภูมิพลอดุ...,สายไหม,เปิดตรวจแล้ว,ไม่ระบุ,เปิดตรวจแล้ว
2389317,25/10/2021,67.0,อื่นๆ,กรุงเทพมหานคร,สายไหม,กรุงเทพมหานคร,กลาง,โรงพยาบาล บี.แคร์ เมดิคอล เซ็นเตอร์,02-523-3360-71,ไม่ระบุ,สายไหม,เปิดตรวจแล้ว,ไม่ระบุ,ไม่ระบุ
2389318,25/10/2021,53.0,อื่นๆ,กรุงเทพมหานคร,สายไหม,กรุงเทพมหานคร,กลาง,โรงพยาบาลภูมิพลอดุลยเดช,0-2534-7647,ห้องปฏิบัติการจุลชีววิทยา อาคาร14 รพ.ภูมิพลอดุ...,สายไหม,เปิดตรวจแล้ว,ไม่ระบุ,เปิดตรวจแล้ว
2389319,25/10/2021,53.0,อื่นๆ,กรุงเทพมหานคร,สายไหม,กรุงเทพมหานคร,กลาง,โรงพยาบาล บี.แคร์ เมดิคอล เซ็นเตอร์,02-523-3360-71,ไม่ระบุ,สายไหม,เปิดตรวจแล้ว,ไม่ระบุ,ไม่ระบุ

In [182]:
data_pro_lab2dp.shape #ขนาดของตาราง dropna

(1949192, 14)

In [183]:
removes = data_pro_lab2.shape[0] - data_pro_lab2dp.shape[0]
print(f'size before drop = {data_pro_lab2.shape[0]}')
print(f'size after drop = {data_pro_lab2dp.shape[0]}')
print(f'% from drop = {(removes/data_pro_lab2.shape[0])*100}')
 #มีข้อมูลที่หายไป 18% ซึ่งสามารถยอมรับได้

size before drop = 2389521
size after drop = 1949192
% from drop = 18.427500741780463

In [184]:
data_pro_labcn2 = data_pro_lab.fillna(value={'orgth':'ไม่สามารถระบุได้','telephone':'ไม่สามารถระบุได้','address':'ไม่สามารถระบุได้','district':'ไม่สามารถระบุได้','npsts':'ไม่สามารถระบุได้','pooledsaliva':'ไม่สามารถระบุได้','pooledswab':'ไม่สามารถระบุได้'})
data_pro_labcn2

,announce_date,age,risk,province_of_onset,district_of_onset,province,6 ภูมิภาค (ภูมิศาสตร์),orgth,telephone,address,district,npsts,pooledsaliva,pooledswab
0,12/1/2020,61.0,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,ไม่มีข้อมูล,กรุงเทพมหานคร,กลาง,ไม่สามารถระบุได้,ไม่สามารถระบุได้,ไม่สามารถระบุได้,ไม่สามารถระบุได้,ไม่สามารถระบุได้,ไม่สามารถระบุได้,ไม่สามารถระบุได้
1,17/1/2020,74.0,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,ไม่มีข้อมูล,กรุงเทพมหานคร,กลาง,ไม่สามารถระบุได้,ไม่สามารถระบุได้,ไม่สามารถระบุได้,ไม่สามารถระบุได้,ไม่สามารถระบุได้,ไม่สามารถระบุได้,ไม่สามารถระบุได้
2,22/1/2020,73.0,คนต่างชาติเดินทางมาจากต่างประเทศ,นครปฐม,เมือง,นครปฐม,กลาง,โรงพยาบาลราชพฤกษ์,0-4333-3555,456 หมู่ 14 ถนนมิตรภาพ ตำบลในเมือง อำเภอเมือง ...,เมือง,เปิดตรวจแล้ว,ไม่ระบุ,ไม่ระบุ
3,22/1/2020,73.0,คนต่างชาติเดินทางมาจากต่างประเทศ,นครปฐม,เมือง,นครปฐม,กลาง,บริษัท เนชั่นแนล เฮลท์แคร์ ซิสเท็มส์ จำกัด สาข...,076298298 ต่อ5111,ไม่ระบุ,เมือง,เปิดตรวจแล้ว,ไม่ระบุ,ไม่ระบุ
4,22/1/2020,68.0,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,ไม่มีข้อมูล,กรุงเทพมหานคร,กลาง,ไม่สามารถระบุได้,ไม่สามารถระบุได้,ไม่สามารถระบุได้,ไม่สามารถระบุได้,ไม่สามารถระบุได้,ไม่สามารถระบุได้,ไม่สามารถระบุได้
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2034500,12/8/2021,52.0,ทัณฑสถาน/เรือนจำ,กาญจนบุรี,ไม่มีข้อมูล,กาญจนบุรี,ตะวันตก,ไม่สามารถระบุได้,ไม่สามารถระบุได้,ไม่สามารถระบุได้,ไม่สามารถระบุได้,ไม่สามารถระบุได้,ไม่สามารถระบุได้,ไม่สามารถระบุได้
2034501,12/8/2021,34.0,ทัณฑสถาน/เรือนจำ,กาญจนบุรี,ไม่มีข้อมูล,กาญจนบุรี,ตะวันตก,ไม่สามารถระบุได้,ไม่สามารถระบุได้,ไม่สามารถระบุได้,ไม่สามารถระบุได้,ไม่สามารถระบุได้,ไม่สามารถระบุได้,ไม่สามารถระบุได้
2034502,12/8/2021,31.0,ทัณฑสถาน/เรือนจำ,กาญจนบุรี,ไม่มีข้อมูล,กาญจนบุรี,ตะวันตก,ไม่สามารถระบุได้,ไม่สามารถระบุได้,ไม่สามารถระบุได้,ไม่สามารถระบุได้,ไม่สามารถระบุได้,ไม่สามารถระบุได้,ไม่สามารถระบุได้
2034503,12/8/2021,83.0,ทัณฑสถาน/เรือนจำ,กาญจนบุรี,ไม่มีข้อมูล,กาญจนบุรี,ตะวันตก,ไม่สามารถระบุได้,ไม่สามารถระบุได้,ไม่สามารถระบุได้,ไม่สามารถระบุได้,ไม่สามารถระบุได้,ไม่สามารถระบุได้,ไม่สามารถระบุได้
2034504,12/8/2021,47.0,ทัณฑสถาน/เรือนจำ,กาญจนบุรี,ไม่มีข้อมูล,กาญจนบุรี,ตะวันตก,ไม่สามารถระบุได้,ไม่สามารถระบุได้,ไม่สามารถระบุได้,ไม่สามารถระบุได้,ไม่สามารถระบุได้,ไม่สามารถระบุได้,ไม่สามารถระบุได้

## ตารางข้อมูลจำนวนผู้ติดเชื้อช่วงที่ 3 กับข้อมูลห้องLab

In [185]:
data_pro_lab3 = data_pro003.merge(data_lab,how='left',left_on='district_of_onset',right_on = 'district') 
data_pro_lab3

,announce_date,age,risk,province_of_onset,district_of_onset,province,6 ภูมิภาค (ภูมิศาสตร์),orgth,telephone,address,district,npsts,pooledsaliva,pooledswab
0,26/10/2021,20.0,อื่นๆ,ลำปาง,เมืองลำปาง,ลำปาง,เหนือ,โรงพยาบาลลำปาง,0-5423-7400,28/3 ห้องอณูชีวโมเลกุล กลุ่มงานเทคนิคการแพทย์ ...,เมืองลำปาง,เปิดตรวจแล้ว,เปิดตรวจแล้ว,เปิดตรวจแล้ว
1,26/10/2021,20.0,อื่นๆ,ลำปาง,เมืองลำปาง,ลำปาง,เหนือ,โรงพยาบาลเขลางค์นคร-ราม ลำปาง,0-5401-9619,ห้องปฏิบัติการโรงพยาบาลเขลางค์นครราม 79/12 ถ.พ...,เมืองลำปาง,เปิดตรวจแล้ว,ไม่ระบุ,เปิดตรวจแล้ว
2,26/10/2021,20.0,อื่นๆ,ลำปาง,เมืองลำปาง,ลำปาง,เหนือ,โรงพยาบาลมะเร็งลำปาง,0-5433-5262-8,199 ถ. ลำปาง-งาว ตำบลพิชัย อำเภอเมือง จังหวัดล...,เมืองลำปาง,เปิดตรวจแล้ว,ไม่ระบุ,ไม่ระบุ
3,26/10/2021,20.0,อื่นๆ,ลำปาง,เมืองลำปาง,ลำปาง,เหนือ,เซ็นทรัลแล็บกรุ๊ป คลินิกเทคนิคการแพทย์,ไม่ระบุ,655/19-20 ถนนไฮเวย์-ลำปาง-งาว ตำบล หัวเวียง อำ...,เมืองลำปาง,เปิดตรวจแล้ว,ไม่ระบุ,ไม่ระบุ
4,26/10/2021,42.0,อื่นๆ,ลำปาง,เมืองลำปาง,ลำปาง,เหนือ,โรงพยาบาลลำปาง,0-5423-7400,28/3 ห้องอณูชีวโมเลกุล กลุ่มงานเทคนิคการแพทย์ ...,เมืองลำปาง,เปิดตรวจแล้ว,เปิดตรวจแล้ว,เปิดตรวจแล้ว
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2356223,27/2/2022,ปี,ทัณฑสถาน/เรือนจำ,ไม่มีข้อมูล,ไม่มีข้อมูล,ไม่มีข้อมูล,ไม่มีข้อมูล,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2356224,27/2/2022,ปี,ทัณฑสถาน/เรือนจำ,ไม่มีข้อมูล,ไม่มีข้อมูล,ไม่มีข้อมูล,ไม่มีข้อมูล,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2356225,27/2/2022,ปี,ทัณฑสถาน/เรือนจำ,ไม่มีข้อมูล,ไม่มีข้อมูล,ไม่มีข้อมูล,ไม่มีข้อมูล,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2356226,27/2/2022,ปี,ทัณฑสถาน/เรือนจำ,ไม่มีข้อมูล,ไม่มีข้อมูล,ไม่มีข้อมูล,ไม่มีข้อมูล,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2356227,27/2/2022,ปี,ทัณฑสถาน/เรือนจำ,ไม่มีข้อมูล,ไม่มีข้อมูล,ไม่มีข้อมูล,ไม่มีข้อมูล,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [186]:
data_pro_lab3dp = data_pro_lab3.dropna() 
data_pro_lab3dp

,announce_date,age,risk,province_of_onset,district_of_onset,province,6 ภูมิภาค (ภูมิศาสตร์),orgth,telephone,address,district,npsts,pooledsaliva,pooledswab
0,26/10/2021,20.0,อื่นๆ,ลำปาง,เมืองลำปาง,ลำปาง,เหนือ,โรงพยาบาลลำปาง,0-5423-7400,28/3 ห้องอณูชีวโมเลกุล กลุ่มงานเทคนิคการแพทย์ ...,เมืองลำปาง,เปิดตรวจแล้ว,เปิดตรวจแล้ว,เปิดตรวจแล้ว
1,26/10/2021,20.0,อื่นๆ,ลำปาง,เมืองลำปาง,ลำปาง,เหนือ,โรงพยาบาลเขลางค์นคร-ราม ลำปาง,0-5401-9619,ห้องปฏิบัติการโรงพยาบาลเขลางค์นครราม 79/12 ถ.พ...,เมืองลำปาง,เปิดตรวจแล้ว,ไม่ระบุ,เปิดตรวจแล้ว
2,26/10/2021,20.0,อื่นๆ,ลำปาง,เมืองลำปาง,ลำปาง,เหนือ,โรงพยาบาลมะเร็งลำปาง,0-5433-5262-8,199 ถ. ลำปาง-งาว ตำบลพิชัย อำเภอเมือง จังหวัดล...,เมืองลำปาง,เปิดตรวจแล้ว,ไม่ระบุ,ไม่ระบุ
3,26/10/2021,20.0,อื่นๆ,ลำปาง,เมืองลำปาง,ลำปาง,เหนือ,เซ็นทรัลแล็บกรุ๊ป คลินิกเทคนิคการแพทย์,ไม่ระบุ,655/19-20 ถนนไฮเวย์-ลำปาง-งาว ตำบล หัวเวียง อำ...,เมืองลำปาง,เปิดตรวจแล้ว,ไม่ระบุ,ไม่ระบุ
4,26/10/2021,42.0,อื่นๆ,ลำปาง,เมืองลำปาง,ลำปาง,เหนือ,โรงพยาบาลลำปาง,0-5423-7400,28/3 ห้องอณูชีวโมเลกุล กลุ่มงานเทคนิคการแพทย์ ...,เมืองลำปาง,เปิดตรวจแล้ว,เปิดตรวจแล้ว,เปิดตรวจแล้ว
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2356139,27/2/2022,64.0,อื่นๆ,กรุงเทพมหานคร,ราชเทวี,กรุงเทพมหานคร,กลาง,คลินิกเทคนิคการแพทย์ กรุงเทพจีโนม,0-2034-1544,39 ถนน พญาไท แขวง ถนนพญาไท เขตราชเทวี กรุงเทพม...,ราชเทวี,เปิดตรวจแล้ว,ไม่ระบุ,ไม่ระบุ
2356140,27/2/2022,64.0,อื่นๆ,กรุงเทพมหานคร,ราชเทวี,กรุงเทพมหานคร,กลาง,สถาบันมะเร็งแห่งชาติ,02 202 6800,ไม่ระบุ,ราชเทวี,เปิดตรวจแล้ว,ไม่ระบุ,ไม่ระบุ
2356141,27/2/2022,64.0,อื่นๆ,กรุงเทพมหานคร,ราชเทวี,กรุงเทพมหานคร,กลาง,บริษัท เนชั่นแนล เฮลท์แคร์ ซิสเท็มส์ จำกัด สาข...,0-2201-4600,ไม่ระบุ,ราชเทวี,เปิดตรวจแล้ว,ไม่ระบุ,ไม่ระบุ
2356142,27/2/2022,64.0,อื่นๆ,กรุงเทพมหานคร,ราชเทวี,กรุงเทพมหานคร,กลาง,งานอณูชีววิทยา โรงพยาบาลราชวิถี,0-2206-2900 ต่อ 40610-2,ไม่ระบุ,ราชเทวี,เปิดตรวจแล้ว,ไม่ระบุ,ไม่ระบุ
2356143,27/2/2022,64.0,อื่นๆ,กรุงเทพมหานคร,ราชเทวี,กรุงเทพมหานคร,กลาง,งานจุลชีววิทยา โรงพยาบาลราชวิถี,"0-2206-2900 ต่อ 3142, 3143",ไม่ระบุ,ราชเทวี,เปิดตรวจแล้ว,ไม่ระบุ,ไม่ระบุ

In [187]:
data_pro_lab2dp.shape #ขนาดของตาราง dropna

(1949192, 14)

In [188]:
removes = data_pro_lab3.shape[0] - data_pro_lab3dp.shape[0]
print(f'size before drop = {data_pro_lab3.shape[0]}')
print(f'size after drop = {data_pro_lab3dp.shape[0]}')
print(f'% from drop = {(removes/data_pro_lab3.shape[0])*100}')
 #มีข้อมูลที่หายไป 18% ซึ่งสามารถยอมรับได้

size before drop = 2356228
size after drop = 1922044
% from drop = 18.427079213047296

In [189]:
data_pro_labcn3 = data_pro_lab.fillna(value={'orgth':'ไม่สามารถระบุได้','telephone':'ไม่สามารถระบุได้','address':'ไม่สามารถระบุได้','district':'ไม่สามารถระบุได้','npsts':'ไม่สามารถระบุได้','pooledsaliva':'ไม่สามารถระบุได้','pooledswab':'ไม่สามารถระบุได้'})
data_pro_labcn3

,announce_date,age,risk,province_of_onset,district_of_onset,province,6 ภูมิภาค (ภูมิศาสตร์),orgth,telephone,address,district,npsts,pooledsaliva,pooledswab
0,12/1/2020,61.0,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,ไม่มีข้อมูล,กรุงเทพมหานคร,กลาง,ไม่สามารถระบุได้,ไม่สามารถระบุได้,ไม่สามารถระบุได้,ไม่สามารถระบุได้,ไม่สามารถระบุได้,ไม่สามารถระบุได้,ไม่สามารถระบุได้
1,17/1/2020,74.0,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,ไม่มีข้อมูล,กรุงเทพมหานคร,กลาง,ไม่สามารถระบุได้,ไม่สามารถระบุได้,ไม่สามารถระบุได้,ไม่สามารถระบุได้,ไม่สามารถระบุได้,ไม่สามารถระบุได้,ไม่สามารถระบุได้
2,22/1/2020,73.0,คนต่างชาติเดินทางมาจากต่างประเทศ,นครปฐม,เมือง,นครปฐม,กลาง,โรงพยาบาลราชพฤกษ์,0-4333-3555,456 หมู่ 14 ถนนมิตรภาพ ตำบลในเมือง อำเภอเมือง ...,เมือง,เปิดตรวจแล้ว,ไม่ระบุ,ไม่ระบุ
3,22/1/2020,73.0,คนต่างชาติเดินทางมาจากต่างประเทศ,นครปฐม,เมือง,นครปฐม,กลาง,บริษัท เนชั่นแนล เฮลท์แคร์ ซิสเท็มส์ จำกัด สาข...,076298298 ต่อ5111,ไม่ระบุ,เมือง,เปิดตรวจแล้ว,ไม่ระบุ,ไม่ระบุ
4,22/1/2020,68.0,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,ไม่มีข้อมูล,กรุงเทพมหานคร,กลาง,ไม่สามารถระบุได้,ไม่สามารถระบุได้,ไม่สามารถระบุได้,ไม่สามารถระบุได้,ไม่สามารถระบุได้,ไม่สามารถระบุได้,ไม่สามารถระบุได้
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2034500,12/8/2021,52.0,ทัณฑสถาน/เรือนจำ,กาญจนบุรี,ไม่มีข้อมูล,กาญจนบุรี,ตะวันตก,ไม่สามารถระบุได้,ไม่สามารถระบุได้,ไม่สามารถระบุได้,ไม่สามารถระบุได้,ไม่สามารถระบุได้,ไม่สามารถระบุได้,ไม่สามารถระบุได้
2034501,12/8/2021,34.0,ทัณฑสถาน/เรือนจำ,กาญจนบุรี,ไม่มีข้อมูล,กาญจนบุรี,ตะวันตก,ไม่สามารถระบุได้,ไม่สามารถระบุได้,ไม่สามารถระบุได้,ไม่สามารถระบุได้,ไม่สามารถระบุได้,ไม่สามารถระบุได้,ไม่สามารถระบุได้
2034502,12/8/2021,31.0,ทัณฑสถาน/เรือนจำ,กาญจนบุรี,ไม่มีข้อมูล,กาญจนบุรี,ตะวันตก,ไม่สามารถระบุได้,ไม่สามารถระบุได้,ไม่สามารถระบุได้,ไม่สามารถระบุได้,ไม่สามารถระบุได้,ไม่สามารถระบุได้,ไม่สามารถระบุได้
2034503,12/8/2021,83.0,ทัณฑสถาน/เรือนจำ,กาญจนบุรี,ไม่มีข้อมูล,กาญจนบุรี,ตะวันตก,ไม่สามารถระบุได้,ไม่สามารถระบุได้,ไม่สามารถระบุได้,ไม่สามารถระบุได้,ไม่สามารถระบุได้,ไม่สามารถระบุได้,ไม่สามารถระบุได้
2034504,12/8/2021,47.0,ทัณฑสถาน/เรือนจำ,กาญจนบุรี,ไม่มีข้อมูล,กาญจนบุรี,ตะวันตก,ไม่สามารถระบุได้,ไม่สามารถระบุได้,ไม่สามารถระบุได้,ไม่สามารถระบุได้,ไม่สามารถระบุได้,ไม่สามารถระบุได้,ไม่สามารถระบุได้

## ตารางข้อมูลจำนวนผู้ติดเชื้อช่วงที่ 4 กับข้อมูลห้องLab

In [190]:
data_pro_lab4 = data_pro004.merge(data_lab,how='left',left_on='district_of_onset',right_on = 'district') 
data_pro_lab4

,announce_date,age,risk,province_of_onset,district_of_onset,province,6 ภูมิภาค (ภูมิศาสตร์),orgth,telephone,address,district,npsts,pooledsaliva,pooledswab
0,28/2/2022,41.000000,สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้,พะเยา,เมืองพะเยา,พะเยา,เหนือ,โรงพยาบาลพะเยา,0-5440-9300,269 ถ. พหลโยธิน ต.บ้านต๋อม อ.เมือง จ.พะเยา 56000,เมืองพะเยา,เปิดตรวจแล้ว,ไม่ระบุ,เปิดตรวจแล้ว
1,28/2/2022,41.000000,สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้,พะเยา,เมืองพะเยา,พะเยา,เหนือ,โรงพยาบาลพะเยาราม,0-5441-1111\r\n,660 หมู่ 3 ตำบล ท่าวังทอง อำเภอ เมือง จังหวัด ...,เมืองพะเยา,เปิดตรวจแล้ว,เปิดตรวจแล้ว,เปิดตรวจแล้ว
2,28/2/2022,45.000000,สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้,พะเยา,เมืองพะเยา,พะเยา,เหนือ,โรงพยาบาลพะเยา,0-5440-9300,269 ถ. พหลโยธิน ต.บ้านต๋อม อ.เมือง จ.พะเยา 56000,เมืองพะเยา,เปิดตรวจแล้ว,ไม่ระบุ,เปิดตรวจแล้ว
3,28/2/2022,45.000000,สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้,พะเยา,เมืองพะเยา,พะเยา,เหนือ,โรงพยาบาลพะเยาราม,0-5441-1111\r\n,660 หมู่ 3 ตำบล ท่าวังทอง อำเภอ เมือง จังหวัด ...,เมืองพะเยา,เปิดตรวจแล้ว,เปิดตรวจแล้ว,เปิดตรวจแล้ว
4,28/2/2022,40.000000,สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้,พะเยา,เมืองพะเยา,พะเยา,เหนือ,โรงพยาบาลพะเยา,0-5440-9300,269 ถ. พหลโยธิน ต.บ้านต๋อม อ.เมือง จ.พะเยา 56000,เมืองพะเยา,เปิดตรวจแล้ว,ไม่ระบุ,เปิดตรวจแล้ว
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
792016,15/3/2022,36.943725,ทัณฑสถาน/เรือนจำ,ไม่มีข้อมูล,ไม่มีข้อมูล,ไม่มีข้อมูล,ไม่มีข้อมูล,NaN,NaN,NaN,NaN,NaN,NaN,NaN
792017,15/3/2022,36.943725,ทัณฑสถาน/เรือนจำ,ไม่มีข้อมูล,ไม่มีข้อมูล,ไม่มีข้อมูล,ไม่มีข้อมูล,NaN,NaN,NaN,NaN,NaN,NaN,NaN
792018,15/3/2022,36.943725,ทัณฑสถาน/เรือนจำ,ไม่มีข้อมูล,ไม่มีข้อมูล,ไม่มีข้อมูล,ไม่มีข้อมูล,NaN,NaN,NaN,NaN,NaN,NaN,NaN
792019,15/3/2022,36.943725,ทัณฑสถาน/เรือนจำ,ไม่มีข้อมูล,ไม่มีข้อมูล,ไม่มีข้อมูล,ไม่มีข้อมูล,NaN,NaN,NaN,NaN,NaN,NaN,NaN
792020,15/3/2022,36.943725,ทัณฑสถาน/เรือนจำ,ไม่มีข้อมูล,ไม่มีข้อมูล,ไม่มีข้อมูล,ไม่มีข้อมูล,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [191]:
data_pro_lab4.isnull().any()

announce_date             False
age                       False
risk                      False
province_of_onset         False
district_of_onset         False
province                  False
6 ภูมิภาค (ภูมิศาสตร์)    False
orgth                      True
telephone                  True
address                    True
district                   True
npsts                      True
pooledsaliva               True
pooledswab                 True
dtype: bool

In [192]:
data_pro_lab4dp = data_pro_lab4.dropna() 
data_pro_lab4dp

,announce_date,age,risk,province_of_onset,district_of_onset,province,6 ภูมิภาค (ภูมิศาสตร์),orgth,telephone,address,district,npsts,pooledsaliva,pooledswab
0,28/2/2022,41.0,สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้,พะเยา,เมืองพะเยา,พะเยา,เหนือ,โรงพยาบาลพะเยา,0-5440-9300,269 ถ. พหลโยธิน ต.บ้านต๋อม อ.เมือง จ.พะเยา 56000,เมืองพะเยา,เปิดตรวจแล้ว,ไม่ระบุ,เปิดตรวจแล้ว
1,28/2/2022,41.0,สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้,พะเยา,เมืองพะเยา,พะเยา,เหนือ,โรงพยาบาลพะเยาราม,0-5441-1111\r\n,660 หมู่ 3 ตำบล ท่าวังทอง อำเภอ เมือง จังหวัด ...,เมืองพะเยา,เปิดตรวจแล้ว,เปิดตรวจแล้ว,เปิดตรวจแล้ว
2,28/2/2022,45.0,สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้,พะเยา,เมืองพะเยา,พะเยา,เหนือ,โรงพยาบาลพะเยา,0-5440-9300,269 ถ. พหลโยธิน ต.บ้านต๋อม อ.เมือง จ.พะเยา 56000,เมืองพะเยา,เปิดตรวจแล้ว,ไม่ระบุ,เปิดตรวจแล้ว
3,28/2/2022,45.0,สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้,พะเยา,เมืองพะเยา,พะเยา,เหนือ,โรงพยาบาลพะเยาราม,0-5441-1111\r\n,660 หมู่ 3 ตำบล ท่าวังทอง อำเภอ เมือง จังหวัด ...,เมืองพะเยา,เปิดตรวจแล้ว,เปิดตรวจแล้ว,เปิดตรวจแล้ว
4,28/2/2022,40.0,สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้,พะเยา,เมืองพะเยา,พะเยา,เหนือ,โรงพยาบาลพะเยา,0-5440-9300,269 ถ. พหลโยธิน ต.บ้านต๋อม อ.เมือง จ.พะเยา 56000,เมืองพะเยา,เปิดตรวจแล้ว,ไม่ระบุ,เปิดตรวจแล้ว
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
791962,15/3/2022,46.0,อื่นๆ,กรุงเทพมหานคร,ห้วยขวาง,กรุงเทพมหานคร,กลาง,โรงพยาบาลพระรามเก้า,0-2202-9999 ต่อ 11710-11712,โรงพยาบาลพระรามเก้า เลขที่ 99 ถ.พระรามเก้า บาง...,ห้วยขวาง,เปิดตรวจแล้ว,ไม่ระบุ,ไม่ระบุ
791963,15/3/2022,46.0,อื่นๆ,กรุงเทพมหานคร,ห้วยขวาง,กรุงเทพมหานคร,กลาง,MIC Lab (บริษัทเมดิคอล อินโนเวชัน เซ็นเตอร์ จำ...,0-2101-6345,เลขที่ 7 ซอยจัดสรร ถนนสุทธิสารวินิจฉัย แขวงสาม...,ห้วยขวาง,เปิดตรวจแล้ว,ไม่ระบุ,เปิดตรวจแล้ว
791964,15/3/2022,46.0,อื่นๆ,กรุงเทพมหานคร,ห้วยขวาง,กรุงเทพมหานคร,กลาง,โรงพยาบาลปิยะเวท,0-2129-5555,โรงพยาบาลปิยะเวท 998 ถนนริมคลองสามเสน แขวงบางะ...,ห้วยขวาง,เปิดตรวจแล้ว,ไม่ระบุ,ไม่ระบุ
791965,15/3/2022,46.0,อื่นๆ,กรุงเทพมหานคร,ห้วยขวาง,กรุงเทพมหานคร,กลาง,บริษัทเนชั่นแนล เฮลท์แคร์ ซิสเท็มส์ จำกัด สาขา...,0-2467-1111 ต่อ 3284,2301/2 ถนน เพชรบุรีตัดใหม่ แขวง บางกะปิ เขตห้ว...,ห้วยขวาง,เปิดตรวจแล้ว,ไม่ระบุ,ไม่ระบุ
791966,15/3/2022,46.0,อื่นๆ,กรุงเทพมหานคร,ห้วยขวาง,กรุงเทพมหานคร,กลาง,โรงพยาบาลเพชรเวช,1390,"2469/13,15 ถ.เพชรบุรีตัดใหม่ ระหว่างแยก เอกมัย...",ห้วยขวาง,เปิดตรวจแล้ว,ไม่ระบุ,ไม่ระบุ

In [193]:
data_pro_lab4dp.shape #ขนาดของตาราง dropna

(645469, 14)

In [194]:
removes = data_pro_lab4.shape[0] - data_pro_lab4dp.shape[0]
print(f'size before drop = {data_pro_lab4.shape[0]}')
print(f'size after drop = {data_pro_lab4dp.shape[0]}')
print(f'% from drop = {(removes/data_pro_lab4.shape[0])*100}')
 #มีข้อมูลที่หายไป 18% ซึ่งสามารถยอมรับได้

size before drop = 792021
size after drop = 645469
% from drop = 18.503549779614428

In [195]:
data_pro_labcn4 = data_pro_lab4.fillna(value={'orgth':'ไม่สามารถระบุได้','telephone':'ไม่สามารถระบุได้','address':'ไม่สามารถระบุได้','district':'ไม่สามารถระบุได้','npsts':'ไม่สามารถระบุได้','pooledsaliva':'ไม่สามารถระบุได้','pooledswab':'ไม่สามารถระบุได้'})
data_pro_labcn4

,announce_date,age,risk,province_of_onset,district_of_onset,province,6 ภูมิภาค (ภูมิศาสตร์),orgth,telephone,address,district,npsts,pooledsaliva,pooledswab
0,28/2/2022,41.000000,สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้,พะเยา,เมืองพะเยา,พะเยา,เหนือ,โรงพยาบาลพะเยา,0-5440-9300,269 ถ. พหลโยธิน ต.บ้านต๋อม อ.เมือง จ.พะเยา 56000,เมืองพะเยา,เปิดตรวจแล้ว,ไม่ระบุ,เปิดตรวจแล้ว
1,28/2/2022,41.000000,สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้,พะเยา,เมืองพะเยา,พะเยา,เหนือ,โรงพยาบาลพะเยาราม,0-5441-1111\r\n,660 หมู่ 3 ตำบล ท่าวังทอง อำเภอ เมือง จังหวัด ...,เมืองพะเยา,เปิดตรวจแล้ว,เปิดตรวจแล้ว,เปิดตรวจแล้ว
2,28/2/2022,45.000000,สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้,พะเยา,เมืองพะเยา,พะเยา,เหนือ,โรงพยาบาลพะเยา,0-5440-9300,269 ถ. พหลโยธิน ต.บ้านต๋อม อ.เมือง จ.พะเยา 56000,เมืองพะเยา,เปิดตรวจแล้ว,ไม่ระบุ,เปิดตรวจแล้ว
3,28/2/2022,45.000000,สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้,พะเยา,เมืองพะเยา,พะเยา,เหนือ,โรงพยาบาลพะเยาราม,0-5441-1111\r\n,660 หมู่ 3 ตำบล ท่าวังทอง อำเภอ เมือง จังหวัด ...,เมืองพะเยา,เปิดตรวจแล้ว,เปิดตรวจแล้ว,เปิดตรวจแล้ว
4,28/2/2022,40.000000,สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้,พะเยา,เมืองพะเยา,พะเยา,เหนือ,โรงพยาบาลพะเยา,0-5440-9300,269 ถ. พหลโยธิน ต.บ้านต๋อม อ.เมือง จ.พะเยา 56000,เมืองพะเยา,เปิดตรวจแล้ว,ไม่ระบุ,เปิดตรวจแล้ว
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
792016,15/3/2022,36.943725,ทัณฑสถาน/เรือนจำ,ไม่มีข้อมูล,ไม่มีข้อมูล,ไม่มีข้อมูล,ไม่มีข้อมูล,ไม่สามารถระบุได้,ไม่สามารถระบุได้,ไม่สามารถระบุได้,ไม่สามารถระบุได้,ไม่สามารถระบุได้,ไม่สามารถระบุได้,ไม่สามารถระบุได้
792017,15/3/2022,36.943725,ทัณฑสถาน/เรือนจำ,ไม่มีข้อมูล,ไม่มีข้อมูล,ไม่มีข้อมูล,ไม่มีข้อมูล,ไม่สามารถระบุได้,ไม่สามารถระบุได้,ไม่สามารถระบุได้,ไม่สามารถระบุได้,ไม่สามารถระบุได้,ไม่สามารถระบุได้,ไม่สามารถระบุได้
792018,15/3/2022,36.943725,ทัณฑสถาน/เรือนจำ,ไม่มีข้อมูล,ไม่มีข้อมูล,ไม่มีข้อมูล,ไม่มีข้อมูล,ไม่สามารถระบุได้,ไม่สามารถระบุได้,ไม่สามารถระบุได้,ไม่สามารถระบุได้,ไม่สามารถระบุได้,ไม่สามารถระบุได้,ไม่สามารถระบุได้
792019,15/3/2022,36.943725,ทัณฑสถาน/เรือนจำ,ไม่มีข้อมูล,ไม่มีข้อมูล,ไม่มีข้อมูล,ไม่มีข้อมูล,ไม่สามารถระบุได้,ไม่สามารถระบุได้,ไม่สามารถระบุได้,ไม่สามารถระบุได้,ไม่สามารถระบุได้,ไม่สามารถระบุได้,ไม่สามารถระบุได้
792020,15/3/2022,36.943725,ทัณฑสถาน/เรือนจำ,ไม่มีข้อมูล,ไม่มีข้อมูล,ไม่มีข้อมูล,ไม่มีข้อมูล,ไม่สามารถระบุได้,ไม่สามารถระบุได้,ไม่สามารถระบุได้,ไม่สามารถระบุได้,ไม่สามารถระบุได้,ไม่สามารถระบุได้,ไม่สามารถระบุได้

In [196]:
data_pro_labcn.to_csv('data01.csv', encoding='utf-8')

In [197]:
data_pro_labcn2.to_csv('data02.csv', encoding='utf-8')

In [198]:
data_pro_labcn3.to_csv('data03.csv', encoding='utf-8')

In [199]:
data_pro_labcn4.to_csv('data04.csv', encoding='utf-8')

In [200]:
data_pro_labcn4.to_csv('data_pro_labcn4.csv')

In [201]:
#case_pro_lab = data1234.merge(data_lab,how='left',left_on='province_of_onset',right_on = 'province') 
#case_pro_lab

In [202]:
##case_pro_labdp.to_csv('Project_otter.csv', encoding='utf-8')

# ลอง

In [203]:
data1234.head()

,announce_date,age,risk,province_of_onset,district_of_onset
0,12/1/2020,61.0,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,ไม่มีข้อมูล
1,17/1/2020,74.0,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,ไม่มีข้อมูล
2,22/1/2020,73.0,คนต่างชาติเดินทางมาจากต่างประเทศ,นครปฐม,เมือง
3,22/1/2020,68.0,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,ไม่มีข้อมูล
4,24/1/2020,66.0,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,ไม่มีข้อมูล

In [204]:
dist = data1234.groupby('district_of_onset')['risk'].count()

In [205]:
dist_df = pd.DataFrame(dist)
dist_noindex = dist_df.reset_index()
dist_noindex

     district_of_onset  risk
0                          3
1                เมือง     2
2                #REF!    26
3      (พิชัย) วังน้อย     1
4                    -   242
...                ...   ...
6169           ้บานไผ่     1
6170            ้เมือง     1
6171   ้เมืองเพชรบูรณ์     1
6172         ​ปลวกแดง​     1
6173       ​วังทองหลาง     7

[6174 rows x 2 columns]

In [206]:
set(data1234['district_of_onset'])

{'มโนรมณ์',
 'หอพักไทยฟู้ดส์',
 'กระทุ่มแบน',
 'สุวรรคูหา',
 'ท่ามะกาท่ามะก่า',
 'พญำไท',
 'บาพลี',
 'ยานาวา',
 'สุไหงโกหลก',
 'โคกโพธิ์ขัย',
 'คลองสา',
 'หนอง่มวง',
 'ไม่มี',
 'บ้านเเหลม',
 'มหาสารคาม',
 'คลองวสาน',
 'สนามชัตเขต',
 'ปากเพลียว',
 'ร่อ',
 'กันทรักษ์',
 'เขตคุสิต',
 'แม่ริม',
 'บ้านด่านลายหอย',
 'เขตบางรัก',
 'หนองแก',
 'ศรีมหาโภชน์',
 'ดอนสาร',
 'สำโรงใหม่',
 'ตะกั่ั่วทุ่ง',
 'ปลงกแดง',
 'ทับเที่ยง',
 'เยือน',
 'เขต มีนบุรี',
 'วัดดอน',
 'สวนแตง',
 'เชียรใหญ่',
 'บ้านผืือ',
 'ภููกามยาว',
 'อ.บ้านโป่ง  จ.ราชบุรี',
 'ราษฎร์บุรณะ',
 'ไม่ระบุ',
 'ทุ่งทองท่าม่วง',
 'สอง',
 'รัตนวาปี',
 'บ่อพลอย',
 'สีคิ้ิ้ว',
 'ปางปะอิน',
 'บางบัวทออง',
 'หนองหญ้า',
 'พระนคศรีอยุธยา',
 'จอมบึง',
 'บ้านแยง',
 'พระราม8',
 'เมืองระยองระยอง',
 'หว้านใหญ่',
 'ยนครชัยศรี',
 'แม่กลอง',
 'ธำมรงค์',
 'ตะกั่วป่า',
 'ลาดแก้วหลุด',
 'ทุ่่งฝน',
 'พธาราม',
 'อ.จะแนะ',
 'กมลาไสย',
 'ทุ่่าสองยาง',
 'ศรีรัตะ',
 'ศรีประจันทร์',
 'คันยาว',
 'สหัสขันธุ์์',
 'ทับไทร',
 'ลำลูกกา ปทุม',
 'บางนรัก',
 'บึงสามัคคี จ.กำแพงเพชร',
 'ทับช้าง',
 'ห้วยยาบ',
 'ป่าคลอก',
 'แขวงมักกะสัน',
 'พนมทวน',
 'อ.ปากเกร็ด   จ.นนทบุรี',
 'มวกหล็ก',
 'ดอนตููม',
 'เมืองปทุมธานี ปทุมธานี',
 'ม.บูรพา',
 'บ้านโป้ง',
 'นาเกลือบางละมุง',
 'ลาดหุมแก้ว',
 'สุไหหงโกลก',
 'เกาะศาลพระ',
 'ปากพลี',
 'สุขุมวิท 50',
 'บางกอกใหญ',
 'ปลวกแดง',
 'สมเด็จ',
 'หนองแขน',
 'คำบ่อ',
 'สระพัฒนา',
 'พิสัย',
 'เมืองสตูล จ.สตูล',
 'ปะตง',
 'กองดิน',
 'ตะโหนด',
 'บางเค็ม',
 'อ.เชียรใหญ่',
 'ประดิพัทธ์',
 'คลงท่อม',
 'วัดโสมนัส',
 'สาภี',
 'บางใบไม้',
 'ทับผึ้ง',
 'พระประแดง',
 'ตะกั่วทุุ่่ง',
 'ทุ่งโพ',
 'ปลวกแดง\u200b',
 'เมืืองหนองคาย',
 'ประทุมวัน',
 'ท้ายเหมือง',
 'ศีรราชา',
 '-เลือกอำเภอ-',
 'โคกโพธื',
 'น่าน',
 'นตรไทย',
 'กรุงเทพมหานคร./พิษณุโลก',
 'สมุทรสงคราม',
 'กะทูู้้',
 'ฉลุง',
 'ขันเงิน',
 'บ้านดง',
 'คำม่่วง',
 'เทศบาลเมืองสระบุรี',
 'บวงพลี',
 'แม่แมะ',
 'เมืองนครฐม',
 'บางพึ่ง',
 'เขตบางแหลม',
 'พระประแดงจ.สมุทรปราการ',
 'บางน้ำจืด',
 'เขต คันนายาว',
 'ทรายกองดินใต้',
 'คููเมือง',
 'หนองหาน',
 'ปาดเกร็ด',
 'อ.เขตป้อมปราบศัตรูพ่าย',
 'คันน่ย่ว',
 'กระทุ่มแดง',
 'บ้านแพร้ว',
 'พระปรแดง',
 'บางเดื่อ',
 'พนมสาร',
 'ลุ่มระวี',
 'องค์รักษ์',
 'บ้านพร้าว',
 'โพธารม',
 'บรรพตพิศัย',
 'สิงเกา',
 'ผักให่',
 'อำแพง',
 'กันทรวิชัย',
 'วัดเนีย',
 'ควนเนียง',
 'ศรีประจัน',
 'บงาเขน',
 'ภูาษีเจริญ',
 'เทพสถิต',
 'บางพลี\t',
 'พนม',
 'อ.จอมบึง จ. ราชบุรี',
 'ทท่ามะกา',
 'บางบบ่',
 'จัทรเกษม',
 'บ้านตาขุุุน',
 'แขวงประเวศ',
 'ลำสนธิ',
 'บางปูใหม่',
 'แก่น',
 'สากเหล็ก',
 'ตุสัต',
 'บ้านด่่านลานหอย',
 'เขื่องใน',
 'บางศรีทอง',
 'เลิงนกทา',
 'ทุงครุ',
 'เมืองฉะเชิเทรา',
 'ปากคลองตลาด',
 'นิคมน้ำอูน',
 'แพรกษา',
 'มือง',
 'ปััว',
 'เมืืองพังงา',
 'เคียบชา',
 'หนองแซม',
 'ซ่าหลวง',
 'แสนทอง',
 'พุนฟิน',
 'กันททรลักษ์',
 'ลาดพพร้าว',
 'ด่านขุนทด',
 'บางมะำร้าว',
 'ปทุมราชวงศษ',
 'เวียงหนองล่อง',
 'พระราม6',
 'กัลยาณิวัฒนา',
 'เขตดอกไม้',
 'บางยี่ขัน',
 'ปากข่อง',
 'ลาดกรัง',
 'รพช.รัตนวาปี',
 'หนองแค',
 'หนองใหญ่',
 'กิ่งอำเภอจังหาร',
 'ถนนขาด',
 '\xa0บ้านไร่',
 'บ้านหนุน',
 'หนอกจอก',
 'บางคลองแหลม',
 'หงษ์เจริญ',
 'เสนา',
 'สนามชัยเขต',
 'รำมะสัก',
 'ท่าสะอ้าน',
 'เมืองสุมทรปราการ',
 'ฝาง',
 'ตลาด',
 'สว่างอารมย์',
 'บางคอแหลง',
 'ท่าใหม่\xa0',
 'โคกสลุง',
 'ตะพานหิน',
 'ทั่าฉาง',
 'ทุุ่่งหัวช้าง',
 'โนนาแดง',
 'สองแคว',
 'บ้านแผ้ว',
 'บึง',
 'จตุจกร',
 'ตม.',
 'อ.บางใหญ่ จ.อยุธยา',
 'อุดมสุข ชอย19',
 'มาบยาพร',
 'สรรพยา',
 'บางกะปิิ',
 'ตคลองเตย',
 'กุยุบรี',
 'อ้อมน้อย',
 'หัวยยอด',
 'นำ้พอง',
 'เขต บางกะปิ',
 'เขาสวนกวาง',
 'กัณทนรวิชัย',
 'เขตคลองเตย',
 'ขามทะเลสอ',
 'บางสมัคร',
 'บัวน้อย',
 'หนองบัวใต้',
 'ท่าคอย',
 'พูทธมณฑล',
 'วัดป่า',
 'สะพานสุง',
 'รัตภูมิ จ. สงขลา',
 'บากกอใหญ่',
 'บาวใหญ่',
 'อุุทัย',
 'บ้านไพร',
 'ฝั่งธนบุรี',
 'บางขุนเมียน',
 'มายยอ',
 'ราชพฤกษ์',
 'ทุ่งเสลี่ยม',
 'บ่อกระดาน',
 'ปลายพระยา จ.กระบี่',
 'หัััวหิน',
 'หลังสวร',
 'ห้วยพันท้าย',
 'ปากเกร็ดจ.นนทบุรี',
 'บันนังสตา',
 'แม่จัน เชียงราย',
 'แพนกษา',
 'กุมวาปี',
 'กระทุุ่่มแบน',
 'เชียงของ',
 'ศรีีเชีียงใหม่',
 'วังน้ำเย็น',
 'ค่าบุรฉัตร',
 'ห้วยจรเข้',
 'เขตสพานสูง',
 'กระทุ่มลาย',
 'บป',
 'บางกะป',
 'ราษฏร์บุูรณะ',
 'เขาคิชกุฏ',
 'ครบุรี',
 'มะชาม',
 'สามงาม',
 'อ.ไพรบึง',
 'รพช.เฝ้าไร่',
 'เขตประเวศน์',
 'บางชิอ',
 'ยี่หอ',
 'สุวรรณภูมิิ',
 'บ้านช่างหล่อ',
 'คลางสาน',
 'เมิองนนทบุรี',
 'บ้านกาศ',
 'ละเเม',
 'ปากเกล็ด',
 'ธันยบุรี',
 'บางละมุน',
 'คลองสามวา',
 'กุุดข้าวปุ้น',
 'กุดข้าวปุน',
 'พระโนง',
 'บ้างระกำ',
 'ยาหา',
 'ปลวกแดเง',
 'ทุ่งครุ่',
 'ศรีสาคร',
 'กมลไสย',
 'กุดชุม',
 'สัมผัสผู้ป่วยยืนยัน COVID21',
 'ศรีมหาโคตร',
 'บาวงละมุง',
 'โขงเจียม',
 'กุฉฺนารายณ์',
 'บ้านใหม่ชัยพัจน์',
 'นิคมคำสร้อย',
 'โนนสังข์',
 'กินอำเภอนาเดิม',
 'ห้วยขวง',
 'เกาะันทร์',
 'ดอนมะโนรา',
 'สุุไหงโกลก',
 'พระนครเหนือ',
 'เมืองนครสวรรค์',
 'บางกรวบ',
 'รพ.กันทรารมย์',
 'หนองทรายขาว',
 'ทรายขาว',
 'สุวรณภูมิ',
 'ด้านซ้าย',
 'ราษฎรบูรณะ',
 'กิ่งอำเภอบางเสาธง',
 'มะเขือแจ้',
 'ลากกระบัง',
 'บ้านแพ้้ว',
 'น้ำทอง',
 'หััวไทร',
 'อ.เมืองนครศรีธรรมราช',
 'เจริญศฺลป์',
 'เบ็ญจลักษณ์',
 'ลำปายมาศ',
 'กิ่งอำเภอชุมตาบง',
 'หินปัก',
 'กะรน',
 'โคกสำเริง',
 'ปมุมวัน',
 'กุยบุุรี',
 'บางพลีัด',
 'พระขโหนง',
 'ศรีบรรพต',
 'ปิ่นเกล้า',
 'ลอง',
 'เกตรวิสัย',
 'เทพกษัตรี',
 'เกษตรสมบูรณ์ จ.ชัยภูมิ',
 'ประเวศร์',
 'ปทุมรัตต์์',
 'ท่าไม้',
 'หวาย',
 'กันทะเทศ',
 'พลับเพลา',
 'ส้มพันธวงศ์',
 'บ้านโพธิ์',
 'อรัญญิก',
 'อ.นครชัยศรีจ.นครปฐม',
 'ท่าแซะ',
 'บ่อหลวง',
 'หนองบัวเเดง',
 'วังน้ำเขียว',
 'โปร่งน้ำร้อน',
 'นาคูณใหญ่',
 'กระนวน',
 'ร่อนพิบูลย์\n',
 'บางกระทุ่ม จ .พิาณุโลก',
 'จ.นครปฐม',
 'หนองแขง',
 'ปรเวศ',
 'กิ่งอำเภอพนมดงรัก',
 'ห้วยตพ',
 'ปักธงชัย',
 'เขวา',
 'โพธฺชัย',
 'ทุ่งนุ้ย',
 'บางแสน',
 'ทองผาภุมิ',
 'ท่าหิน',
 'บึงโขงโหลง',
 'กิ่งอำเภอสามร้อยยอด',
 'บ้านต้อน',
 'ปลอกแดง',
 'รพ.สนาม',
 'อ.บ้านโป่งจ.ราชบุรี',
 'ถาวรพัฒนา',
 'โคกโพธ์',
 'การอน',
 'แก่งคอย',
 'จ.อยุธยา',
 'เมือง\u200bราชบุรี',
 'โกสุมพิิสัย',
 'นาโพธิ์',
 'เมือนครปฐม',
 'คลองสน',
 'สัมพันธวงธ์',
 'ประยี่',
 'เมืองนนบุรี',
 'บางขุนเทีย',
 'กิ่งอำเภอฆ้องชัย',
 'ธาร',
 'หิรัญรูจี',
 'หนองหญ้าไทร',
 'พหลโยธน',
 'ศรีสมเด็ก',
 'บางพลีใหม่',
 'บ้านแพ',
 'เขาสมิง',
 'กเกร็ด',
 'หนองบันแดง',
 'วังแดง',
 'ป้อมปราบศัตรุพ่าย',
 'รัชโยธิน',
 'ธััญญบุรี',
 'ป่าพลู',
 'มืองตรัง',
 'อำเภอนาเยีย',
 'คลองสองต้นนุ่น',
 'เมืองสมทุรสาคร',
 'อ.อุทุมพรพิสัย จ.ศรีสะเกษ',
 'บางจอมทอง',
 'ลาดกะบือ',
 'จะนะ',
 '.เมืองชลบุรี',
 'บ้านกอกน้อย',
 'บ้านบ่อ',
 'บางน้ำเปรี้ยว',
 'สะพานหิน',
 'อ.ลาดหลุมแก้วจ.ปทุมธานี',
 'บางนาค',
 'บางปะจัน',
 'บางบอน กรุงเทพมหานคร',
 'ต. บางกระดี จ.ปทุมธานี',
 'สุวารี',
 'บางอพ',
 'รัตนภูมิ',
 'สรรพาวุธ',
 'นคาชัยศรี',
 'บางเสาธรง',
 '้บานไผ่',
 'บางเลน นครปฐม',
 'ท่ามะเขือ',
 'ชาณุวรลักษบุรี',
 'เมือวสมุทรสาคร',
 'หัวเวียง',
 'บางพราน',
 'หนองบางพลู',
 'มันจาคีรี',
 'ชมแพ',
 'บ้านถิ่น',
 'คลองถ่อม',
 'กาเยาะมาตี',
 'คันนายาว',
 'ท่าขี้เหล็ก',
 'ประจักษ์ศิลปาคม',
 'ขาณุวงลักษณ์',
 'แปลงยาวว',
 'เกษตรสมบูรณ์',
 'ทุ่งเสลียม',
 'พิปูน/เชียงราย',
 'พลับพาชัย',
 'ตาลโกน',
 'ยะหรั่ง',
 'กิ่งอำเภอเมืองยาง',
 'บางระกำ',
 'นางแดดบุ่ง',
 'บ้้านนาเดิม',
 'ทุ่งพลุ',
 'วังน้อน',
 'ชำสูง',
 'ทุ่งครุ้',
 'เรือนจำจังหวัดอ่างทอง',
 'นาหัวบ่อ',
 'เขาชนกัน',
 'สะพาานสูง',
 'พนมมวน',
 'ห้าฉัตร',
 'ประเวศประเวศ',
 'กิ่งอำเภอชื่นชม',
 'วังทอง',
 'เมืองสมุทรสงครามฯ',
 'ดินแง',
 'ศรีเทพ',
 'ชนะสงคราม',
 'ปัตตานี',
 'ดอนพุทรา',
 'ขุขันธิ์',
 'อ.กันทรวิชัย',
 'ห้วยขวาง 10310',
 'วังน้อย',
 'บ่อสุพรรณ',
 'วังสมหมอ',
 'นาจะหลวย',
 'โซ่',
 'บ้านนเดิม',
 'โพธิ์ศรีสุวรรณ',
 'ร่องคำ',
 'บางแพ',
 'เมืืองเลย',
 'เขตราชเทวี',
 'รพช.ศรีเชียงใหม่',
 'ลำำลูกกา',
 'ชัยบุรี',
 '-',
 'สุโขทัย',
 'พระพรหม',
 'เพีย',
 'กกโก',
 'บาวแค',
 'นครชัยศรีษะ',
 'คีีรีรัฐนิคม',
 'ท่่าคันโท',
 'โคกภู',
 'นาบอน',
 'กุดดินจี่',
 'คลองมหานาค',
 'บางเเค',
 'สรรคบุรี',
 'บ้านบุง',
 'เมืองชุมพร',
 'ศรีณรงค์',
 'หลักสาม',
 'เสลภูมิ',
 'เขตบางกะปิ',
 'เมืองมุกดาหาร',
 'ศรีมโสสถ',
 'บำแพงแสน',
 'ดอนเจดีย์ สุพรรณบุรี',
 '3 โนนสัง',
 'เชีียรใหญ่',
 'อ.เมือง จ.นครราชสีมา',
 'ยีงอ',
 'กิ่งอําเภอศรีนครินทร',
 'มายอ',
 'ปราณบุรีี',
 'ลาดพร้าว31',
 'สองพี่น้อง',
 'หนองกุวศรี',
 'เมืองพะเยา',
 'ปากพนัง',
 'เมืองสิงห์บุรี',
 'เขต ลาดพร้าว',
 'แขวงพระโขนง',
 'พระโต๊ะ',
 'กุดบาก',
 'ปราณบุุรี',
 'นบพิดำ',
 'ฆ้องชัย',
 'โพนทาอง',
 'จ. นนทบุรี',
 'โนนค้อ',
 'พรหรมบุรี',
 'สุจสำราญ',
 'ปทุมวัน',
 'ปะนาเระ\n',
 'บ้านโตก',
 'สรีราชา',
 'สรรคบุรี จ.ชัยนาท',
 'สันป่าตอง',
 'แม่สาย',
 'เชียงใหม่',
 'มหาชนะชัย',
 'หนองใหย่',
 'ท่ากระดาน',
 'ต้นเปา',
 'ปรีดีพนมยงค์',
 'ศรีมหาโพพธิ',
 'บางคอแอหลม',
 'ปางมะค่า',
 'บาองกอกใหญ่',
 'คอลงสาน',
 'เมืองอุดรธานี',
 'เขตบาง',
 'อ.แม่จัน จ.เชียงราย',
 'จัตุจักร',
 'เมืองศรีษะเกษ',
 'บางบำหรุ',
 'คลองตำหรุ',
 'เมืองสมุทสาคร',
 'แม่ฃาน้อย',
 'หนองขุ่นใหญ่',
 'มันบุรี',
 'บ่อพลับ',
 'กท.',
 'บ้านนาเดิม',
 'เขตหนองเเขม',
 'เมืองสระบุรี',
 'HOME ISOLATION',
 'สามชุม',
 'ท่าระหัด',
 'สูงเม่น',
 'ดอนมูล',
 'สุรศักดิ์',
 'ลำลูกกา ',
 'เสริมงาม',
 'ท่าศาลา',
 'เมยวดี',
 'คลองหลอง',
 'มะข้ามเตี้ย',
 'พนมทมวน',
 'ทุ่่งช้าง',
 'ถูเพียง',
 '10.อื่นๆ',
 'บานทอง',
 'ดอยตูม',
 'บางขนเทียน',
 'เถิน',
 'ศรีณรงค์\\กิ่ง',
 'บึ่งกลุ่ม',
 'เรณูใต้',
 'ดินทอง',
 'วัง',
 'คลองหนึ่ง',
 'พรมพิราม',
 'อ.ทองผาภูมิ',
 'ดอนเมือน',
 'ยางตลาด',
 'บ้านด่าน',
 'ยางกอกน้อย',
 'ฟากท่่า',
 'บางเขย',
 'ชานุพาน',
 'เมืองชลบุรี \t',
 'พระบาทนาสิงห์',
 'หองจิก',
 'ชานุมมาน',
 'สัันติสุข',
 'ธัญญะ',
 'ท่าแชะ',
 'ธุนบุรี',
 'ป่าติว',
 'กาญจนบุรี',
 'ปากช่่อง',
 'สามง่ามท่าโบสถ์',
 'บางซ่อ',
 'ป้อมปราม',
 'กาญจนดิษย์',
 'รัษฎา',
 'นาแห้ว',
 'หัวไทร',
 'ปรวกแดง',
 'ธาตุเชิงชุม',
 'บางซื่่อ',
 'เคลองเตย',
 'บางน้ำเปริ้ยว',
 'สูงเม่่น',
 'โคกสูง',
 'หวายเหนียว',
 'เมืองนครพนม',
 'บางพาศรี',
 'คลองสิบ',
 'แกลง',
 'นะหริ่ง',
 '\xa0บ้านสร้าง',
 'คลองสามสา',
 'อ.อุทัย',
 'เมืองจัน',
 'โซ่่พิสัย',
 'ตลุก',
 'คำเขื่อนก้ว',
 'เขต ทวีวัฒนา',
 'อ.เขาย้อย จ.เพชรบุรี',
 'พระสมุุทรเจดีย์',
 'วังน้ำขาว',
 'กุดดู่',
 'ภููผาม่าน',
 'สมเด็็จ',
 'เก่ากลอย',
 'วังม่วงสัทธรรม',
 'นาดินดำ',
 'แขวงลาดกระบัง',
 'บางค้อ',
 'ชะอวด นครศรีฯ',
 'สะพานสููง',
 'ตลิงชัน',
 'คลองหล',
 'พรมหมบุรี',
 'นาคูน',
 'ยางหล่อ',
 'วังทอง จ.พิษรุโลก',
 'พรายกระต่าย',
 'บางบังทอง',
 'ุถลาง',
 'ตำรวจ สน.วัดพระยาไกร กรุงเทพมหานคร',
 'จันทเกษม',
 'พรรคนิคม',
 'อ.จุฬาภรณ์',
 'ท่่าแซะ',
 'หนองลุมพุก',
 'เมืองบุุรีรัมย์',
 'บางเขน',
 'นาขา',
 'คลองน้ำไหล',
 'เขตสัมพันธ์ กรุงเทพมหานคร',
 'ชมแดน',
 'ขุขขันธ์',
 'สารภี',
 'กิ่งอำเภอเขวาสินรินทร์',
 'แปลยาว',
 'เมืองอุุตดิตถ์',
 'ตากฟ้า',
 'เบญจรักษ์',
 'เมือง สกลนคร',
 'ไม่่ระบุ',
 'ในเวียง',
 'รับมารักษาจาก ตจว.',
 'สุรวงศ์',
 'เขาน้อย',
 'กุสุุมาลย์',
 'บ้านนนาสาร',
 'ลุมพินี',
 'รพ.แหลมสิงห์',
 'บางเลย',
 'เมืองนครนาย ก',
 'สามร้้อยยอด',
 'ยางราก',
 'อ.เมือง จ.นครศรีธรรมราช',
 'สองพี่น้อง จ.สุพรรณบุรี',
 'หลํกสอง',
 'สมรักษ์ นานอก',
 'เมืิอง',
 'เมืองสุรินทร์',
 'กระทุมแบน',
 '\xa0กบินทร์บุรี',
 'บ้้านตาขุน',
 'รัตภูมิิ',
 'ด่านมะขามเตี้ย',
 'นิคร',
 'จันทรเกษม  จตุจักร',
 'โป่งตาลอง',
 'ศิลาดาน',
 'แม่่จัน',
 'มาจากพื้นที่เสี่ยง',
 'วชิรพยาบาล',
 'ปากตะโก',
 'บ่อไร',
 'สุขสำราญ',
 'สุไหงปาดี',
 'โพหัก',
 'จตุจัตร',
 'สันติสุข',
 'งบ้านฉาง',
 'โคกพระเจดีย์',
 'พรานกระต่าง',
 'บางแวก',
 'ลานบ่า',
 'เมืองนครศรีฯ',
 'อ.วัดสิงห์ จ.ชัยนาท',
 'บึงกุ่ม',
 'วังกระโจม',
 'พญา',
 'บ้านโพธ์',
 'บึ่งกุ้ม',
 'อ.พนมทวน',
 'ศรีวิลาศ มามี',
 'กระทุ้มแบน',
 'ท่าช้าง',
 'เฉลิิมพระเกียรติ',
 'น้ำผุด',
 'หนองแชม',
 'ทาวน์อินทรวน์',
 'ดอนไผ่',
 'แม่่สอด',
 'เมืองพิษณุุโลก',
 'คลองหาด',
 'ศรีสะคะ',
 'สังคม',
 'น้ำเกลี้ยง',
 'บ้างขุนเทียน',
 'กรง\u200bปินัง',
 'บางแก้ว',
 'เชีียงม่วน',
 'เมืองตาก',
 'บางกอกใหญ่่',
 'บางปลา',
 'หาดใหย่',
 'พิปูน',
 'ภูเก็ต',
 'หนองพังค่า',
 'บางก้าน',
 'บางวบัวทอง',
 'บบางเสาธง',
 'ทับสะแก',
 'นาขาม',
 'โพิ์ทอง',
 'เมืองชลบุุรี',
 'ราษฎร์บูรณะ',
 'เมืองสกล',
 'เมืองฉะเชิงเทรา\u200e',
 'งามวงศ์งาน',
 'เมืองนริวาส',
 'กรุงเทพมหานคร.',
 'กุดป่อง',
 'สัตหีบ.',
 '13.อื่นๆ',
 'พนมทวน\xa0',
 'วัดธาตุ',
 'สะเนียน',
 'วังโป่่ง',
 'เชียงแสน',
 'หนองวััวซอ',
 'นอกเขต',
 'ปง',
 'ซับใหญ่',
 'เมืองเมืองชลบุรี',
 'เมืองนครศรีธรรมราข',
 'ทองผาภูมิ',
 'พระเเสง',
 'ขุนยวม',
 'คลองบางโฉลง',
 'ชัยนารายณ์',
 'ภูเพียง',
 'ลานดอกไม้',
 'เมืองสมุุทรปราการ',
 'เขตบางนา',
 'ร้อยกวาง',
 'เมืองจันทรบุรี',
 'บางโพงพงาง',
 'พุทธมนฑล',
 'ศรีรัตนะ',
 'จำปาสัก',
 'นนบุรี',
 "วังทอ'หลาง",
 'คลองสามวา กรุงเทพมหานคร',
 'ุพุนพิน',
 'บางงกะปิ',
 'ราชบูรณะ',
 'ต้อวัง',
 'เขตลาดกระบัง',
 'พุนพิิน',
 'บุ่งกุ่ม',
 'ทุ่งครู',
 'แม่่ระมาด',
 'วังบาล',
 'บ้้านไผ่',
 'สัมพันธวงศ์',
 'ยางตวาด',
 'ตลองใหญ่',
 'คอลงเตย',
 'เมืองปราจีนบุรี',
 'เมืืองตาก',
 'สมอเรียง',
 'กระทุ่มเบน',
 'เมืองพิศณุโลก',
 'วังจันทรี',
 'โพธิ์ตรุ',
 'เขตพระประแดง',
 'บ้านเเพ้ว',
 'ราษฏ์บูรณะ',
 'บันนังสตา\xa0',
 'น้ำร้อน',
 'บ้านโคก',
 'ท้ายเหมือง จ.พังงา',
 'หัวหิิน',
 'กุดจับ',
 'เมืองอุุตรดิตถ์',
 'รพ.ยี่งอ',
 'ขอนหาด',
 'วานรนิิวาส',
 'นาวา',
 'ตาดสุม',
 'ปากพยูน',
 'บาเจาะ',
 'อ.เมืองภูเก็ต',
 'ฃุมแสง',
 'พระแท่น',
 'ปาเกร็ด',
 'นาอ้อ',
 'ค้าขาย ที่บ้าน',
 'ลบางบัวทอง',
 'ขี้เหล็ก',
 'ทุ่งขวาง',
 'จำปาหล่อ',
 'พระปฐมเจดีย์',
 'อ.เมือง จ.สงขลา',
 'ปลวกหแดง',
 'บ้านโอ่ง',
 'กระบวน',
 'ธนบยุรี',
 'บางสีทอง',
 'บังนาราง',
 'ท่าเกษม',
 'เมืองสตล',
 '\u200bวังทองหลาง',
 'ทุุ่งใหญ่',
 'ท่าเลา',
 'กลักสี่',
 'นางนา',
 'พงษ์',
 'ดอนแฝก',
 'สมุุทรสาคร',
 'อ.สามร้อยยอด',
 'วังทรายพูล',
 'แก้งสนามนาง',
 'มะขามเตี้ย',
 'ปากช่อง',
 'เมืองจันทร์',
 'แปดริ้ว',
 'สามพราน จนครปฐม',
 'หนองกอมเกาะ',
 'เขาสามยอด',
 'ทุ่งเข้าหลวง',
 'เชียงขอม',
 'ดสิต',
 'เคหะร่มเกล้า',
 'โคกกลอย',
 'แขวงวังบูรพา',
 'บางขุนไทร',
 'บ้านอิฐ',
 'ศรีวิิไล',
 'กบินทร์',
 'จตรพักตรพิมาน',
 'ดงมูลเหล็ก',
 'พัฒนานคร',
 'ห้วยย้ง',
 'ปากเกร็็ด',
 'ลาดกระบ้ง',
 'ดินแ',
 'แม่เเตง',
 'สระพัง',
 'แม่พริก',
 'สี่แยกมหานาค ตสิต',
 'พระยืน',
 'สี่แยกมหานาค',
 'หังสวน',
 'ภูกระดึง',
 'เชียงแแสน',
 'นาคูู',
 'เมืองลำพููน',
 'สร้อยทอง',
 'สองคลอง',
 'เพชรบูรณ์',
 'นาทม',
 'จรเข้เผือก',
 'อ.เมือง จ.เพชรบุรี',
 'พระราม8 ',
 'เมืองสกลนคร',
 'ไทรโยค',
 'อำเพระนครศรีอยุธยา',
 'ทุ่งวัดดอน',
 'ครบุุรี',
 'ทุ่าอุเทน',
 'เทียนทะเล',
 'สรรบุรี',
 'บ้างบัวทอง',
 'เมืองนครศรีธรรมราช',
 'คลองหก',
 'บางโพงพาง',
 'ด่านเมืองเตี้ย',
 'บางะกง',
 'เขตลบางนา',
 'บ้านอ่าย',
 'หนองหิิน',
 'กิ่งอ.แม่เปิน',
 'บางประอินทร์',
 'ไผ่ใหญ่',
 'หงาว',
 'เสาให้',
 'ห้วยเม๊ก',
 'สำโรงใต้',
 'หนองยาง',
 'เว',
 'ทวีวัฒน์',
 'อ.แม่ฟ้าหลวง',
 'วาปัปทุม',
 'พระพุทรบาท',
 'เที่ยงแท้',
 'หนองจาก',
 'เขตทุ่งครู',
 'ห้วยขว้าง',
 'สาคู',
 'บาโงสะโต',
 'เขาสวนกลาง',
 'บางพลัก',
 'บ้านดู่',
 'กันทรมย์',
 'เมืองนครนายกสมุทรสาคร',
 'บ้างพลี',
 'เก้าเลี้ยง',
 'รับราชการ',
 'ปรางกู่ค์',
 'อ.เมือง จ.ราชบุรี',
 'อ.กระทุ่มแบนจ.สมุทรสาคร',
 'ห้วยยางโทน',
 'อ่าวลึก',
 ...}

In [207]:
data1234['district_of_onset'].replace({'กิงอำเภอชัยบุรี':'อำเภอชัยบุรี','บ้านฝาง\n':'บ้านฝาง','-':'ไม่มีข้อมูล', 'อำเภอศรีราชา':'ศรีราชา','\xa0ประจันตคาม':'ประจันตคาม','บ่างกะปิ':'บางกะปิ','บางละมุง.':'บางละมุง',
 'ท่าศาลา/ปทุมธานี':'ท่าศาลา','วังโป่ง เพชรบูรณ์':'เมืองเพชรบูรณ์','คบองเตย':'คลองเตย', 'นตรไทย':'เมืองพิษณุโลก',
 'แพรกษา':'เมืองสมุทรปราการ', 'อ.หนองแขม กรุงเทพมหานคร.':'หนองแขม',  'รพ.น้ำหนาว':'เมืองเพชรบูรณ์',
 'ตลิ่งชีน':'ตลิ่งชัน', 'เมืองปทุมธานี\xa0':'เมืองปทุมธานี', 'ปลวดเเดง':'ปลวกเเดง', 'เขต ทวีวัฒนา':'ทวีวัฒนา',
 'ชุุมพลบุรี':'เมืองสุรินทร์', 'เขตปทุมวัน':'ปทุมวัน', 'วังกระโจม':'เมืองนครนายก', 'ค่ายบางระจัน':'เมืองสิงห์บุรี',
 'ด่านมะขามเตี้ย กาญจนบุรี':'เมืองกาญจนบุรี', 'บางเสาร์ธง':'บางเสาธง', 'ตลองหลวง':'คลองหลวง',
 'วััดหลวง':'วัดหลวง', 'เมืืองอุดรธานี':'เมืองอุดรธานี', 'พระโขนง กรุงเทพมหานคร':'พระโขนง',
 'ศีราชา':'ศรีราชา', 'บาง เสาธง':'บางเสาธง', 'ราษฏร์ลูรณะ':'ราษฎร์บูรณะ', 'สัามพราย':'สามพราน',
 'นครศรีธรรมราช':'เมืองนครศรีธรรมราช', 'พระโขนง\u200b':'พระโขนง', 'คอลเตย':'คลองเตย',
 'หันนายาว':'คันนายาว', 'ท่าปลา (พิชัย)':'ท่าปลา', 'ลำพยา':'เมืองนครปฐม', 'ต้าผามอก':'ลอง',
 'กำแพงแสน นฐ':'กำแพงแสน', 'เมืองสมุทรปราากร':'เมืองสมุทรปราการ', 'สาบยใหม่':'สายไหม',
 'กัณฑรลักษณ์':'กันทรลักษณ์', 'ลลาดหลุมแก้ว':'ลาดหลุมแก้ว', '2สองพี่น้อง':'สองพี่น้อง',
 'เมืองสมุทรสาค':'เมืองสมุทรสาคร', 'เขตบางกะปิ กรุงเทพมหานคร.':'บางกะปิ','กเกร็ด':'ปากเกร็ด',
 'หนองจอก กรุงเทพมหานคร':'หนองจอก', 'สัังขละบุรี':'สังขละบุรี', 'คองสามวา':'คลองสามวา',
 'กิ่งอำเภอบัวลาย':'บัวลาย', 'เจะไอร้อง':'เจาะไอร้อง', 'ท่าม่วงกาญจนบุรี':'ท่าม่วง', 'ห้วยผึ้ึ่ง':'ห้วยผึ้ง',
 'สานมพราน':'สามพราน', 'พังตรุ':'ท่าม่วง', 'งบ้านฉาง':'บ้านฉาง', 'บ้านผืือ':'บ้านผือ', 'รพ.หล่มสัก':'หล่มสัก',
 'อ.เขาย้อย จ.เพชรบุรี':'เขาย้อย', 'เขตดุสิต':'ดุสิต', 'พุมธมณฑล':'พุทธมณฑล', 'บางซิ่อ':'บางซื่อ',
 'ปากเพลียว':'ปากเกลียว', 'คลองหลวง /หนองแซง':'คลองหลวง', 'ลานสัก-Cupทัพทัน':'ลานสัก',
 'มโรมย์':'มโนรมย์', 'เขตปทุม':'ปทุมวัน', 'เขตจตุจักร':'จตุจักร', 'นหว้า':'นาหว้า', 'ตรอน ทุ่งเสลี่ยม':'ทุ่งเสลี่ยม',
 'ราษำร์บูรณะ':'ราษฎร์บูรณะ', 'ลากพร้าว':'ลาดพร้าว', 'อ.กะพ้อ':'กะพ้อ', 'อ.ปางศิลาทอง':'ปางศิลาทอง',
 'กิ่งอำเภอบางเสาธง':'บางเสาธง', 'เขตสาธร':'สาธร', 'หนองแขม กรุงเทพมหานคร':'หนองแขม',
 'บ้านโปาง':'บ้านโป่ง', 'ศรี\u200bราชา':'ศรีราชา', 'นบพิดำ':'นบพิตำ', 'อ.เชียรใหญ่':'เชียรใหญ่',
 'บางละมุงชลบุรี':'บางละมุง', 'เมืองปัตตานี-':'เมืองปัตตานี', 'วานรนิิวาส':'วานรนิวาส', 'เมืองศีรสะเกษ':'เมืองศรีสะเกษ',
 'บางประปิ':'บางกระปิ', 'เมืองจันทรบุรี':'เมืองจันทบุรี', 'กิ่งอำเภอโนนนารายณ์':'โนนนารายณ์',
 'เขาคิฌกูฏ':'เขาคิชฌกูฏ', 'บางน้ำเปริ้ยว':'บางน้ำเปรี้ยว', 'ท่าเรื่อ':'ท่าเรือ', 'เมืองนครศรีธรรมราข':'เมืองนครศรีธรรมราช',
 'เขตทุ่งครุ':'ทุ่งครุ', 'ท่่าบ่อ':'ท่าบ่อ', 'เมืองนนทบรี':'เมืองนนทบุรี',  'เขตบางเขน':'บางเขน',
 'อำเภอเมืองนนทบุรี':'เมืองนนทบุรี', 'ปรวกแดง':'ปลวกแดง', 'เขตบางนาตราด':'บางนาตราด',
 'อ.เมืองอำนาจเจริญ จ.อำนาจเจริญ':'เมืองอำนาจเจริญ', 'ศรีสวัสดิ์\xa0':'ศรีสวัสดิ์', 'เขตคลองขวาง':'คลองขวาง',
 'โพนพิสััย':'โพนพิสัย', 'เมืองอำนาจ':'เมืองอำนาจเจริญ', 'อ.สามพราน จ.นครปฐม':'สามพราน',
'เมืองจันทบุรี\xa0':'เมืองจันทบุรี', 'ป้อมปราบฯ':'ป้อมปราบศัตรูพ่าย', 'เปือยน้้อย':'เปือยน้อย',
 'เมืองกาฬสิินธุ์':'เมืองกาฬสินธุ์', 'อ.หนองฉาง  จ.อุทัยธานี':'หนองฉาง', 'หัวหมาก กรุงเทพมหานคร':'หัวหมาก',
 'เมืองฉะเชิงเมรา':'เมืองฉะเชิงเฉรา', 'หัวยคต':'ห้วยคต', 'เมืองขอนแก่่น':'เมืองขอนแก่น',
 'ทุ้งกระเบน':'คุ้งกระเบน', 'เขตคลองตัน':'คลองตัน', 'อ.ประเวศ กรุงเทพมหานคร.':'ประเวศ',
 'เขตทุ่งครู':'ทุ่งครู่', 'เมืองสตล':'เมืองสตูล', 'ดอนเมือง กรุงเทพ':'ดอนเมือง', 'เมืิอง':'เมือง',
 'สีีคิ้ว':'สีคิ้ว', 'ปากเกร็ดจ.นนทบุรี':'ปากเกร็ด', 'สองพีน้อง':'สองพี่น้อง', 'เมืืองมหาสารคาม':'เมืองมหาสารคาม',
 'เขตลาดกระบัง':'ลาดกระบัง', 'เขตปทุมเวศ กรุงเทพมหานคร':'ปทุมเวศ', 'เขตคลองมหานาค':'คลองมหานาค',
 'เมืองกาญฯ':'เมืองกาญจนบุรี', 'กันททรลักษ์':'กันทรลักษณ์', 'เมือง/กรุงเทพมหานคร':'เมือง',
 'อ.สวนผึ้ง':'สวนผึ้ง', 'บางเขน\xa0':'บางเขน', '\xa0เขตดินแดง':'ดินแดง', 'อ.บ้านไผ่':'บ้านไผ่',
 'สตูล':'เมืองสตูล', 'อ.เมืองปัตตานี':'เมืองปัตตานี', 'สมุทรปราการ':'เมืองสมุทรปราการ'}, inplace=True)

In [208]:
data1234.head()

,announce_date,age,risk,province_of_onset,district_of_onset
0,12/1/2020,61.0,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,ไม่มีข้อมูล
1,17/1/2020,74.0,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,ไม่มีข้อมูล
2,22/1/2020,73.0,คนต่างชาติเดินทางมาจากต่างประเทศ,นครปฐม,เมือง
3,22/1/2020,68.0,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,ไม่มีข้อมูล
4,24/1/2020,66.0,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,ไม่มีข้อมูล

In [211]:
data_t= data1234.merge(data_lab,how='left',left_on='district_of_onset',right_on = 'district') 
data_t

,announce_date,age,risk,province_of_onset,district_of_onset,orgth,telephone,address,district,npsts,pooledsaliva,pooledswab
0,12/1/2020,61.0,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,ไม่มีข้อมูล,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,17/1/2020,74.0,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,ไม่มีข้อมูล,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,22/1/2020,73.0,คนต่างชาติเดินทางมาจากต่างประเทศ,นครปฐม,เมือง,โรงพยาบาลราชพฤกษ์,0-4333-3555,456 หมู่ 14 ถนนมิตรภาพ ตำบลในเมือง อำเภอเมือง ...,เมือง,เปิดตรวจแล้ว,ไม่ระบุ,ไม่ระบุ
3,22/1/2020,73.0,คนต่างชาติเดินทางมาจากต่างประเทศ,นครปฐม,เมือง,บริษัท เนชั่นแนล เฮลท์แคร์ ซิสเท็มส์ จำกัด สาข...,076298298 ต่อ5111,ไม่ระบุ,เมือง,เปิดตรวจแล้ว,ไม่ระบุ,ไม่ระบุ
4,22/1/2020,68.0,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,ไม่มีข้อมูล,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
7577439,15/3/2022,36.943725,ทัณฑสถาน/เรือนจำ,ไม่มีข้อมูล,ไม่มีข้อมูล,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7577440,15/3/2022,36.943725,ทัณฑสถาน/เรือนจำ,ไม่มีข้อมูล,ไม่มีข้อมูล,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7577441,15/3/2022,36.943725,ทัณฑสถาน/เรือนจำ,ไม่มีข้อมูล,ไม่มีข้อมูล,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7577442,15/3/2022,36.943725,ทัณฑสถาน/เรือนจำ,ไม่มีข้อมูล,ไม่มีข้อมูล,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7577443,15/3/2022,36.943725,ทัณฑสถาน/เรือนจำ,ไม่มีข้อมูล,ไม่มีข้อมูล,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [213]:
data_tcn =data_t.dropna()
data_tcn

,announce_date,age,risk,province_of_onset,district_of_onset,orgth,telephone,address,district,npsts,pooledsaliva,pooledswab
2,22/1/2020,73.0,คนต่างชาติเดินทางมาจากต่างประเทศ,นครปฐม,เมือง,โรงพยาบาลราชพฤกษ์,0-4333-3555,456 หมู่ 14 ถนนมิตรภาพ ตำบลในเมือง อำเภอเมือง ...,เมือง,เปิดตรวจแล้ว,ไม่ระบุ,ไม่ระบุ
3,22/1/2020,73.0,คนต่างชาติเดินทางมาจากต่างประเทศ,นครปฐม,เมือง,บริษัท เนชั่นแนล เฮลท์แคร์ ซิสเท็มส์ จำกัด สาข...,076298298 ต่อ5111,ไม่ระบุ,เมือง,เปิดตรวจแล้ว,ไม่ระบุ,ไม่ระบุ
8,26/1/2020,73.0,คนต่างชาติเดินทางมาจากต่างประเทศ,ประจวบคีรีขันธ์,หัวหิน,โรงพยาบาลหัวหิน,0-3252-3000,กลุ่มงานเทคนิคการแพทย์ 30/2 ต.หัวหิน อ.หัวหิน ...,หัวหิน,เปิดตรวจแล้ว,เปิดตรวจแล้ว,เปิดตรวจแล้ว
14,28/1/2020,32.0,คนต่างชาติเดินทางมาจากต่างประเทศ,ภูเก็ต,เมือง,โรงพยาบาลราชพฤกษ์,0-4333-3555,456 หมู่ 14 ถนนมิตรภาพ ตำบลในเมือง อำเภอเมือง ...,เมือง,เปิดตรวจแล้ว,ไม่ระบุ,ไม่ระบุ
15,28/1/2020,32.0,คนต่างชาติเดินทางมาจากต่างประเทศ,ภูเก็ต,เมือง,บริษัท เนชั่นแนล เฮลท์แคร์ ซิสเท็มส์ จำกัด สาข...,076298298 ต่อ5111,ไม่ระบุ,เมือง,เปิดตรวจแล้ว,ไม่ระบุ,ไม่ระบุ
...,...,...,...,...,...,...,...,...,...,...,...,...
7577385,15/3/2022,46.0,อื่นๆ,กรุงเทพมหานคร,ห้วยขวาง,โรงพยาบาลพระรามเก้า,0-2202-9999 ต่อ 11710-11712,โรงพยาบาลพระรามเก้า เลขที่ 99 ถ.พระรามเก้า บาง...,ห้วยขวาง,เปิดตรวจแล้ว,ไม่ระบุ,ไม่ระบุ
7577386,15/3/2022,46.0,อื่นๆ,กรุงเทพมหานคร,ห้วยขวาง,MIC Lab (บริษัทเมดิคอล อินโนเวชัน เซ็นเตอร์ จำ...,0-2101-6345,เลขที่ 7 ซอยจัดสรร ถนนสุทธิสารวินิจฉัย แขวงสาม...,ห้วยขวาง,เปิดตรวจแล้ว,ไม่ระบุ,เปิดตรวจแล้ว
7577387,15/3/2022,46.0,อื่นๆ,กรุงเทพมหานคร,ห้วยขวาง,โรงพยาบาลปิยะเวท,0-2129-5555,โรงพยาบาลปิยะเวท 998 ถนนริมคลองสามเสน แขวงบางะ...,ห้วยขวาง,เปิดตรวจแล้ว,ไม่ระบุ,ไม่ระบุ
7577388,15/3/2022,46.0,อื่นๆ,กรุงเทพมหานคร,ห้วยขวาง,บริษัทเนชั่นแนล เฮลท์แคร์ ซิสเท็มส์ จำกัด สาขา...,0-2467-1111 ต่อ 3284,2301/2 ถนน เพชรบุรีตัดใหม่ แขวง บางกะปิ เขตห้ว...,ห้วยขวาง,เปิดตรวจแล้ว,ไม่ระบุ,ไม่ระบุ
7577389,15/3/2022,46.0,อื่นๆ,กรุงเทพมหานคร,ห้วยขวาง,โรงพยาบาลเพชรเวช,1390,"2469/13,15 ถ.เพชรบุรีตัดใหม่ ระหว่างแยก เอกมัย...",ห้วยขวาง,เปิดตรวจแล้ว,ไม่ระบุ,ไม่ระบุ

In [215]:
covid_dist = data_tcn.groupby('district')['risk'].count()
covid_dist

district
กบินทร์บุรี    12086
กระทุ่มแบน     97893
กระนวน           702
กระบุรี          892
กะทู้           4819
               ...
โคกโพธิ์        3949
โพธาราม         8112
โพนทอง          3169
ไทรน้อย         6033
ไม่ระบุ         7200
Name: risk, Length: 242, dtype: int64

In [216]:
covid_df = pd.DataFrame(covid_dist)
covid_noindex = covid_df.reset_index()
covid_noindex

        district   risk
0    กบินทร์บุรี  12086
1     กระทุ่มแบน  97893
2         กระนวน    702
3        กระบุรี    892
4          กะทู้   4819
..           ...    ...
237     โคกโพธิ์   3949
238      โพธาราม   8112
239       โพนทอง   3169
240      ไทรน้อย   6033
241      ไม่ระบุ   7200

[242 rows x 2 columns]

In [226]:
data_dis1= covid_noindex.merge(data_lab,how='left',left_on='district',right_on = 'district') 
data_dis1

,district,risk,orgth,telephone,address,npsts,pooledsaliva,pooledswab,province
0,กบินทร์บุรี,12086,โรงพยาบาลกบินทร์บุรี,0-3728-8196,ไม่ระบุ,เปิดตรวจแล้ว,ไม่ระบุ,ไม่ระบุ,ปราจีนบุรี
1,กระทุ่มแบน,97893,โรงพยาบาลกระทุ่มแบน,0-3447-0750,450/4 ถนนสุคนนิวิท ต.ตลาด อ.กระทุ่มแบน จ.สมุทร...,เปิดตรวจแล้ว,ไม่ระบุ,ไม่ระบุ,สมุทรสาคร
2,กระทุ่มแบน,97893,โรงพยาบาลมหาชัย 2,0-2431-0054,ไม่ระบุ,เปิดตรวจแล้ว,ไม่ระบุ,ไม่ระบุ,สมุทรสาคร
3,กระทุ่มแบน,97893,โรงพยาบาลวิชัยเวช อินเตอร์เนชั่นแนล อ้อมน้อย,02-441-7899,ไม่ระบุ,เปิดตรวจแล้ว,ไม่ระบุ,ไม่ระบุ,สมุทรสาคร
4,กระนวน,702,โรงพยาบาลสมเด็จพระยุพราชกระนวน,0-4325-1302,ไม่ระบุ,เปิดตรวจแล้ว,ไม่ระบุ,ไม่ระบุ,ขอนแก่น
...,...,...,...,...,...,...,...,...,...
507,ไม่ระบุ,7200,วินเมด คลินิกเทคนิคการแพทย์,ไม่ระบุ,ไม่ระบุ,เปิดตรวจแล้ว,ไม่ระบุ,ไม่ระบุ,กรุงเทพมหานคร
508,ไม่ระบุ,7200,คลินิกเทคนิคการแพทย์ ยู เวลเนส เซ็นเตอร์,ไม่ระบุ,ไม่ระบุ,เปิดตรวจแล้ว,ไม่ระบุ,ไม่ระบุ,กรุงเทพมหานคร
509,ไม่ระบุ,7200,หนองคายเฮลท์แล็บ คลินิกเทคนิคการแพทย์,ไม่ระบุ,ไม่ระบุ,เปิดตรวจแล้ว,ไม่ระบุ,ไม่ระบุ,หนองคาย
510,ไม่ระบุ,7200,บริษัท เนชั่นแนล เฮลท์แคร์ ซิสเท็มส์ จำกัด สาข...,ไม่ระบุ,ไม่ระบุ,เปิดตรวจแล้ว,ไม่ระบุ,ไม่ระบุ,พิษณุโลก
511,ไม่ระบุ,7200,บริษัท เนชั่นแนล เฮลท์แคร์ ซิสเท็มส์ จำกัด สาข...,ไม่ระบุ,ไม่ระบุ,เปิดตรวจแล้ว,ไม่ระบุ,ไม่ระบุ,ตราด

# ส่วนใหม่

In [230]:
data_dis11= data_dis1.merge(province_df,how='left',left_on='province',right_on = 'province') 
data_dis11.head()

,district,risk,orgth,telephone,address,npsts,pooledsaliva,pooledswab,province,6 ภูมิภาค (ภูมิศาสตร์)
0,กบินทร์บุรี,12086,โรงพยาบาลกบินทร์บุรี,0-3728-8196,ไม่ระบุ,เปิดตรวจแล้ว,ไม่ระบุ,ไม่ระบุ,ปราจีนบุรี,ตะวันออก
1,กระทุ่มแบน,97893,โรงพยาบาลกระทุ่มแบน,0-3447-0750,450/4 ถนนสุคนนิวิท ต.ตลาด อ.กระทุ่มแบน จ.สมุทร...,เปิดตรวจแล้ว,ไม่ระบุ,ไม่ระบุ,สมุทรสาคร,กลาง
2,กระทุ่มแบน,97893,โรงพยาบาลมหาชัย 2,0-2431-0054,ไม่ระบุ,เปิดตรวจแล้ว,ไม่ระบุ,ไม่ระบุ,สมุทรสาคร,กลาง
3,กระทุ่มแบน,97893,โรงพยาบาลวิชัยเวช อินเตอร์เนชั่นแนล อ้อมน้อย,02-441-7899,ไม่ระบุ,เปิดตรวจแล้ว,ไม่ระบุ,ไม่ระบุ,สมุทรสาคร,กลาง
4,กระนวน,702,โรงพยาบาลสมเด็จพระยุพราชกระนวน,0-4325-1302,ไม่ระบุ,เปิดตรวจแล้ว,ไม่ระบุ,ไม่ระบุ,ขอนแก่น,ตะวันออกเฉียงเหนือ

In [231]:
District = {'district':'อำเภอ'}
# call rename () method
data_dis11.rename(columns=District,
          inplace=True)

In [238]:
Province = {'province':'จังหวัด'}
# call rename () method
data_dis11.rename(columns=Province,
          inplace=True)

In [235]:
Number = {'risk':'จำนวนผู้ติดเชื้อ'}
# call rename () method
data_dis11.rename(columns=Number,
          inplace=True)

In [239]:
data_dis11

,อำเภอ,จำนวนผู้ติดเชื้อ,orgth,telephone,address,npsts,pooledsaliva,pooledswab,จังหวัด,6 ภูมิภาค (ภูมิศาสตร์)
0,กบินทร์บุรี,12086,โรงพยาบาลกบินทร์บุรี,0-3728-8196,ไม่ระบุ,เปิดตรวจแล้ว,ไม่ระบุ,ไม่ระบุ,ปราจีนบุรี,ตะวันออก
1,กระทุ่มแบน,97893,โรงพยาบาลกระทุ่มแบน,0-3447-0750,450/4 ถนนสุคนนิวิท ต.ตลาด อ.กระทุ่มแบน จ.สมุทร...,เปิดตรวจแล้ว,ไม่ระบุ,ไม่ระบุ,สมุทรสาคร,กลาง
2,กระทุ่มแบน,97893,โรงพยาบาลมหาชัย 2,0-2431-0054,ไม่ระบุ,เปิดตรวจแล้ว,ไม่ระบุ,ไม่ระบุ,สมุทรสาคร,กลาง
3,กระทุ่มแบน,97893,โรงพยาบาลวิชัยเวช อินเตอร์เนชั่นแนล อ้อมน้อย,02-441-7899,ไม่ระบุ,เปิดตรวจแล้ว,ไม่ระบุ,ไม่ระบุ,สมุทรสาคร,กลาง
4,กระนวน,702,โรงพยาบาลสมเด็จพระยุพราชกระนวน,0-4325-1302,ไม่ระบุ,เปิดตรวจแล้ว,ไม่ระบุ,ไม่ระบุ,ขอนแก่น,ตะวันออกเฉียงเหนือ
...,...,...,...,...,...,...,...,...,...,...
507,ไม่ระบุ,7200,วินเมด คลินิกเทคนิคการแพทย์,ไม่ระบุ,ไม่ระบุ,เปิดตรวจแล้ว,ไม่ระบุ,ไม่ระบุ,กรุงเทพมหานคร,กลาง
508,ไม่ระบุ,7200,คลินิกเทคนิคการแพทย์ ยู เวลเนส เซ็นเตอร์,ไม่ระบุ,ไม่ระบุ,เปิดตรวจแล้ว,ไม่ระบุ,ไม่ระบุ,กรุงเทพมหานคร,กลาง
509,ไม่ระบุ,7200,หนองคายเฮลท์แล็บ คลินิกเทคนิคการแพทย์,ไม่ระบุ,ไม่ระบุ,เปิดตรวจแล้ว,ไม่ระบุ,ไม่ระบุ,หนองคาย,ตะวันออกเฉียงเหนือ
510,ไม่ระบุ,7200,บริษัท เนชั่นแนล เฮลท์แคร์ ซิสเท็มส์ จำกัด สาข...,ไม่ระบุ,ไม่ระบุ,เปิดตรวจแล้ว,ไม่ระบุ,ไม่ระบุ,พิษณุโลก,กลาง
511,ไม่ระบุ,7200,บริษัท เนชั่นแนล เฮลท์แคร์ ซิสเท็มส์ จำกัด สาข...,ไม่ระบุ,ไม่ระบุ,เปิดตรวจแล้ว,ไม่ระบุ,ไม่ระบุ,ตราด,ตะวันออก

In [240]:
data_final = data_dis11[['จังหวัด','6 ภูมิภาค (ภูมิศาสตร์)','อำเภอ','จำนวนผู้ติดเชื้อ','orgth','telephone','npsts','pooledsaliva','pooledswab']] 
data_final

,จังหวัด,6 ภูมิภาค (ภูมิศาสตร์),อำเภอ,จำนวนผู้ติดเชื้อ,orgth,telephone,npsts,pooledsaliva,pooledswab
0,ปราจีนบุรี,ตะวันออก,กบินทร์บุรี,12086,โรงพยาบาลกบินทร์บุรี,0-3728-8196,เปิดตรวจแล้ว,ไม่ระบุ,ไม่ระบุ
1,สมุทรสาคร,กลาง,กระทุ่มแบน,97893,โรงพยาบาลกระทุ่มแบน,0-3447-0750,เปิดตรวจแล้ว,ไม่ระบุ,ไม่ระบุ
2,สมุทรสาคร,กลาง,กระทุ่มแบน,97893,โรงพยาบาลมหาชัย 2,0-2431-0054,เปิดตรวจแล้ว,ไม่ระบุ,ไม่ระบุ
3,สมุทรสาคร,กลาง,กระทุ่มแบน,97893,โรงพยาบาลวิชัยเวช อินเตอร์เนชั่นแนล อ้อมน้อย,02-441-7899,เปิดตรวจแล้ว,ไม่ระบุ,ไม่ระบุ
4,ขอนแก่น,ตะวันออกเฉียงเหนือ,กระนวน,702,โรงพยาบาลสมเด็จพระยุพราชกระนวน,0-4325-1302,เปิดตรวจแล้ว,ไม่ระบุ,ไม่ระบุ
...,...,...,...,...,...,...,...,...,...
507,กรุงเทพมหานคร,กลาง,ไม่ระบุ,7200,วินเมด คลินิกเทคนิคการแพทย์,ไม่ระบุ,เปิดตรวจแล้ว,ไม่ระบุ,ไม่ระบุ
508,กรุงเทพมหานคร,กลาง,ไม่ระบุ,7200,คลินิกเทคนิคการแพทย์ ยู เวลเนส เซ็นเตอร์,ไม่ระบุ,เปิดตรวจแล้ว,ไม่ระบุ,ไม่ระบุ
509,หนองคาย,ตะวันออกเฉียงเหนือ,ไม่ระบุ,7200,หนองคายเฮลท์แล็บ คลินิกเทคนิคการแพทย์,ไม่ระบุ,เปิดตรวจแล้ว,ไม่ระบุ,ไม่ระบุ
510,พิษณุโลก,กลาง,ไม่ระบุ,7200,บริษัท เนชั่นแนล เฮลท์แคร์ ซิสเท็มส์ จำกัด สาข...,ไม่ระบุ,เปิดตรวจแล้ว,ไม่ระบุ,ไม่ระบุ
511,ตราด,ตะวันออก,ไม่ระบุ,7200,บริษัท เนชั่นแนล เฮลท์แคร์ ซิสเท็มส์ จำกัด สาข...,ไม่ระบุ,เปิดตรวจแล้ว,ไม่ระบุ,ไม่ระบุ

In [244]:
data_final.to_csv('data_final2.csv', encoding="TIS-620")